### ISSUE TITLE
Show some informations when a deposit is being processed.

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#101]
I think Breez should show some informations when a deposit is being processed, like:
1- The amount
2- Link of the transaction
3- Maybe the ETA to confirm.

The informations should be show on this window:

![photo5132021882319644700](https://user-images.githubusercontent.com/1178856/58293654-c67d9580-7d9c-11e9-8e6e-f1edd827a71d.jpg)

**Comment by kingonly** [comment]
Fixed in https://github.com/breez/breezmobile/pull/126
<img width="426" alt="Screen Shot 2019-07-22 at 12 53 09 PM" src="https://user-images.githubusercontent.com/31890660/61628338-af6aff00-ac8a-11e9-9861-9ea5edbf1865.png">
