### ISSUE TITLE
LNURLW:// QR Code of Pull Payments doesn't scan with Breez (but PhoenixWallet)

### ISSUE THREAD

**Issue by petzsch** [breez/breezmobile#1015]
There is a problem with the lnurlw:// QR Code presented by btcpayserver pull payments - The Breez app doesn't scan it.
According to a user it works fine with PhoenixWallet.

See the detailed problem report here: https://github.com/btcpayserver/btcpayserver/issues/4401

**Comment by kingonly** [comment]
Could you please provide a URl for us to test? We need to repro...

**Comment by tlindi** [comment]
Posting this to activate following The issue.

**Comment by kingonly** [comment]
> Posting this to activate following The issue.

You can subscribe to an issue

**Comment by tlindi** [comment]
> > Posting this to activate following The issue.
> 
> You can subscribe to an issue

Oops - Subcription was not available from mobile view of github - sorry about spam :'-(

**Comment by petzsch** [comment]
couldn't repro the issue on the current version.
On old versions there was an issue, probably having something to do with my site being dual stack (IPv4+IPv6)
