### ISSUE TITLE
Unexpected funds window 

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#102]
Hi,

I had channel closed and I after the funds was confirmed I see a window of Unexpected funds.
Suggestion:
1- Add an option to send all available funds to external wallet.
2- Add a button to use all available funds to open the channel again.

![photo5134419367424010233](https://user-images.githubusercontent.com/1178856/58339223-7e538700-7e1f-11e9-8228-03ad2ded8705.jpg)

**Comment by kingonly** [comment]
In latest release, all funds are sent (removed amount field).

**Comment by bitcoinuser** [comment]
Great. I don't think it's necessary to add a button to use all available funds to open the channel again.
