### ISSUE TITLE
When a channel is closed, balance goes to 0 with no messages of what happened.

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#103]
Hi,

I had an experience of a closed channel on Breez and the balance went to 0 and no message showed of what happened. So I thought the funds was lost.

Suggestion:

1- Maybe show a message telling the user that the channel was closed and the funds was not lost, and ask if the users want to redeposit the funds to lightning again or withdraw the funds to an external wallet.

**Comment by bitcoinuser** [comment]
And I think should show a popup to ask if the user wants to send the logs to breez to analyze what happened.

**Comment by kingonly** [comment]
closed channels now appear in the payments list
