### ISSUE TITLE
app_fi.arp translation of "backup_phrase_instructions" is cut

### ISSUE THREAD

**Issue by tlindi** [breez/breezmobile#1034]
End user @juhi24 reported this issue to me. Instructions are not completely visible. Finnish translation is likely longer than original English one. And last centence is cut on UI.

![image](https://user-images.githubusercontent.com/7249767/210158102-74f74295-0c2d-43ad-99be-478f6622dd0f.png)

Could you make more space on UI for whole translation to fit / shown. Or should I shorten translation text?

Could @ademar111190 comment?

**Comment by ademar111190** [comment]
It should show all the text; I'll fix it. @tlindi

**Comment by tlindi** [comment]
@ademar111190 Could you also fix this too on same PR? 

"Pay To" <nodename> is in translation too long end of <nodename> is replaced with "..."

![image](https://user-images.githubusercontent.com/7249767/210558572-55521b63-c1ec-4492-bc4c-662e1c8c882e.png)

Fix could be either continuing <nodename> to new line (which in this case I think break UI view) 
or applying change to app_fi.arb

line 1731
  "lnurl_fetch_invoice_pay_to_payee": "Maksun vastaanottaja {payee}",
  
  ->
  
    "lnurl_fetch_invoice_pay_to_payee": "Saaja {payee}",
