### ISSUE TITLE
With translations amount of minSats and maxSats includes "sats"

### ISSUE THREAD

**Issue by tlindi** [breez/breezmobile#1037]
Example app_fi.arb line 33

`"invoice_btc_address_warning_with_min_fee_account_connected": "Osoitteeseen voi tallettaa vähintään {minSats} ja enintään {maxSats} maksuja. Yli {liquidity} talletuksista veloitetaan {setUpFee}% avauskulu ja kuitenkin vähintään {minFee}.",
`

![IMG_20230109_232134_889](https://user-images.githubusercontent.com/7249767/211577374-a000200b-a372-4ac0-a3b5-00af12919521.jpg)

{minSats} turns to "2000 sats" which is incorrect in Finnish. Correct would be "2000 sat". 

Same with "{maxSats}" but for comparison "{setUpFee}" doesn't include unit eg "%" sign.

thanks for reporting @juhi24

**Comment by ubbabeck** [comment]
Closing this as feel free to reopen if wrongfully closed.
