### ISSUE TITLE
UI suggestion to Breez

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#104]
Hi,

I think will be great if Breez implement this kind of interface:

1- Have three "tabs" on top (QRCODE SCANNER / MESSAGES / TRANSACTIONS). The QRCODE SCANNER should be like the CAMERA on whatsapp app, because it's easier and faster than have to go to menu and click pay invoice.

![24617988-696x463](https://user-images.githubusercontent.com/1178856/58371111-e5873f00-7ee4-11e9-8ac0-52e9c6d9e8ec.jpg)

2- One app that Breez could use as example is CIRCLEPAY, they have two tabs (MESSSAGES / TRANSACTIONS)

![photo5138982040031569934](https://user-images.githubusercontent.com/1178856/58371130-136c8380-7ee5-11e9-83f6-4a9db1b1684d.jpg)

3- I think Breez could have some other mechanism than the (connect to pay) function. I would like to see a mechanism that allows Breez users add others Breez users as contact on app, so that I shouldn't have to send a link to pay my friends. I don't know if is possible but will be great if each Breez user could have an ID and when shared with other Breez users, I could connect to them and send messages or satoshis.
I ask: is it possible to send people satoshis or messages even if the users are not online? maybe with tecnology like relay node. So the user receive a notification telling that he received a message or money and asking to open the app.

The way to add contacts could be by sharing a link or qrcode. One example is CIRCLEPAY: 

![photo5138982040031569935](https://user-images.githubusercontent.com/1178856/58371377-24b68f80-7ee7-11e9-8bb8-fc01357fa68c.jpg)

**Comment by kingonly** [comment]
Added invoice actions in https://github.com/breez/breezmobile/pull/125
Other suggestions are more fundamental to be handles as an issue.
