### ISSUE TITLE
High cellular data usage

### ISSUE THREAD

**Issue by float00** [breez/breezmobile#1040]
Cellular data usage of Breez seems high. Any improvement might make it viable for more people.

My phone (Apple iPhone running latest iOS) spends 90% on the time on wifi, but within a 1 month period Breez consumed nearly 2GB of cellular data. 

I wonder what communication is consuming most of this data? Is there anything we can optimise to lower the usage?

**Comment by kingonly** [comment]
Blockchain sync (via Neutrino). We're working on another product based on Greenlight where the user nodes are on the cloud. This product will be optimized in terms of data usage.
