### ISSUE TITLE
How did you put Lnd and Neutrino on Android ,iOS?

### ISSUE THREAD

**Issue by Lursun** [breez/breezmobile#105]
How did you put Lnd and Neutrino on Android, iOS?
I can't find code about that.

**Comment by kingonly** [comment]
Please see our fork here: https://github.com/breez/lightninglib

**Comment by Lursun** [comment]
@kingonly lightninglib is lnd. Ｗhere is neutrino? Is it run on remote host?

**Comment by kingonly** [comment]
No. We run lnd as a library with a Neutrino provider that works against any BIP 157 full node.
