### ISSUE TITLE
Backup restore doesn't restore Currencies, PoS settings and user name or image

### ISSUE THREAD

**Issue by tlindi** [breez/breezmobile#1053]
Something has borken after these were implemented

https://github.com/breez/breezmobile/issues/780

https://github.com/breez/breezmobile/pull/890

In addition to those - After restore PoS default invoicing currency will be BTC instead of clean install "sat". And restore has never restored previous setting (eg EUR).

I have screen recording from Nokia 5.4 Android 12 where issue is seen. Video includes confidential information, so please advice how I could deliver it to you.

**Comment by kingonly** [comment]
@erdemyerebasmaz can you please take a look?
@tlindi we don't backup the POS last selected currency because it will trigger too many backups and it's not considered a setting.

**Comment by erdemyerebasmaz** [comment]
> @erdemyerebasmaz can you please take a look?
> @tlindi we don't backup the POS last selected currency because it will trigger too many backups and it's not considered a setting.

@kingonly this regression is caused by dark theme changes. I need to discuss the reasoning of behind a change with Roei.
@tlindi Leaving out currencies is the only design choice we made. POS Settings and other user preferences will be restored after the fix.

**Comment by kingonly** [comment]
@erdemyerebasmaz DM me on slack

**Comment by tlindi** [comment]
> > @erdemyerebasmaz can you please take a look?
> > @tlindi we don't backup the POS last selected currency because it will trigger too many backups and it's not considered a setting.
> 
> @kingonly this regression is caused by dark theme changes. I need to discuss the reasoning behind a change with Roei. @tlindi Leaving out currencies is the only design choice we made. POS Settings and other user preferences will be restored after the fix.

ACK
