### ISSUE TITLE
Amount should be empty instead max on lnurl-withdraw 

### ISSUE THREAD

**Issue by kingonly** [breez/breezmobile#1057]

**Comment by kingonly** [comment]
@ubbabeck please take a look, DM me if needed. Make sure not to create regressions in the POS flow.

**Comment by kingonly** [comment]
We should still set the amount when the min & max value are equal.

**Comment by erdemyerebasmaz** [comment]
@ubbabeck See applyWithdrawFetchResponse and compare it with applyPayFetchResponse on how to leave it empty.
Afterwards, I suggest you replace the comparison logic on both instances by adding isFixedAmount variable to both WithdrawFetchResponse & PayFetchResponse for checking if min & max amounts of response are equal.

**Comment by ubbabeck** [comment]
This issue has been resolved and merged to master. #1060
