### ISSUE TITLE
If we enable Tor, Kollider app do not open

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#1059]
Hi,

If we enable Tor, Kollider app do not open.

![photo_2023-02-05_13-37-01](https://user-images.githubusercontent.com/1178856/216832123-c897a70d-1253-4a71-a015-cbe85b6be812.jpg)

**Comment by kingonly** [comment]
@ubbabeck I reproduce, please take a look

**Comment by ubbabeck** [comment]
Where able to reproduce the error

I think this issue is might be manifesting itself in breezlib `go.Universe$proxyerror: invalid character '<' looking for beginning of value`

`E/BREEZUI: Error in method finishLNURLAuth: invalid character '<' looking for beginning of value
    go.Universe$proxyerror: invalid character '<' looking for beginning of value
        at bindings.Bindings.finishLNURLAuth(Native Method)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.breez.client.plugins.breez.breezlib.Breez$BreezTask.run(Breez.java:350)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)`

**Comment by ubbabeck** [comment]
This is most likely not related to tor, but lnurl. I have been able to reproduce the error on both iOS and android when tor is enabled (android) and disabled.

**Comment by ubbabeck** [comment]
Opened an issue in the kollider and asking them if they are blocking tor nodes. https://github.com/kolliderhq/kollider-api-client/issues/1

**Comment by erdemyerebasmaz** [comment]
Kollider has went [out of service](https://x.com/kollider_trade/status/1720428682072772708)(🫡 ) and will be removed on next release as part of:
- #1279 

Closing.
