### ISSUE TITLE
Support for BIP21 combined QR Codes with LNURL

### ISSUE THREAD

**Issue by petzsch** [breez/breezmobile#1063]
Hello,

at BTCPay Server there was a change how the new checkout system creates QR codes for top-up invoices (invoices without an amount).

We now use a payment url of the form:
bitcoin:BC1.....?lightning=LNURL...

However with Breez you get the error:
does not contain an LNURL: unknown response tag method: fetchLnurl

Here is a sample QR Code:
![grafik](https://user-images.githubusercontent.com/1374810/217586898-c48d9b53-1204-4e57-8552-f801dadc03c7.png)

if you need a fresh valid one, feel free to create an invoice [here](https://otr.4sats.net/?email=markus@petzsch.eu) for the last option (custom amount).

**Comment by kingonly** [comment]
I don't think it's related to bip21, I get the same error just trying to use the lnurl directly

**Comment by kingonly** [comment]
I get an error in Phoenix also
![Screenshot_2023-02-08-18-26-24-34_2c4670cdec682361b0cb8dd9581e9241](https://user-images.githubusercontent.com/31890660/217590678-47b2c913-f135-400e-8d1f-eb0ec4c479ac.jpg)

**Comment by kingonly** [comment]
And in WoS
![Uploading Screenshot_2023-02-08-18-28-10-89_2e58ba7a93d2a85265bb496e2041c89d.jpg…]()

**Comment by petzsch** [comment]
I see: I get the same error when pasting the LNURL part into it.
Also https://lightningdecoder.com/ doesn't like the lnurl either.

I will discuss this in the BTCPay mattermost... something is off here.

**Comment by kingonly** [comment]
Also in WoS
![Screenshot_2023-02-08-18-28-10-89_2e58ba7a93d2a85265bb496e2041c89d](https://user-images.githubusercontent.com/31890660/217591346-bfb82428-7b4a-49ee-9d9d-b4155fc607d7.jpg)

**Comment by kingonly** [comment]
@petzsch I'm closing for now. Feel free to open with more details if you think there's an issue with Breez.
