### ISSUE TITLE
Hide Invoice QR code on NFC Scan 

### ISSUE THREAD

**Issue by titusz** [breez/breezmobile#1064]
It might be a good idea to hide the Invoice QR code as soon as an LNURLw has been scanned via NFC in the Point of Sale app. So that users cannot pay via QR while an LNURLw payment is under way.

**Comment by kingonly** [comment]
If the payment is underway, we replace the QR with a spinner. Cc: @ademar111190

**Comment by titusz** [comment]
You are right. The spinner did not show up for me because the payment was to fast :)
