### ISSUE TITLE
Breez node disconnected for a long time and users do not know what is happening.

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#107]
Hi, 

Sometimes Breez node is disconnected for long time, so users open Breez wallet and don't have idea why they can't make or receive payments. 
Suggestion: When node is disconnected, show some kind of message on Breez app that service is offline and will be back soon.

**Comment by kingonly** [comment]
Great suggestion 👍

**Comment by tlindi** [comment]
Would be really nice feature :)

Consider also to notify of custom channels and custom Bitcoin node setting.

Maybe show "disconnected" error on Exclamation mark on top right, similar to Reclaim notification?
