### ISSUE TITLE
GUI regarding Breez synching to btc network is inaccurate. Stuck at 0%, but able to send transactions.

### ISSUE THREAD

**Issue by snarflakes** [breez/breezmobile#1075]
Been running breez on iOS for a long time, hadn't checked in on it in a while, upgraded it a month ago or so and noticed it is stuck at 0% sync.  I saw it go up to 2% once, but in general it is always at 0%. Odd thing is I was able to pay an invoice! And I just paid another one.  Is there a way to reset the  GUI showing accurate synchronization? 

Also! when trying to receive/create invoice it shows the 0% circle and just hangs  and is unable to create an invoice. So that part isn't working.

**Comment by kingonly** [comment]
Please see: https://doc.breez.technology/Bitcoin-node-synchronization.html
If the problem persists, let's handle this via email: contact AT breez DOT technology
