### ISSUE TITLE
Backup to another Android user account fails

### ISSUE THREAD

**Issue by tlindi** [breez/breezmobile#1076]
How to reproduce:

Restore Breez with Google account say X. Settings Backup and Security shows backup account X information at bottom of screen.
Setup new google account Y to phone. Remove account X from phone.
Go to breez, select backup. And see it does nothing. Exclamation sign is shown on top right and it stays there. 
Settings Backup and Security shows no backup information at bottom of screen.

Add old account X back to phone. Breez creates backups nicely. But it doesn't ask which of two account I'd like to backup.

I have video and lnd.log if needed. Please advice how to deliver them to you securely.

**Comment by kingonly** [comment]
@ademar111190 please investigate and follow up with @tlindi
