### ISSUE TITLE
WebDav backup not working

### ISSUE THREAD

**Issue by jeee** [breez/breezmobile#1079]
I added a webdav user and can reach the webdav site entering the url and user&pass in the browser but breez gives me either an invalid url on one device and on another 'Failed to connect with the remote server, please check your settings.'.

Apache seems to be running with the following config:

```
<Location /webdav/myusername>
        DAV On
        BrowserMatch "MSIE" AuthDigestEnableQueryStringHack=On
        AuthType Digest
        AuthName "myusername"
        AuthUserFile /var/www/clients/client1/web2/webdav/myusername.htdigest
        Require valid-user
        Options +Indexes
        Order allow,deny 
        Allow from all 
</Location>
```

**Comment by yaslama** [comment]
Can you confirm that you can read/write files and directories when using a webdav client? Using a browser is not the same as using a real webdav client.

**Comment by jeee** [comment]
Creating folders and uploading files seems to work fine from my android phone using WebDAV navigator.

**Comment by yaslama** [comment]
We support only basic authentication for webdav and not digest authentication because it's globally less secure. See https://httpd.apache.org/docs/2.4/mod/mod_auth_digest.html
