### ISSUE TITLE
The avatar icon appears as " - " when receiving via BTC address it should be " + "

### ISSUE THREAD

**Issue by Nackoo2000** [breez/breezmobile#1084]
1. Receive payment via BTC address
2. Send funds from another wallet

![photo_2023-03-13_14-41-16](https://user-images.githubusercontent.com/127208515/224727518-784865cd-748c-48dd-a539-a33da96600bc.jpg)

**Comment by roeierez** [comment]
@Nackoo2000 I also see 8476 sats as fee for the latest bitcoin transfer.
We should investigate why the fees is so high.

**Comment by kingonly** [comment]
@erdemyerebasmaz please take a look
