### ISSUE TITLE
Calendar filter doesn't work in POS reports

### ISSUE THREAD

**Issue by kingonly** [breez/breezmobile#1098]
![Screenshot_2023-03-19-20-06-58-13_73a31df444cba46df764485ac1a8c3ef](https://user-images.githubusercontent.com/31890660/226198003-bcbdaf9f-6973-4f3f-94ea-eea80a44bc17.jpg)

**Comment by kingonly** [comment]
@ademar111190 we can close, right?

**Comment by ademar111190** [comment]
Yes, I didn't mention the issue on the PR fixing it https://github.com/breez/breezmobile/pull/1103 my bad.
