### ISSUE TITLE
Remove support for 0 sat invoices

### ISSUE THREAD

**Issue by juscamarena** [breez/breezmobile#110]
0 sat invoices aren't safe.

On lnd irc recently:

For invoices with the amount field set to 0, isn't it possible for an intermediate node to do the following:

• assume the next hop is the final hop, send an UpdateAddHTLC with a lower amount than specified in the source's forwarding instructions
• If this fails with UnknownPaymentHash, assume that this is either not a "donation" invoice or that this node is not the final hop
• If this doesn't fail, they can claim the incoming htlc at a substantial profit
• In the failure case, just send the original UpdateAddHTLC received from the previous hop and call it a day

I've disabled support for them on bitrefill

**Comment by kingonly** [comment]
It's safe now
