### ISSUE TITLE
Sending all funds to a BTC address may fail

### ISSUE THREAD

**Issue by syrop** [breez/breezmobile#1107]
I had 103 792 satoshis. I wanted to send it all to a BTC address.

I submitted the operation for execution; it would show that I had only 1 satoshi left. Breez requires you to always have at least 2 satoshis in the wallet, so I think leaving just one satoshi behind was already a bug.

After 2 minutes of "pending" state the operation would disappear from the history with no error message displayed, and the satoshis were back in my balance. This happened many times.

WORKAROUND:
1. Remember how much money it is trying to send after calculating the fees
2. Manually type a similar amount (as opposed to "Use All Funds")
3. After the operation I have 191 sats left, so I may donate it to charity over Lightning, so that it is not wasted.

**Comment by kingonly** [comment]
Breez doesn't require you to have 2 sats in the wallet.
We have private channels to Boltz with 0 fees. In this case it seems the payment wasn't routed via the private channels and that's why you weren't able to send all funds. In normal operating, this shouldn't happen. We'll review our Boltz channels and work with them to prevent this from happening.

**Comment by syrop** [comment]
In the state I described, when I try to send 190 sats over LN-URL, I get a pop-up saying "Breez requires you to keep 2 sats in your balance".

**Comment by kingonly** [comment]
Not the same flow, there's a different logic in send all funds.

**Comment by kingonly** [comment]
Actually, our channels look good, so there's something else going on. We will follow up with you to understand the issue.

**Comment by yaslama** [comment]
@syrop, can you please send an email to contact@breez.technology? We'll try to understand the issue.

**Comment by kingonly** [comment]
Moving to support
