### ISSUE TITLE
APK version backup does nothing on ungoogled phone, add on-decice backup into some directory

### ISSUE THREAD

**Issue by anton-isidore** [breez/breezmobile#1108]
**The story:**

I have ungoogled phone. I have downloaded the apk and I hit the triangle warning to do backup. Clicked backup now and nothing happens. Is my wallet backed up? I haven't got any seed words. I am very confused user at this point.

Ok I go to settings. Here is encrypted backup settings I turn it on, I save seed.

But, the Google Drive is set as backup. Wait, I don't have it. I don't have even Google Play Services. 

So I have no backup after all...

**The problem**

This is very confusing for user and he/she can then easily thought that wallet is backed up but is isn't. Some error notification at least should be visible.

Also there seems to be standard that wallet will do backup on drive to some folder so it can be synced via sync of user's choice (Syncthing in my case). This should be probably added as backup method. So I don't have to run my own server. I am fine to backup channel backup just with Syncthing to my other devices.

Thanks!

**Comment by kingonly** [comment]
The problem is that we cannot rely on out of band sync because backup needs to happen immediately after the payment. Currently, WebDav is our way to provide an cloud backup for degoogled devices.
