### ISSUE TITLE
Accept comma in POS mode

### ISSUE THREAD

**Issue by ubbabeck** [breez/breezmobile#1111]
Some android models does not show dot `.` on the keyboard type `TextInputType.numberWithOptions`, but rather comma `,` so the user are not able to use decimal when adding a new item in the POS mode.
![comma](https://user-images.githubusercontent.com/36157890/229713981-1d2d753d-d212-40f6-8054-e45ca4b80ebd.jpeg)

**Comment by erdemyerebasmaz** [comment]
Tested this now and can't pinpoint the reason why but I was able to isolate the case where this behavior happens.

If you click on the price field after switching a currency there's only a comma on the keyboard, however, if you click any other text field then price field, the keyboard is displayed properly with both comma and a dot option again.

**Comment by tlindi** [comment]
FYI Comma is used as a decimal separator on some regions, so it would be nice to functionality be consistant.
