### ISSUE TITLE
Breez invoice scanning not complete if client moves to another wifi

### ISSUE THREAD

**Issue by tlindi** [breez/breezmobile#1125]
Found repeteable issue on Android.

I have WiFi on, used Breez on home wifi and I leave open Breez on background.

I go to merchant (my phone connects to their WiFi which I have saved to phone) I open my phone, scan their Breez invoice and My Breez hangs. No breez syncing to network is shown. No error about Breez offline is shown. Invoice read never completes no matter how long I wait. To recover I need to close BreezApp.

Then I scan invoice again and Breez will instantly sync, show question if I wanna pay and payment goes trougth instantly.

I have saved developer logs. Please let know where to send them if needed?

**Comment by ok300** [comment]
Hey @tlindi thanks for reporting this!

The connection handling went through several changes in the past months. We've just tested this with the current version and it works.

Is it still an issue for you? Let us know, we'd be glad to help get it solved.

**Comment by tlindi** [comment]
I have not tested for a while. I trust your tests and it's ok for me to close the issue.

**Comment by ok300** [comment]
Perfect, thanks!
