### ISSUE TITLE
Incompatible with 2022 device running Android 12 due to missing ABI support

### ISSUE THREAD

**Issue by WillCodeCo** [breez/breezmobile#1127]
Might it be possible to support ABIs such as `armeabi-v7a` ?  Unfortunately the current APKs are not compatible with Xiaomi Redmi A1 running Android 12, a device which was launched in 2022, so not mega ancient !

Devices such as these are very popular in China, so this could be a headache for many many potential users

**Comment by yaslama** [comment]
These (very) low end devices are using a stripped down version of Android (Android Go) which is 32 bits only and the current version of our app is 64 bits only. *But* we are working on a new app which will be 32 bits compatible.
