### ISSUE TITLE
[UX] POS: optional keypad to enter amount of item

### ISSUE THREAD

**Issue by MarnixCroes** [breez/breezmobile#1131]
Currently, every time the merchant clicks on an item, the item will be added +1.
So when the merchant wants to select the item 21 times, the merchant has to make 21 clicks. 100 items, 100 clicks etc...
Maybe higher amounts of items are not that common, but it can be: 21 meat balls, 100 plastic straws etc.
It would be an improvement if there is an optional keypad to enter the amount of a selected item.
For example when clicking here:
![image](https://user-images.githubusercontent.com/93143998/234529336-e8d7ad17-7c69-45f5-ba8d-6befd2ad27bf.png)

**Comment by kingonly** [comment]
Are you a merchant that is having a UX issue or this is just a suggestion?

**Comment by MarnixCroes** [comment]
it's a suggestion

**Comment by kingonly** [comment]
Noted. We'll put it on the back burner for now.
