### ISSUE TITLE
"Warning" icon shouldn't be static when a process is happening

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#114]
Hi,

Today I opened Breez and I saw on top right the warning button. So I clicked on it and it told me to backup again to Google Drive, so I did it. After I do it, the warning button still appear for some minutes, so I imagined that the process didn't work, so I clicked on it again. 

Suggestion: When a process is "happening" the warning button shouldn't be static. Should be a spinning icon.

![photo4929449552235309067](https://user-images.githubusercontent.com/1178856/59940728-d2a75200-9431-11e9-8fc7-3dd2423b2263.jpg)

**Comment by kingonly** [comment]
This is a great suggestion and we've an open task on this issue. We'll you posted once fixed.

**Comment by kingonly** [comment]
Fixed in https://github.com/breez/breezmobile/commit/7625b06b355a8d4b206bb15a0afb0007b0245168
