### ISSUE TITLE
Back up screen freeze in iOS

### ISSUE THREAD

**Issue by Nackoo2000** [breez/breezmobile#1144]
There must be at least 2 backups in Apple Cloud
1. Install/reinstall Breez mobile
2. Click Restore from backup
3. Select Apple iCloud
4. Click OK
5. Select the backup from which to restore (Back up with a key)
6. Click OK
7. Go back to the first screen 
8. Click restore from Back up 
9. Select Apple iCloud
10. Click OK
11. Select a backup

Result: Buttons "OK" and "Cancel" do not work

![image](https://github.com/breez/breezmobile/assets/127208515/f9d04181-32b8-4174-b070-0a768486ed54)

**Comment by kingonly** [comment]
Won't fix for now.
