### ISSUE TITLE
Guiding text inaccurate about max amount for lightning adsress (iOS)

### ISSUE THREAD

**Issue by Nackoo2000** [breez/breezmobile#1147]
1. Send > Paste Invoice or ID
2. Enter manually a lightning address
3. The screen appears with 11M sats limit

![image](https://github.com/breez/breezmobile/assets/127208515/e406e443-ad99-4c78-a8b0-31b3de03a701)

**Comment by kingonly** [comment]
That's from the provider, we don't want to change that now, it's ok.
