### ISSUE TITLE
Bad UI for expired invoice

### ISSUE THREAD

**Issue by Nackoo2000** [breez/breezmobile#1149]
1. Create a lightning invoice
2. Leave the invoice open for more than 1 hour
3. Try to pay the invoice

![image](https://github.com/breez/breezmobile/assets/127208515/061c55eb-ad37-40aa-a079-1e8f97053364)

@kingonly what should be the text for the use case?
Suggestion: "This invoice expired. Please create a new one to make the payment"

**Comment by kingonly** [comment]
Not a regression though, so no need to fix itnow
