### ISSUE TITLE
Iphone 5 users can't see or copy the preimage

### ISSUE THREAD

**Issue by grunch** [breez/breezmobile#115]
I'm testing breez and there's something that's a problem on iPhone 5, on payment detail modal the last item, the preimage can't be visualized cause there's no more space on the screen.

I suggest to make it scroll down to let the user copy or share the preimage, it's very important to have access to it, in some sites you need the proof of payment.

![IMG_0021](https://user-images.githubusercontent.com/228364/60025196-847f9200-966f-11e9-9f64-db36095fc987.jpg)

**Comment by kingonly** [comment]
Thanks for your report. We'll take a look at this issue...

**Comment by kingonly** [comment]
I'll close when it's published
