### ISSUE TITLE
History / Activity: Timestamp says ~1 day ago although its almost 2 days

### ISSUE THREAD

**Issue by myxmaster** [breez/breezmobile#1151]
When a payment is almost 2 days in the past, it still says ~1 day ago. I think that is confusing.

I personally would like
either: always the date
or: "today" if its on the same day, otherwise date.

**Comment by kingonly** [comment]
I see your point, but almost 2 days, isn't 2 days...
This is the algorithm the library (and many other apps) use.

We had dates in the past, but we think this works better for most users.
Your feedback is noted, but we won't fix for now.

**Comment by myxmaster** [comment]
Ok I see. Maybe it is a translation issue too, but not sure. I refer to the German translation of Breez.

For me, ~ does not mean "almost" but "about". And when it really is e.g. 1 day and 20 hours, I would definitely say "about 2 days", rather than "about 1 day".
