### ISSUE TITLE
small glitch after closing Node ID dropdown

### ISSUE THREAD

**Issue by MarnixCroes** [breez/breezmobile#1153]
https://github.com/breez/breezmobile/assets/93143998/cf188f1d-fb20-4ad2-9eff-9828207ddc93

cannot always repro

0.15-beta(1681054500)

Graphene OS

**Comment by kingonly** [comment]
This is most likely an os/flutter issue.
I never saw this or had been reported on this issue, so I don't think we need to actively look into it. Will probably resolve itself by flutter upgrades.
