### ISSUE TITLE
create issue template(s)

### ISSUE THREAD

**Issue by MarnixCroes** [breez/breezmobile#1154]
@kingonly ACK?
if yes, I can do it

**Comment by kingonly** [comment]
Go for it!

**Comment by MarnixCroes** [comment]
@kingonly 
- a "simple" .md or an .yml?
- only a _Bug Report_ or also _Feature Request_ or anything else?

**Comment by kingonly** [comment]
Only bug reports please 🙏
A simple md will do I think.
Thanks so much!
