### ISSUE TITLE
Incorrect Supported Android Version

### ISSUE THREAD

**Issue by PeteClubSeven** [breez/breezmobile#1156]
### General Description

I updated my fork and noticed that the minimum SDK version supported is now 28 (Android 9+). It seems the change came from a recent update to the Breez fork of md5_file_checksum https://github.com/breez/md5_file_checksum/commit/5c1578c1da172d5f1bf8ce5e8ac7b641794949b6. The breezmobile README.md states Android 7+ 64-bit as being supported. I wanted to know which is correct? I didn't want to submit a pull request to fix the README.md if it turned out that it wasn't your intention to stop supporting Android 7 and 8.

**Comment by PeteClubSeven** [comment]
Never mind I see it was intended based on this PR: https://github.com/breez/breezmobile/pull/1140

**Comment by kingonly** [comment]
Idk. We need to review this. The current published version support 7.

**Comment by PeteClubSeven** [comment]
> Idk. We need to review this. The current published version support 7.

I was quite surprised to see my old trusty Android 8.1 dev phone be incompatible but if it is intended for Android 9  to become the new minimum then I made a PR to change it: https://github.com/breez/breezmobile/pull/1157

**Comment by kingonly** [comment]
I didn't approve the change though. We need to revisit this.

**Comment by PeteClubSeven** [comment]
I'll leave it in your hands, sounds like some internal discussion might be needed :+1:

**Comment by kingonly** [comment]
We will revert this change

**Comment by PeteClubSeven** [comment]
> We will revert this change

Alright I'll close my pull request and I guess you can close this issue once the change is reverted, thanks! :+1:

**Comment by kingonly** [comment]
Yes, will do

**Comment by PeteClubSeven** [comment]
I can confirm that it now works again on my Moto G5 Plus (Android 8.1), thanks a lot that makes development easier for me.
