### ISSUE TITLE
[UX] LNURL-withdraw, make min and max amount clickable

### ISSUE THREAD

**Issue by MarnixCroes** [breez/breezmobile#1162]
### General Description

prior to https://github.com/breez/breezmobile/pull/1060 the user only had to scan/paste the LNURL-withdraw and then click `redeem`.
Now the user has to manually enter an amount.
Would be nice if the min and max amount are clickable, so when the user clicks it, the amount field gets filled in.

![image](https://github.com/breez/breezmobile/assets/93143998/466bf235-1c9d-4a87-8338-00cae3794003)

clicking 5 would enter 5, clicking 20 would enter 20.

Now it requires many clicks...

**Comment by kingonly** [comment]
That's a good suggestion

**Comment by RubenWaterman** [comment]
At Satsback.com, we recommend Breez and Phoenix as the go-to wallets for new users.

- We heavily use LNURL-withdraw for payouts.
- We "miss" the older flow where the max amount is pre-filled automatically.
- Currently, we don't expect users to input the right amount manually.
- As a result, when the withdraw is settled, our Satsback interface shows the full amount to be settled, even if a user has only claimed half in the Breez wallet.

Potential Solutions:

- I just discovered we can address this issue by setting the min and max amounts to be the same. We plan to implement this.
- It would also help if the min and max amounts were clickable, as suggested by @MarnixCroes.
- Lastly, would it be an idea if only a max. amount is given, this amount still gets prefilled. Perhaps this conflicts with https://github.com/breez/breezmobile/issues/1057 and https://github.com/breez/breezmobile/pull/1060 but I'm curious as to why anyone would *not* want to claim the full amount to be withdrawn? (if no min. value is given).

Would like to hear your thoughts @kingonly

**Comment by kingonly** [comment]
In your case you should should set the min max to the same value, why offer a lower minimum if you're not interested in it? No min means semantically means there's no minimum.
