### ISSUE TITLE
Bad UI for Breez offline

### ISSUE THREAD

**Issue by Nackoo2000** [breez/breezmobile#1176]
1. Turn off WiFi and Mobile data on the device.
2. Click Receive>Receive via Invoice
3. Enter the amount of sats
4. Click Create

![image](https://github.com/breez/breezmobile/assets/127208515/a0777f23-0156-47b0-809a-91c4cfab23ef)

NOTE: The flush bar that says Breez is offline appears properly
@kingonly please advise on the proper outcome for this one.

**Comment by kingonly** [comment]
Is this a regression?

**Comment by Nackoo2000** [comment]
Yes here is how it is handled currently.

https://github.com/breez/breezmobile/assets/127208515/3c2ac29e-4cf2-40cb-9226-352846fcb93f

**Comment by kingonly** [comment]
I don't think it's a regression (it depends on the timing when the network disconnects) or something we should fix right now.  @roeierez please verify and close if you agree.

**Comment by Nackoo2000** [comment]
Are these the messages that should appear here?

![image](https://github.com/breez/breezmobile/assets/127208515/9a186e50-f7d2-49fd-9b87-9e459c483b19)

**Comment by kingonly** [comment]
I don't want to deal with this.
