### ISSUE TITLE
ios anytime dropdown menu icon is wrong

### ISSUE THREAD

**Issue by ubbabeck** [breez/breezmobile#1184]
It shows as "?" but should be "..."

![ios_menu_button](https://github.com/breez/breezmobile/assets/36157890/27f7096e-f6a6-44a5-a1c9-e128285ab625)

**Comment by erdemyerebasmaz** [comment]
Could be related to removal of `icon_map.dart`
https://github.com/breez/breezmobile/pull/1175/files#diff-97883a9cafebb60c739fbe3eb991b8e382b58e2cdc609849358b3f22a054e69a

**Comment by erdemyerebasmaz** [comment]
@ubbabeck It was because `cupertino_icons` was removed... https://github.com/breez/anytime_podcast_player/pull/47/files
Great catch!
