### ISSUE TITLE
Certificate error for LNURLw from LNbits instances

### ISSUE THREAD

**Issue by arbadacarbaYK** [breez/breezmobile#1200]
### General Description

Generated a lnurlw (with nfc-brrr.com if that matters)
wrote to nfc-tag
tapping to phone this pops up (Breez)

However in BlueWallet it worked and the lnurlw also gets paid out to another lnbits wallet. They dont seem to care :P

### How To Reproduce?

1. Install lnurlw extension on an lnbits instance (tried saas.lnbits.com, lnbits.plebtag.com as well as legend.lnbits.com)
2. Click on generate lnurlw
3. write to nfc tag by opening the link and clicking on the nfc-symbol and tapping a card to chrome on android
4. See ERROR

### Screenshots

![photo_2023-08-27_21-25-52](https://github.com/breez/breezmobile/assets/63317640/71d185a2-6400-4524-9d25-fb63635b69a9)
![photo_2023-08-27_21-25-48](https://github.com/breez/breezmobile/assets/63317640/85a7396c-e1c5-417f-aebd-73995d882d94)

### Logs
-

### Operating System

Android on Huawai and iPhone

### Breez Version
latest from stores

**Comment by JssDWt** [comment]
Note that these two screenshots are from different servers. So the same problem on different servers.

**Comment by JssDWt** [comment]
I'm getting this myself for the lnbits server
![image](https://github.com/breez/breezmobile/assets/15966593/feb021df-cbcf-40de-8fdb-e4d83d25b2e1)

The date in the user's error corresponds with the expiration of the previous let's encrypt root CA. https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

**Comment by yaslama** [comment]
> I'm getting this myself for the lnbits server ![image](https://user-images.githubusercontent.com/15966593/263554060-feb021df-cbcf-40de-8fdb-e4d83d25b2e1.png)
> 
> The date in the user's error corresponds with the expiration of the previous let's encrypt root CA. https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

@JssDWt  Please note that your error is not a certificate error but a dns resolving error. Can you please check your connection? Can you open the url using chrome in the same device?

**Comment by yaslama** [comment]
> ### General Description
> 
> Generated a lnurlw (with nfc-brrr.com if that matters) wrote to nfc-tag tapping to phone this pops up (Breez)
> 
> However in BlueWallet it worked and the lnurlw also gets paid out to another lnbits wallet. They dont seem to care :P
> ### How To Reproduce?
> 
>     1. Install lnurlw extension on an lnbits instance (tried saas.lnbits.com, lnbits.plebtag.com as well as legend.lnbits.com)
> 
>     2. Click on generate lnurlw
> 
>     3. write to nfc tag by opening the link and clicking on the nfc-symbol and tapping a card to chrome on android
> 
>     4. See ERROR
> 
> 
> ### Screenshots
> 
> ![photo_2023-08-27_21-25-52](https://user-images.githubusercontent.com/63317640/263549867-71d185a2-6400-4524-9d25-fb63635b69a9.jpg) ![photo_2023-08-27_21-25-48](https://user-images.githubusercontent.com/63317640/263549870-85a7396c-e1c5-417f-aebd-73995d882d94.jpg)
> ### Logs
> 
> 
> ### What type of machine are you observing the error on?
> ### Operating System
> 
> Android on Huawai and iPhone
> ### Breez Version
> 
> latest from stores

Do you have an error when you open https://legend.lnbits.com using chrome from your device?
If you see an error in chrome, you can install and open firefox then open this link using firefox https://letsencrypt.org/certs/isrgrootx1.der, save the file and open it with the "Certificate Installer" to install the root for letsencrypt.

**Comment by arbadacarbaYK** [comment]
no theres no error but will do. why would that only be relevant for Breez but not other apps ? :P

**Comment by JssDWt** [comment]
It must have been my internet connection, because indeed the links are working now for me.

This rules out issues with the app in general and it's @arbadacarbaYK's phone that doesn't appear to have the let's encrypt root CA installed.

@arbadacarbaYK It could be that other apps don't check the SSL connection perhaps.

**Comment by arbadacarbaYK** [comment]
![IMG_5527](https://github.com/breez/breezmobile/assets/63317640/df84e0b2-cbde-4a77-b8e8-6c5f56953dc1)

bit weird that its  nowhere a problem. If I generate an invoice it doesn’t sync also. Pls stop caring for certs on old phones 😅🤣

**Comment by yaslama** [comment]
> ![IMG_5527](https://user-images.githubusercontent.com/63317640/263635865-df84e0b2-cbde-4a77-b8e8-6c5f56953dc1.jpeg)
> 
> bit weird that its nowhere a problem. If I generate an invoice it doesn’t sync also. Pls stop caring for certs on old phones 😅🤣

This error is not related to the certificate. It's a name resolving (dns) error. Please check that your connection is ok and retry.

**Comment by JssDWt** [comment]
> This error is not related to the certificate. It's a name resolving (dns) error. Please check that your connection is ok and retry.

I asked her to share this error here too, because it's the same error I got yesterday.

**Comment by arbadacarbaYK** [comment]
Close this PR with the request to ignore old certificates 🤣

**Comment by JssDWt** [comment]
So the problem is the Android version. Android versions >=7.1.1 will trust the new let's encrypt certificates, Android versions below that will not by default.

But let's encrypt has a hack for older devices, because the new let's encrypt root certificate is signed by DST Root CA X3, (which expires 30-9-2021), older phones should still trust these new let's encrypt certificates.
Apparently though, this is not the case for this user's phone, in the breez app. Note that this also makes the app fail to sync, because we sync over http.

I think we're giving up, but posting the final insights here.
