### ISSUE TITLE
Broken UI

### ISSUE THREAD

**Issue by iBobik** [breez/breezmobile#1210]
### General Description

Last update broke multiple things. UI is always broken. LN transactions fails on No route. Sometimes Breez offline error. And on the top it switched me to the Czech translation (correctly), but with a lot of incorrect strings (better to rever this "Google Translate" nonsence than welcoming new users by this).

### How To Reproduce?

1. Get new update
2. Profit!

### Screenshots

https://github.com/breez/breezmobile/assets/614232/a46a2068-abcc-4777-9052-5c72112480ad

### Logs

I prefer to share it privately, write me e-mail from @breez.technology domain if you wish.

### What type of machine are you observing the error on?
iPhone

### Operating System

iOS  17.0 and the last Beta (maybe Beta 3?).

### Breez Version

"0.16.4-beta.rc1 commit=" from App Store

**Comment by kingonly** [comment]
@erdemyerebasmaz  let's focus on the broken UI first. 
@iBobik we added Slovak translation, but let's open a separate bug on it. Regarding the no route, it's unlikely related to the new release. Let's handle the bugs first.

**Comment by kingonly** [comment]
@iBobik does it happen in the latest update?

**Comment by iBobik** [comment]
All fixed, thank you!
