### ISSUE TITLE
Switch to https://api.boltz.exchange/

### ISSUE THREAD

**Issue by kingonly** [breez/breezmobile#1217]
Should be the same as https://boltz.exchange/api but w/o Cloudflare

**Comment by yaslama** [comment]
Fixed by the following commits:
https://github.com/breez/boltz/commit/f934a24010d463e64cb40e4bc157edba4393f86b
https://github.com/breez/breez-sdk/commit/a441154a106eb7c4dd70a49453bd73c98f94edaa

**Comment by JssDWt** [comment]
Needs a version bump of boltz in breez library still.
