### ISSUE TITLE
Backup prompt at `Receive via BTC address` dialog

### ISSUE THREAD

**Issue by MarnixCroes** [breez/breezmobile#1221]
### General Description

![image](https://github.com/breez/breezmobile/assets/93143998/2561a0ed-ce6f-4f61-a488-3b5c0ce8e159)

### How To Reproduce?

I was able to repro with this, but not 100% of the time
I've been able to repro 4 times
to repro again, I have to restart Breez, iirc

1. At homescreen, click on Backup warning triangle
2. Click on `Don't prompt again`
3. Click on `Later`
4. Click on Back up triangle again
5. click on later
6. Go to backup triangle
7. disable `Don't prompt again`
8. click on later

10. Go to Receive via BTC address
11. see error

Now at Receive via BTC address, I don't get an address anymore and I can't repro since then.

### What type of machine are you observing the error on?

Pixel mobile

### Operating System

Graphene OS

### Breez Version

latest,
versionCode 1695315644

**Comment by MarnixCroes** [comment]
I'm also able to repro without all the steps/touching Backup prompt 😅

**Comment by kingonly** [comment]
@MarnixCroes this isn't bug. The backup prompt can be displayed in this context.

**Comment by MarnixCroes** [comment]
ok. it feels weird though.
It's ok if it shows up at a different dialog like when some funds are received.
For me the issue was that it shows up sometimes randomly.

When user goes to `Receive via BTC address` dialog, and then is typing over the address or tries to scan it and all of a sudden the backup prompt shows up. It's bad UX and feels buggy imo.

(this never happened before, only since recent update?)

**Comment by kingonly** [comment]
In most cases you should already have a backup though. Honestly, I think it's ok. Nothing changed in the UX.
We'll keep monitoring and see if others complain.
