### ISSUE TITLE
[BUG] unable to scan same invoice for a second time

### ISSUE THREAD

**Issue by MarnixCroes** [breez/breezmobile#1231]
### How To Reproduce?

1. scan an invoice
2. See `You are requested to pay:` dialog
3. click CANCEL
4. try to scan the same invoice again
5. see ERROR, cannot scan the invoice again. Only after restarting Breez

### Operating System

Graphene OS

### Breez Version

latest,
1695315644

**Comment by JssDWt** [comment]
A similar, but maybe unrelated flow is:
- Scan invoice
- pay
- payment fails
- Try to scan invoice again

In that case the QR scanner doesn't pick up on the invoice if it's the same.
