### ISSUE TITLE
Persist fiat amounts with POS invoices

### ISSUE THREAD

**Issue by JssDWt** [breez/breezmobile#1233]
A merchant wants to price their goods in fiat, but receives lightning payments. For these people it's important to have a record of the amounts received in fiat, rather than sats, for their administration. 

A solution could be to persist the fiat amount with the invoice. That way we would be able to show the charged fiat amount as well.

**Comment by kingonly** [comment]
We have that in the POS Transactions screen and it's aldo included in the POS reports
