### ISSUE TITLE
Translation: Spanish language translation is incorrect

### ISSUE THREAD

**Issue by christopherowenowens** [breez/breezmobile#1246]
### General Description

Spanish language translation is incorrect. "Ahorrar" -> "Guardar". Ahorrar means to save money, discount; guardar means to save settings.

I am not a native speaker, so there may be other translations that are incorrect. For example: "respaldar" seems very unusual for "backup", usually respaldar means to "back" something as in support it; you usually hear "copiar de seguridad" or similar.

### How To Reproduce?

1. Open top left folder from home screen
2. Click on profile picture 
3. Options are "Cancelar" or "Ahorrar". Should be Guardar.

### Screenshots
N/A

### Logs
N/A

### What type of machine are you observing the error on?
Mobile Phone - Android

### Operating System
Android 11

### Breez Version
0.16.4-beta; 2023-09-21

**Comment by kingonly** [comment]
Thanks for the report @christopherowenowens!
Feel free to submit a PR here: https://github.com/breez/Breez-Translations

**Comment by christopherowenowens** [comment]
Closing this and moving to translations
