### ISSUE TITLE
Breez node not rebalanced?

### ISSUE THREAD

**Issue by Talkless** [breez/breezmobile#1268]
I've failed to send payment to some Binans user via LN. It was about 25k stats, though sending in two steps 10k + 15k worked.

Now it even fails to pay Joltfun ~9k sats...

Wallet currently have ~220k sats.

I did not open any manual challenge or similar.

Is everything "fine" with Breez node?

I've clicked "Yes" to "Sendng fialed payment detail.s to Breez..." couple of times, you should see the issues.

**Comment by kingonly** [comment]
This is a typical liquidity issue. Contact us via email to contact@breez.technology and we'll follow up.

**Comment by Talkless** [comment]
@kingonly I've sent email from vincas@.....net with some more info, but got no reply yet. Maybe got into spam folder?

Thanks.

**Comment by kingonly** [comment]
I'll check with support
