### ISSUE TITLE
outgoing tx pending for 40+ min

### ISSUE THREAD

**Issue by MarnixCroes** [breez/breezmobile#1274]
### General Description

I sent a tx and it was pending for 40+ minutes, afaik the time-out on outgoing payments is max 2 min

### How To Reproduce?

1. I tried to send to a Phoenix user
2. that didn't work, payment kept pending
3. then I scanned a LNURL (while that payment was still pending)
4. the original payment kept being pending for more than 40 minutes

I don't remember exactly how it fixed itself, just after more time or after restart

### Screenshots

![image](https://github.com/breez/breezmobile/assets/93143998/a42705d0-2a20-4e1e-b819-9ba0f2391af9)

### Logs

can send logs if wanted

### Operating System

Graphene

### Breez Version

latest, 1697539298

**Comment by kingonly** [comment]
This can happen if a node in the route doesn't forward the htlc or if the payee node doesn't settle the payment. That's the reason every lightning payment has an expiration time as well.

**Comment by MarnixCroes** [comment]
ok, thought it might be a bug if you send when still having a pending payment
