### ISSUE TITLE
Wrong message for pending closed channel 

### ISSUE THREAD

**Issue by Nackoo2000** [breez/breezmobile#1278]
The numbers are wrong in the dialog message and the $ sign has to be removed.
![321561885-2eb2f429-cb93-43df-93a9-4de930f86dd5](https://github.com/breez/breezmobile/assets/127208515/b97ff1fb-5af9-409e-872f-4f56d890e148)

**Comment by Nackoo2000** [comment]
I am not sure if this was solved so I can test for it.

**Comment by erdemyerebasmaz** [comment]
@Nackoo2000 It's not solved and was not part of this release but I'll take a look.

**Comment by erdemyerebasmaz** [comment]
@Nackoo2000 The numbers aren't wrong per se, but your account's tip height appears to be 0 when this dialog was opened.

(blockheight - account's tipHeight) * 10 (_In theory there is one block per 10 minutes_) / 60 which gives us
(793830 - 0)*10/60 = 132305 hours

Could you try recreating this with latest build and share logs? We'll investigate why account response returned tip height as 0.

**Comment by Nackoo2000** [comment]
When I reported this it was an old node that was in this state it was not during testing.
Not sure how exactly to recreate this case please give me a step-by-step.

**Comment by erdemyerebasmaz** [comment]
> When I reported this it was an old node that was in this state it was not during testing. Not sure how exactly to recreate this case please give me a step-by-step.

You can use the cooperative close channels feature, the pending close transaction should appear on tx list

**Comment by Nackoo2000** [comment]
The whole section is skipped so I think this is good and we can close the issue - your call.
![image](https://github.com/breez/breezmobile/assets/127208515/6f5ac0e1-0099-44a6-9c46-4abd6dc08583)

**Comment by Nackoo2000** [comment]
Now I remember that this was not my issue but it came from a support case but I will be on the lookout for it.
