### ISSUE TITLE
Podcasting player is "blinking"

### ISSUE THREAD

**Issue by Nackoo2000** [breez/breezmobile#1281]
When I play a podcast and want to skip 30 sec or go back 10 sec the play button is "blinking".

https://github.com/breez/breezmobile/assets/127208515/340ea998-4778-4707-8833-8c2e5c2f88ae

**Comment by erdemyerebasmaz** [comment]
Marked as a non-issue. The "blinking" is the animation for downloading the data on new timestamp.

Anytime does not have caching for podcast data on the version we're currently using.

**Comment by erdemyerebasmaz** [comment]
Applied the solution on video.
