### ISSUE TITLE
Auto paste doesn't work

### ISSUE THREAD

**Issue by Nackoo2000** [breez/breezmobile#1286]
When I copy an invoice in the clipboard Breez does not paste it automatically after opening.
I have to paste it manually in Send > Send via ....
The same is for a BTC Adress or LNURL

**Comment by erdemyerebasmaz** [comment]
Is this on iOS or Android?
Could you add logs?

**Comment by Nackoo2000** [comment]
For iOS and Android the behavior is the same and consistent you can easily reproduce it.

1. Copy invoice from WoS
2. Open BreezM
3. Nothing happens
