### ISSUE TITLE
Closed Channel can't recover funds

### ISSUE THREAD

**Issue by oGobby** [breez/breezmobile#1298]
### General Description
Trying to recover my funds, I forced a channel when trying to troubleshoot for a few hours, now no channels are available at all. I tried many things but to no avail please help me
{
    "totalBalance": "51517",
    "confirmedBalance": "0",
    "unconfirmedBalance": "51517",
    "lockedBalance": "0",
    "reservedBalanceAnchorChan": "0",
    "accountBalance": {
        "default": {
            "confirmedBalance": "0",
            "unconfirmedBalance": "51517"
        },
        "imported": {
            "confirmedBalance": "0",
            "unconfirmedBalance": "0"
        }
    }
}

Balance shows unconfirmed but the blockchain has already been through 64 confirmations
https://blockstream.info/tx/680e90f09bfe466422de9b197674abb28a3a1270ff32ff47b5025a8d03e54b40

Insert Your Logs Here
[breez.logs.zip](https://github.com/user-attachments/files/15687554/breez.logs.zip)

### What type of machine are you observing the error on?
Pixel 6

### Operating System

Android 14 -> 0.17.5-beta

### Breez Version

Google Play Store

**Comment by kingonly** [comment]
Please email us contact@breez.technology 
This isn't a medium for support...
