### ISSUE TITLE
Boosting a podcast episode - discrepency for the ammount sent

### ISSUE THREAD

**Issue by Nackoo2000** [breez/breezmobile#1313]
When I boosted an episode 50 sats (the minimum allowed) the outgoing payment was for 48 sats as seen in the balance screen.
![image](https://github.com/user-attachments/assets/d3d78c72-3a91-4a92-a261-a7fd41abfcab)

[breez.logs (43).zip](https://github.com/user-attachments/files/17294443/breez.logs.43.zip)

**Comment by kingonly** [comment]
Not a regression
