### ISSUE TITLE
Feature request: show fiat amount in confirmation dialog

### ISSUE THREAD

**Issue by Talkless** [breez/breezmobile#1315]
### General Description

It would be useful to have "fiat confirmation" amount shown together with sats in "Approve" dialog.

### How To Reproduce?

Try paying to somewhere.
"Approve" popup shows only sats, no fiat amount available as confirmation.

### Screenshots

![amount](https://github.com/user-attachments/assets/4a812b21-156b-42e5-9166-ced165e44657)

### Breez Version

0.17.bugfixes.3

**Comment by kingonly** [comment]
You can long press the sats amount and you'll see the fiat value

**Comment by Talkless** [comment]
That's apparently non-intuitive enough then.

Wallet balance is shown with both sats and fiat at the same time. Here could be the same.

You could make a poll in twitter via `@Breez_Tech`: "Did you know that long-press on sats in payment confirmation dialog switches display to fiat? Yes/No?" I wonder what percentage of users discovered that by themselves... :)

**Comment by kingonly** [comment]
No, it's not obvious, we're aware.

**Comment by Talkless** [comment]
So maybe we should better rename this issue and keep this open?

**Comment by kingonly** [comment]
It's by design for now. We might change it later, but it's not currently a bug.
