### ISSUE TITLE
Extreme power consumption of the podcast player

### ISSUE THREAD

**Issue by iBobik** [breez/breezmobile#1317]
### General Description

In background audio the podcast player consumer so much energy my phone burns me in the pocket.

Here are comparison where 3 different apps playing background audio consumer similar energy, but for very different time:
<img src="https://github.com/user-attachments/assets/34bd7f27-6cd2-4ff6-a9fa-50ab2469f5ee" alt="power amount" width="300" />
<img src="https://github.com/user-attachments/assets/08633739-4a57-48dc-a837-cced1b84efc5" alt="time played" width="300" />

### What type of machine are you observing the error on?
Phone

### Operating System

iOS 18

### Breez Version

1.1.19

**Comment by kingonly** [comment]
Are you streaming sats?

**Comment by iBobik** [comment]
Yes. If it makes LN transaction every second then it makes sense for me to
require pocket nuclear reactor.

**Comment by kingonly** [comment]
Yep. We can't optimize the lnd CPU consumption for now. Set the sats/min to 0 as a workaround.

**Comment by iBobik** [comment]
But you can decrease interval when the transaction are send. E.g. only when playing is stopped. Or any other smaller interval.
