### ISSUE TITLE
french decimal comma refused when creating an invoice

### ISSUE THREAD

**Issue by gotcha** [breez/breezmobile#142]
Under IOS 12 in French.

While creating an invoice, when trying to input the BTC amount, the numeric keypad includes the comma as a decimal sign (instead of the dot) which gets refused by the app.

IOW, impossible to create an invoice.

FIX: the validation of amount should be localized.

**Comment by kingonly** [comment]
Thanks for your report, we'll take a look...

**Comment by gotcha** [comment]
If there was some basic doc how to setup a dev environment on Mac, I'd be happy to help on both expanding that doc and trying to fix this bug.

**Comment by kingonly** [comment]
I'll get one of devs to assist you. Thank you so much!

**Comment by gotcha** [comment]
@roeierez Thanks
@kingonly Should I make a separate issue for doc about dev environment under MacOS ?

**Comment by kingonly** [comment]
Please do
