### ISSUE TITLE
When camera has not been authorized, there is no message explaining why tapping inovice pay fails

### ISSUE THREAD

**Issue by gotcha** [breez/breezmobile#143]
under IOS 12

when access to camera has not been authorized, tapping invoice pay opens a new window that closes immediately.

iow, paying an invoice is impossible.

Fix 1: give a chance to paste an invoice and fail only if user tries to scan

Fix 2: there should be a message recalling to authorize access to camera

Fix 3: Message to recall and scan button enabled only when access is authorized

**Comment by kingonly** [comment]
Nice catch!

**Comment by kingonly** [comment]
Paying Invoice should still be possible if you copy the Invoice and open Breez (Breez takes a look at the clipboard). Only if you cancel the first Invoice, then there's an issue. Anyway, we'll get it fixed.
