### ISSUE TITLE
Feature: configure unit BTC or sats

### ISSUE THREAD

**Issue by gotcha** [breez/breezmobile#144]
Would be great if it was possible to choose unit for Balance and invoices:
BTC or sats

Most people would be easier with sats imo as it is pretty easy to make mistakes with so many decimal zeros.

Further, it would be an easy fix for #142

**Comment by kingonly** [comment]
Currently, you can change the unit globally by tapping the unit in the home screen. Further improvement would be to provide this option in BTC input fields.

**Comment by gotcha** [comment]
Well, I think a global choice is fine but there should be a way to discover it. IOW, could it be surfaced in IOS configuration as it is a natural goto when looking for the choice ?

**Comment by gotcha** [comment]
BTW, this makes #142 much less urgent to fix.

**Comment by kingonly** [comment]
Default unit is Sat. We will add UI to better expose this functionality.

**Comment by gotcha** [comment]
Which makes a lot of sense.

What I find interesting is that I managed to turn to BTC without doing it consciously. IOW being able to change it just via a single tap is maybe an issue.
