### ISSUE TITLE
Added onchain funds, "failed to add funds", confusing UX

### ISSUE THREAD

**Issue by mariodian** [breez/breezmobile#150]
Hi, so this is my experience (and possible bugs?) with adding funds to Breez.

I sent less than 900k satoshi to the bech32 deposit address generated by the wallet. The transaction got confirmed quickly but I got the following error:

> Failed to add funds: rpc error: code = Unknown
> desc = Error in payment response: unable to find a path to destination

When checking the dev console, I didn't see anything under `walletbalance` nor `channelbalance`, there was no open channel on my side, nor a pending one. The funds seemed gone. 

However, `listchaintxns` showed me the confirmed transaction and `listchannels` showed me a channel with a **remote** balance (for a while). Then it showed up under `closedchannels` (?) as `REMOTE_FORCE_CLOSE`.

15 minutes later the error message was gone and it was replaced by one saying that a secure channel is opening. 

Then `pendingchannels` started showing the new channel with remote balance and it was eventually open and 90% of funds were transferred to the local side of the channel.

Not sure if there is a bug in the whole funding process but regardless, I think the UX isn't very clear about what's going on. I understand why there's no balance showing in the UI while the channel is opening, but I think there should at least be a pending transaction displayed in the tx list so the user has at least a slight idea that "something is happening". For a moment I thought my funds were gone especially with this scary looking error message:

![IMG_0588](https://user-images.githubusercontent.com/3636406/63073045-79532f00-bf59-11e9-9587-7620857228d7.png)

**Comment by kingonly** [comment]
We're going to add a link to tx info while the channel is being opened.

**Comment by kingonly** [comment]
We've added a link to the funding tx in the latest release
