### ISSUE TITLE
Suggestion: developers option on Breez menu should be hidden as standard

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#153]
Hi,

Suggestion: developes option on Breez menu should be hidden as standard and only appear if the user tap seven times on any part of menu.
Something like what happens on Android OS to activate developers option.

No reason to have developers option on Breez for newbie users. I suggested Breez to a friend and he asked me a lot of things about it.

**Comment by brmdbr** [comment]
I think users will know that "developer" options are not for them.
