### ISSUE TITLE
Is there a way to create a new backup?

### ISSUE THREAD

**Issue by brmdbr** [breez/breezmobile#163]
So I cant find the backup option in the wallet, I guess its not there because I've already created it. I'd like to create a new one but there is no option it seems. Am I doing something wrong or is there no option for it?

**Comment by kingonly** [comment]
You need to grant permission for Google Drive backup once, then Breez performs backups automatically after payments or after generating add funds addresses.
Last backup time is displayed in the Developers screen.
You can revoke Breez permissions here: https://myaccount.google.com/permissions
That will trigger re-authorization.

**Comment by brmdbr** [comment]
Awesome, thanks!
