### ISSUE TITLE
Suggestion: have spaces between numbers

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#170]
Hi,

When inserting an amount on Sat amount field, should have spaces like how appear on receive up to. See the image:

![photo5159248921254537267](https://user-images.githubusercontent.com/1178856/64478053-fcdaf700-d178-11e9-9af5-17d948d7e831.jpg)

**Comment by bitcoinuser** [comment]
Same thing on dollars field:

![photo5159248921254537268](https://user-images.githubusercontent.com/1178856/64478068-36136700-d179-11e9-9a09-c162df27146c.jpg)

**Comment by bitcoinuser** [comment]
![photo5042286589438437433](https://user-images.githubusercontent.com/1178856/68089764-1f248480-fe4b-11e9-84c5-2f664406b4ca.jpg)

**Comment by kingonly** [comment]
Fixed in latest
