### ISSUE TITLE
Installation without play store

### ISSUE THREAD

**Issue by DarkWingMcQuack** [breez/breezmobile#178]
I am only using fdroid as a source of apps. Is there currently a way to install the wallet without building it by myself or using google play store? Is there a way to get the apk?

**Comment by seth586** [comment]
+1, I want to use breeze on my android device that I choose to not run google play services. (Think lineageOS, grapheneOS and other Android Open Source Project OSs).

It appears that I can install the apk, but the app never bootstraps / syncs.

Please remove the requirement to run google software! Thanks!

**Comment by AbelLykens** [comment]
Also see #413 .

**Comment by emanuelb** [comment]
Yes, they publish APKs in github releases: https://github.com/breez/breezmobile/releases
Just visit: https://github.com/breez/breezmobile/releases
click "Assets" and download the APK file.
