### ISSUE TITLE
The distance between numbers on PIN window is big, so if I type fast I always click on wrong number

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#183]
The distance between numbers on PIN window is big, so if I type fast I always click on wrong number.

On Green wallet I can type fast and most of time I click on correct numbers. See the difference between Green and Breez: (Obs. See number 2)

![photo4950013782634113052](https://user-images.githubusercontent.com/1178856/66142438-c8255880-e5db-11e9-9215-42507f4ea1f9.jpg)

![photo4950013782634113051](https://user-images.githubusercontent.com/1178856/66142497-dc695580-e5db-11e9-9ed9-d36bf3f4183f.jpg)

**Comment by bitcoinuser** [comment]
Breez could have bigger numbers on PIN.

**Comment by bitcoinuser** [comment]
A good example of how could look like:

![photo5012856374014617750](https://user-images.githubusercontent.com/1178856/67491153-d00c7180-f64a-11e9-8d3b-693aaeabd6e9.jpg)

**Comment by kingonly** [comment]
Nice example!
