### ISSUE TITLE
Bug: Android back button on Breez PIN window does nothing

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#186]
Bug: Android back button on Breez PIN window does nothing, but should close the app.

**Comment by bitcoinuser** [comment]
Maybe show a message like this:

![photo5014805412993673263](https://user-images.githubusercontent.com/1178856/67611337-591cc900-f76f-11e9-830d-fda30db17cc8.jpg)

**Comment by kingonly** [comment]
Fixed in latest
