### ISSUE TITLE
Suggestion of how Breez sidebar is opened

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#189]
Hi,

When you swipe the finger to open the breez sidebar, the user need to go to the beginning of left part of window. On telegram for example is different, works in almost any part of the window.
I prefer the telegram way because it's easier to open the menu using only one hand.

**Comment by kingonly** [comment]
This isn't clear... Could you please send a video?

**Comment by kingonly** [comment]
Breez menu can also be opened using dragging the toe from the bottom part, so I don't really understand the request....

**Comment by kingonly** [comment]
Fixed in the latest update
