### ISSUE TITLE
Minor UI problem on dark mode

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#194]
Font on top (battery, clock...) should be white color like Telegram app and not white. See the difference:

![photo4976591396744046628](https://user-images.githubusercontent.com/1178856/66706044-b55e0280-ed04-11e9-8787-3cc3a6a4f8d0.jpg)

![photo4976773761055434847](https://user-images.githubusercontent.com/1178856/66706057-df172980-ed04-11e9-9941-09f07229cf47.jpg)

**Comment by kingonly** [comment]
Fixed
