### ISSUE TITLE
Not clear for me that If I activate Pin and forget the Pin and lose phone, I lose the sats.

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#201]
Hi,

Not clear for me that If I activate Pin forget it and lose phone, I lose the sats. Because will be mandatory insert the Pin to restore the wallet, right?

If yes, I think the Breez UI/UX should warn the user about it.

**Comment by kingonly** [comment]
No, that's not the case. We used to have an option to encrypt the backup with the pin. Then, we added a warning. Now the only option is to encrypt with a seed phrase.

**Comment by bitcoinuser** [comment]
Hi,

Ok, but it's not clear for me what to do if I set a Pin and then forget it and can't access the app. I think it's just reinstall the app, right?

So my suggesion is add a "Forgot?" button on Pin window, that when clicked, show a message like: If you forgot the PIN, just reinstall the app and set new PIN.

![photo5041889536891791483](https://user-images.githubusercontent.com/1178856/68227238-1d38fd80-ffd2-11e9-9f88-d1513deb3dd3.jpg)
