### ISSUE TITLE
Backup hangs after selecting account

### ISSUE THREAD

**Issue by wintercooled** [breez/breezmobile#208]
This happened repeatedly with one of my Google accounts but another later worked.
![Screenshot_20191110-210122](https://user-images.githubusercontent.com/25693053/68703629-ec813700-0582-11ea-939f-caf715fdb2c2.jpg)

**Comment by wintercooled** [comment]
A bit more information:

It was sat like the screen above (rotating wait icon) for 30 seconds. I tried multiple times, quit app from memory and tried again etc. It hung via both the prompt from the wallet pop up to back up and then also later when I clicked the exclamation mark icon to back up.

The account I was trying to back up to was my personal (not family, business etc) account. I ended up using another personal account and that worked fine. When I tried to link the first account I had 0 sats balance, I may have received bitcoin into the wallet by the time I tried the second account - I forget. Not sure if that makes a difference.

Other apps have linked to my google account ok in the past.

It's not an issue for me personally as I just used the other account - just logging for your info.

**Comment by kingonly** [comment]
Thanks for the information!
It's interesting to see if the app is registered here under you personal account (the one that hanged): https://myaccount.google.com/permissions

If so, could you please try to revoke access from all your accounts (personal + second account), and try to backup to your personal account again?

**Comment by wintercooled** [comment]
It was linked to my second account. I revoked access and now in the Breez app I have no way to tell it to back up. The exclamation mark icon has gone and from the menu/advanced/security and backup it says it last synced with my second google account this morning nut there is no option to now change to use another backup account!

**Comment by wintercooled** [comment]
So currently it's not being backed up - which isn't ideal I assume ;-)

**Comment by kingonly** [comment]
Open Add Funds > Deposit to BTC Address to trigger a new backup.

**Comment by wintercooled** [comment]
Thanks. That prompted to back up. Main Google account still hangs.
Secondary worked. I'll stick with that.

**Comment by morenotos** [comment]
I'm having the a similar problem.
I'm trying to restore my wallet in android, I give breeze  access to google drive, it says restoring data, and then that it is initializing. Then sometimes it crashes and others it just tays that way (initializing).

**Comment by roeierez** [comment]
I would happily assist you restoring your data. As first step I need access to your logs.
Are you able to run the app send logs? If so you can send me to roeierez@gmail.com (via the dev screen).
If the app crashes on restart and you can't send logs, move to airplane mode and restart the app, it will probably won't crash and give you the options to send the logs.

**Comment by morenotos** [comment]
Thank you.
When I click on "share logs" in the dev screen the app does not do anything.
I am also using the app on iOS, having the same issue, and I sent the reports to Breez through apple.
Would you be able to find those reports?

**Comment by roeierez** [comment]
@morenotos  We would be able to find the reports if you send me your device model.
Regardless, apple report sometimes do not contain enough information so it is better to send the logs.
Would you mind try starting the app when your device is set to airplane mode? At this state you will see a dialog with an option to send the logs.

**Comment by morenotos** [comment]
This is what i did:
1. Installed the app.
2. Try to restore from backup.
3. Restoring...
4. Initializing...
5. App crashes.
6. Swich phone to airplane mode.
7. Open app
8. I just see the app's main screen (where the balance is supposed to be shown) with no data, just the background, no dialog with option to send logs.

If I go to the dev screen and click on share logs nothing happens.
If I try to restore from backup again (by going to dev screen and selecting show initial screen) the app crashes when trying to restore.

**Comment by roeierez** [comment]
@morenotos  I see, in order to properly understand the issue I built a special package for you to install.
This package attempts to show the error that keeps breez in "initializing..." mode and also allows you to send logs from the dev screen in such situation. 
I saw your crash report on testflight with this description: 
_"The app was initializing after trying to restore the wallet and the crashed."_

Please approve this is your report and I will send to the associated email a link to a private build for you to install.
Once installed, please do the following:
1. Open the app where it is in "initializing..." mode, wait for a flushbar with error to appear and please send me a screenshot with that error.
2. Try again to send the logs via the dev screen, hopefully with success this time.
Step by step we will get it fixed.

**Comment by kingonly** [comment]
No more reports on this issue
