### ISSUE TITLE
Android app crash on broadcast refund

### ISSUE THREAD

**Issue by RobertHosking** [breez/breezmobile#221]
I accidentally sent above the limit on chain to fund my wallet. Thankfully, there's a refund option. 

However, after I enter a refund address and set sat/byte and tap "broadcast", I get a popup spinner signaling the transaction is being sent then... BAM! The app crashes and I'm looking at my home screen. Happens every time. I even cleared app data and storage and recovered my wallet from backup... nothing. Still crashes every time and my refund is not sent.

Will my refund be safe until this bug is fixed?

**Comment by kingonly** [comment]
There's a regression in the product. Try sending the refund to a bech32 (segwit) address (the crash happens when sending the refund to a non-bech32 address).

**Comment by RobertHosking** [comment]
I see. I'll try sending to an Electrum first, then send from Electrum to my preferred destination.
