### ISSUE TITLE
Have an option to connect to testnet

### ISSUE THREAD

**Issue by fresheneesz** [breez/breezmobile#222]
I believe we need to make it easy for newcomers to bitcoin (and the LN) to play around on the testnet to get comfortable with how these things work without risking their money. Beyond that, *I* want to play around with breez on testnet to see how it works without risking *my* money. To that end, I'm requesting that there be an easy switch to switch the app onto the testnet so people can play around with the important use cases that would usually cost money. This would also do wonders for beta testing and bug finding.

**Comment by pfergi42** [comment]
I would 2nd this, specifically to test LNURL (withdraw) QR codes.

**Comment by kingonly** [comment]
Please see our comment on #557.
