### ISSUE TITLE
Crashing when attempting to get refund

### ISSUE THREAD

**Issue by dudeimstoked** [breez/breezmobile#227]
I sent a few too many sats to my address and am attempting a refund.
Everything goes smoothly until I click "broadcast" then the app crashes.
I tried on 2 different Android phones, both crash at the same point.

**Comment by kingonly** [comment]
Our apologies. This is a known issue and we'll be posting an update soon.
To avoid the crash, please use a bech32 (segwit) address.

**Comment by dudeimstoked** [comment]
Thanks!
