### ISSUE TITLE
Sync stuck at 70% after restore from backup

### ISSUE THREAD

**Issue by sadilek** [breez/breezmobile#229]
I switched phones and restored Breez from backup. The sync is stuck at 70%. First error from the log file:
```
[ERR] CHANNELDB: unable to open channeldb: source node does not exist
```
[Full lnd.log](https://github.com/breez/breezmobile/files/3919302/lnd.log)

**Comment by roeierez** [comment]
@sadilek Do you remember when was the time you last backed up your node?
We had once such issue where the node was backed up using an old version in of breez and trying to restore with a new version failed.
If possible, here is one work-around you can do:
1. Install the old version (the one that you used to backup your node) and restore from backup.
2. upgrade to the new version on test flight.
3. trigger backup and you should be good.

If it wasn't and old version or you don't remember which version was it LMK and we will help you restore in another way.

**Comment by sadilek** [comment]
I never explicitly triggered a backup. I actually don’t see an option for this, at least in the current state of the app. I have automatic updates enabled. But I opened the app irregularly. It might have been a few weeks since I opened it last.

I can try installing a few older versions and see if the restore works with one of them. Where do I find them? I see no builds on Github and Breez isn’t listed on apkmirror.com. 

Btw, instead of going backwards, I thought I might try going forward and build from HEAD. But I failed to do so because breezbackuprpc as referenced from breez/commands.go is nowhere to be found.

**Comment by roeierez** [comment]
@sadilek sorry just realized you are using android so testflight it irrelevant...
As we are still in beta and we are not yet maintaining a public release history, this is the reason you didn't find old builds for android.

Here is a link to the old version that you can try to restore with:
https://drive.google.com/open?id=1yocW3Qiw_wK889UUx3TrWmlsoS6T5Kvi

**Comment by sadilek** [comment]
The restore with that version worked. I then updated the app version from the Play Store, and it continued working. Thanks for the quick help!
