### ISSUE TITLE
Support LNURL-pay

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#236]
Hi,

Recently I saw an user on twitter who shared a page with a static lightning qrcode invoice (https://i.imgur.com/uGzrD1m.jpg). I see that BLW was the only walllet that I was able to pay this invoice, I think because they support LNURL-pay protocol. https://github.com/btcontract/lnurl-rfc/blob/master/examples.md

I really would like to see Breez support these kind of payments too.

Thanks.

**Comment by bitcoinuser** [comment]
In action: https://twitter.com/fiatjaf/status/1208105051857866754

**Comment by kingonly** [comment]
Fixed in latest
