### ISSUE TITLE
Bug: pin/fingerprint problem when fast minimize and restore on first open

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#237]
1- Open Breez, but before the fingerprint popup appear, minimize Breez. 
2- Restore Breez.

Result: when you restore breez, you can't insert pin and fingerprint popup doesn't appear too, even trying to click on fingerprint button on Breez.

**Comment by kingonly** [comment]
Seem like duplicate of #238

**Comment by bitcoinuser** [comment]
I don't think so, because on #238 I can click on the numbers. On this one I can click on numbers buttons. Just the fingerprint button doesn't work.

**Comment by bitcoinuser** [comment]
I think it's duplicate.
