### ISSUE TITLE
Bug: no fingerprint option when phone is locked and Breez is on foreground

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#238]
Hi,

1- Let breez opened (foreground) and lock the phone.
2- unlock the phone and will appear the Breez PIN

Result: I can unlock Breez using PIN but I can't unlock Breez with fingerprint. Even if I click on Breez fingerprint button, nothing happens.

Obs. On my Breez settings I set to lock automatically = immediate

**Comment by kingonly** [comment]
I don't reproduce... Maybe add a video?

**Comment by bitcoinuser** [comment]
Video uploaded here.
[t_video5186294085048074414.mp4.zip](https://github.com/breez/breezmobile/files/3991834/t_video5186294085048074414.mp4.zip)

**Comment by bitcoinuser** [comment]
This problem happens with Breez on background too and even without lock phone.
I just open Breez, minimize it, wait 30 seconds, restore Breez. Pin appear (and works) but doesn't show fingerprint popup even if I click on fingerprint button.

Obs. On my Breez settings I set to lock automatically = 30 sencond

**Comment by bitcoinuser** [comment]
I will close this bug, because I can't reproduce this all times. Doing the same steps, sometimes works sometimes fails.
