### ISSUE TITLE
Suggestion: drag window to left to show qrcode reader and qrcode invoice

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#240]
Recently Breez added lnurl withdraw but I think takes to much steps to open the qrcode reader. The user needs to click on invoice button and then click on the qrcode button.
I think the user should just drag the window to left to open the qrcode reader and be able to pay qrcode invoices or receive using lnurl withdraw.

See the example of BLW wallet. They have the drag window to open the qrcode reader, and I think this is very fast.

**Comment by kingonly** [comment]
We've implemented a global QR button
