### ISSUE TITLE
Allow checking the checkbox by tapping on the corresponding label

### ISSUE THREAD

**Issue by bolatovumar** [breez/breezmobile#242]
When setting up the app I kept trying to tap on the label to check the checkbox as is often the convention. I took me a couple of taps to realize that I wasn't just mistapping but that I had to tap on the checkbox itself.

It would be nice if tapping the label also checked the checkbox. I can attempt to implement this if ACKed. I don't have much experience with Dart but could be fun to dive into.

![Screenshot_20191222-100815](https://user-images.githubusercontent.com/1934678/71325604-109a3700-24a4-11ea-9da0-c25e89c9f7f6.png)
![Screenshot_20191222-100711](https://user-images.githubusercontent.com/1934678/71325605-109a3700-24a4-11ea-8872-0f33c13215f4.png)

**Comment by roeierez** [comment]
Thanks for your report.



> I can attempt to implement this if ACKed. I don't have much experience with Dart but could be fun to dive into

Sounds good.

**Comment by bolatovumar** [comment]
@roeierez looks like the https://github.com/breez/breez repo could use additional documentation as I couldn't follow the steps to build it. It's probably an environment difference issue.

**Comment by roeierez** [comment]
> @roeierez looks like the https://github.com/breez/breez repo could use additional documentation as I couldn't follow the steps to build it. It's probably an environment difference issue.

I will be happy to improve it. Can you elaborate more on which step has failed?

**Comment by bolatovumar** [comment]
@roeierez I opened an issue for it here: https://github.com/breez/breez/issues/104

**Comment by roeierez** [comment]
@bolatovumar thanks.
As result of your feedback I revisited both projects build documentation.
I hope now it is more clear and here for any additional feedback.

**Comment by bolatovumar** [comment]
@roeierez thanks, I can build now and will attempt the remaining steps to build the app.

**Comment by bolatovumar** [comment]
@roeierez on step 2 it says:
Copy `breez.aar` to the `android/app/libs/` directory

Where is the `android/apps/libs` directory meant be found on my system? I searched for `android` directory on my end and there are many and I'm not sure which one I'm supposed to copy the `breez.aar` file into.
