### ISSUE TITLE
Minor UI issue in "Redeem FastBitcoins Voucher" screen

### ISSUE THREAD

**Issue by bolatovumar** [breez/breezmobile#243]
Currency dropdown is misaligned with the "Voucher Value" field. It's not a big deal but annoys me.

![Screenshot_20191222-105950](https://user-images.githubusercontent.com/1934678/71327329-008e5180-24bc-11ea-98ed-bdd5bb5fe799.png)

**Comment by erdemyerebasmaz** [comment]
Issue persists on large screen devices ![image](https://user-images.githubusercontent.com/4012752/74238344-a903a980-4ce6-11ea-9e11-c1b693628247.png)

**Comment by kingonly** [comment]
Fixed in latest
