### ISSUE TITLE
Hodl invoices

### ISSUE THREAD

**Issue by grunch** [breez/breezmobile#255]
Hey guys, I'm trying to use hold Invoices with breez, but when I try to pay one the wallet get the regular `processing payment` modal forever, the wallet should be available to the user while is paying a hodl invoice.

If I close the wallet and I opened again the wallet refresh and show me the hodl invoice `pending` but it shows `Unknown` instead the invoice description.

If I got settled the invoice the wallet doesn't update that record, I need to close and open again the wallet to see that I paid the invoices.

If I got canceled the invoice wallet doesn't update that record, I need to close and open again the wallet to see that I got the money back.

**Comment by kingonly** [comment]
What's the service you are using?

**Comment by grunch** [comment]
Sorry I forget to mention.
lnd version 0.8.2-beta commit=queue/v1.0.2-170-g22e1f006b19453d08f92df0690f8b9762d5805ab

**Comment by kingonly** [comment]
We're going to add better support for hodl invoices in our next versions, but since hodl are not distinguishable from regular invoices, UX is tricky (knowing when to wait etc). We could add support for pre-defined services. What's your use case for using them?

**Comment by grunch** [comment]
Yes hold invoices are not distinguishable from regular invoices but I think a better UX should be not block the app while the user is waiting for a payment, like BLW does, that would  be a simple change for better UX and at the same time add support to hold invoices.

I want to add hold invoices on my site https://microbet.fun 

Currently if a user creates a prediction, pay invoice (+ routing fees) and wait for someone bet against it, if nobody bet against the user can withdraw the original amount but the site always get 1% on withdrawal (I can't separate balance with 1% on withdrawal with balance with 0%), so the user paid routing fees + 1% and couldn't play.

With hold invoices I can solve this, the user only pay when Is needed.

But I'm not going to do it until we have a nice UX on hodl invoices on the main wallets

**Comment by kingonly** [comment]
We're making some changes, but I don't think it's so straightforward... 
We'll take it into account. Thanks for your input. You might see something better in our next update.

**Comment by grunch** [comment]
Thanks bro, keep up the hard work 👊

**Comment by kingonly** [comment]
Thank you sir!

**Comment by kingonly** [comment]
In the latest update, "Processing Payment" dialog is closed after 10 sec (after received by the dest node), entering a "pending" state. Please let us know if it works for you and close the issue in case it is...
Thank you!

**Comment by grunch** [comment]
It worked great, thanks for this fast response :smile:
