### ISSUE TITLE
Bitcoin Bounce Lnurl withdraw problem on Breez

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#259]
Hi,

1- I tried to claim 100 sats from Bitcoin Bounce game to Breez.
2- I clicked claim and I choose Breez to withdraw the funds from Bitcoin Bounce using Lnurl
3- The payment was processing and never finished on Breez.
4- So I restarted Breez and no payment.
5- The funds appeared as claimed on Bitcoin Bounce.
Obs. I sent message to Bitcoin Bounce developer and he sent me back the 100 sats but he didn't know what caused the problem.

Conclusion: I think it's not ok the popup processing payment appear and never close, so I'm attaching the log.
[lnd (9).log](https://github.com/breez/breezmobile/files/4078168/lnd.9.log)

**Comment by jackeveritt** [comment]
The could be an issue with Bitcoin Bounce (I am the dev of that game).  I will confer with Breez team and make sure I am implementing LNURL in the way they expect

**Comment by jackeveritt** [comment]
I read your issue, and you had two problems. 

1) if the prize Claiming payment failed then bitcoin bounce said it was ‘claimed’
- we have fixed this. If the prize claiming fails we reset the status. Anything related to this is our bug so contact THNDR GAMES direct

2) if the cash out via LNUrL was failing, breez just got stuck with the pop up.
- this is still an open issue which needs further investigation

**Comment by roeierez** [comment]
@jackeveritt the breez popup has two options to be closed:
1. Error is returned by the service from the withdraw request.
2. Invoice was paid.
I think in this case none of these was happening which caused the dialog to just wait...

**Comment by jackeveritt** [comment]
The service returns to Breez asynchronously. So there is a scenario where the service tells Breez the payment was OK but it then it fails when the payment is attempted.

**Comment by roeierez** [comment]
@jackeveritt  understood. At this case there is no way for Breez to know if the payment is still in process or it is failed. 
This is why we added "Close" button at the bottom of the dialog so after some reasonable timeout the user can close it.
@bitcoinuser  one thing is not clear to me is your mention about "Processing Payment" stuck dialog while at the lnurl withdrawal case there is no such dialog as the user receives funds.

**Comment by bitcoinuser** [comment]
I said "processing payment" dialog because I didn't remember the title that appear on the popup. But it was a popup tha looked like the payment processing popup.

**Comment by bitcoinuser** [comment]
Popup that had no close button

**Comment by roeierez** [comment]
![Screenshot_20200131-102546](https://user-images.githubusercontent.com/5394889/73523790-54258080-4414-11ea-86d7-764fbc2ae80a.jpg)

I have been trying to reproduce this and failed.
I am attaching an image of how I saw it on my app. Did you see that dialog just without the close button on bottom?

**Comment by bitcoinuser** [comment]
Hi Roei, as I'm not sure if I saw the close button, (I think no). I will close this issue and If someday I reproduce this again, I reopen it. Thanks
