### ISSUE TITLE
Two times appear the receive window on Breez when withdraw sats from Bitcoin Bounce

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#260]
Hi

I had more than one experience with bitcoin bounce game and breez that I don't know how to reproduce. But happened more than one time.

I started the game and withdraw the sats to Breez wallet. (withdraw was success)

So I let the breez wallet opened and started to play the game again.

So I think I went to claim page with bitcoin bounce again and then I switched to Breez wallet.

So appeared the withdraw window funds again for the withdraw that i already had done.
If I click receive will open the processing popup but will not receive anything because I already had withdraw the sats before.

This is a bug I'm sure exist but I don't know how to reproduce exatly.

**Comment by jackeveritt** [comment]
In Bitcoin Bounce we open breez via the lightning: uri scheme. So this issue would apply to any app or website the opens breez via the lightning uri.

**Comment by jackeveritt** [comment]
Or breez is not clearing the LNURL between sessions

**Comment by roeierez** [comment]
> So I think I went to claim page with bitcoin bounce again and then I switched to Breez wallet.

Does this mean you clicked on an lnurl URL that opened breez app? Or you just switched to breez "manually"?

**Comment by bitcoinuser** [comment]
Just switched manually.

**Comment by bitcoinuser** [comment]
The same problem happened with Phoenix too, but on Phoenix I was able to withdraw two times.
