### ISSUE TITLE
Android app glitches when removing funds to an address.

### ISSUE THREAD

**Issue by UsherTechs** [breez/breezmobile#262]
The display alternates between the wallet balance before removal and the balance after. See reference video. [Reference Video](https://www.reddit.com/r/Bitcoin/comments/evjuek/breez_you_seriously_need_to_fix_your_wallet/)

**Comment by kingonly** [comment]
Thanks for your report! 
We'll take a look to see what may cause this to happen (not an issue we're are aware of).

**Comment by roeierez** [comment]
This looks like subsequent attempts to send payment on lightning that for each attempt a different route is used.
During each attempt the payment enters pending state (as the htlc is added) and when the attempt fails the payment exist this state (the htlc is canceled).
each transition for either direction triggers update of channel balance in LND and we reflect that as is in the UI.

**Comment by kingonly** [comment]
Maybe we need a to wait till multiple attempts are exhausted with a blocking (processing) UI.

**Comment by kingonly** [comment]
This is now fixed
