### ISSUE TITLE
Suggestions about the message to be required keep some sats.

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#275]
Hi, 

As I can see, on Receive there's a message that Breez needs to keep x sats on balance.

But I think should shown this way:

1- If user didn't receive any funds yet, the message should be on Receive as it is currently shown.
2- If the user receive more than the x sats that is necessary to keep, the message should now be showed on Send and not anymore on Receive.

**Comment by kingonly** [comment]
Won't implement as new channels are with zero reserve
