### ISSUE TITLE
Will it be possible to use Breez with a self-hosted backend?

### ISSUE THREAD

**Issue by stevenroose** [breez/breezmobile#28]
F.e. with a self-hosted lnd or clightning.

**Comment by kingonly** [comment]
Yes, you can use it with a self-hosted server:
https://github.com/breez/server

**Comment by netclectic** [comment]
It looks like it isn't possible currently to change the hub server in the client, it's only possible if I build my own custom client. 

Is this correct?
If so, are you planning to add the ability to set the hub server via the client?

**Comment by kingonly** [comment]
Yes, that's correct. 
We might also introduce a way to configure a different hub via our app, but currently we use submarine swaps and other services that are not offered in a "pure" lnd/c-lightning implementation.
This is not our focus at the moments.
