### ISSUE TITLE
Addition of breez: deeplink

### ISSUE THREAD

**Issue by Mvfaassen** [breez/breezmobile#300]
**What:**

breez: deeplink next to the lightning: & bitcoin: deeplinks

**Why:**

lightning: & Bitcoin: deeplinks won't work correctly if there are multiple of the same uris available on an IOS or desktop platform.

**How:**

add the prefix breez:, to the already available lightning: & bitcoin: deeplinks. Easiest way to set this up:

breez:lightning:{invoice} 

breez:bitcoin:{address}?amount={amount}

**Comment by kingonly** [comment]
New update includes breez: protocol. iOS is published, Android is waiting Google's approval.
