### ISSUE TITLE
Bug when try to receive via lnurl link with Breez create invoice popup opened.

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#324]
Steps:

1- Create an invoice on Breez and let the popup opened.
2- Go to Thunder game and click on process payment to receive via lnurl link, then choose Breez to receive.

Result:

I can receive the payment but Breez app freeze with the circles of payment received. It's not possible to to nothing on Breez. It's necessary to close and open it again to be possible to use it.

**Comment by kingonly** [comment]
Published
