### ISSUE TITLE
Double-paid LN invoice, shows correct balance, but only one tx in list

### ISSUE THREAD

**Issue by nanotube** [breez/breezmobile#331]
In Breez on android on a fresh wallet, I issued a payment invoice for 10k sat. 

When I paid it first time, a transaction showed up on my tx list, and my balance increased to 10ksat, as expected.

Then I accidentally paid the same invoice again. My balance increased to 20k sat, but no new transaction showed up in the list. So now there is a disconnect between sum of transactions and my balance.

I'll be glad to provide any additional info or debug logs or whatever is needed.

**Comment by kingonly** [comment]
Thanks for opening this issue... This is actually a well known issue. We were waiting for a fix in lnd, we'll check the status and post here the status.

**Comment by nanotube** [comment]
thank you for your quick response! i'll keep my eye on this issue.

**Comment by erdemyerebasmaz** [comment]
Closing. This issue was resolved eons ago.
