### ISSUE TITLE
Backup wallet without Google Drive

### ISSUE THREAD

**Issue by RobertHosking** [breez/breezmobile#333]
I get the notice in the top right telling me to backup. But the "Backup Now" button does nothing because I do not use Google. How can I backup manually? Are there files on my android file system that I can backup? How about a seed phrase or private key?

**Comment by kingonly** [comment]
Breez is a Lightning wallet, not an on-chain wallet, so seed phrase is not applicable in this case. 
Cloud backup is required to store the channel state after every payment. You can add an additional key phrase in the Advanced> Security & Backup. 
Android users typically have a Google account. On iOS, we also support iCloud.
Data is saved in a private data directory, accessible only via the app and by the user.

**Comment by RobertHosking** [comment]
What would it take to add Nextcloud support? When a nextcloud account is added to Android, it behaves a lot like a Google Drive account. It's available in the files sidebar and automatically syncs files. Most Android users have Google, most Breez users are privacy conscious, Google is not privacy conscious.

**Comment by kingonly** [comment]
Perhaps, but that's the reason we've added an additional key phrase protection. Nextcloud would be great, but it would take some time. We would definitely welcome a PR... I'm closing this issue here, but feel free to ping us on Twitter/Telegram.

**Comment by lucaszanella** [comment]
Lightning Wallets do indeed use a private key, but they also need the signed states. The private key only isn't useful for restoring the balance. I think though that people should be allowed to have access to their private keys and could also save the states in other places.

**Comment by kingonly** [comment]
We allow you to export the lnd files using 'Export DB Files' in the Developers menu. These files and a bit of lnd know-how allows you to restore w/o Breez. Moreover, additional cloud options are in our roadmap.

**Comment by kingonly** [comment]
WebDav backup was also added an option.
