### ISSUE TITLE
iPhone SE UI problem

### ISSUE THREAD

**Issue by dimaatmelodromru** [breez/breezmobile#339]
The following doesn't fit and doesn't scroll:
![264D490E-8E62-4F02-B213-1B8253FA1D46](https://user-images.githubusercontent.com/4951450/84882427-e95da480-b097-11ea-8bf5-723994d2e0ef.png)

**Comment by kingonly** [comment]
Since there's an easy workaround and this isn't a common scenario, we decided not to fix.
