### ISSUE TITLE
If you type one extra pin character, it incorrectly says "Incorrect pin"

### ISSUE THREAD

**Issue by fresheneesz** [breez/breezmobile#342]
If you type in your 6 character pin, and then type a 7th character, the "incorrect pin" message comes up right before it takes you into the app. Minor issue, but that should be an easy thing to get rid of.

**Comment by erdemyerebasmaz** [comment]
I could not reproduce the exact scenario but input is now disabled after entering pin code till it's authenticated.

**Comment by erdemyerebasmaz** [comment]
Will close when changes are live.

**Comment by kingonly** [comment]
Fixed
