### ISSUE TITLE
I accidentally paid on chain : (

### ISSUE THREAD

**Issue by fresheneesz** [breez/breezmobile#343]
So I've been playing around with this app with a friend of mine. He's less bitcoin savvy than I am and accidentally presented an onchain bitcoin address QR code to me when I expected him to show me a lightning QR code. I scanned it, and unthinkingly put in the amount to send him and pressed "next" and must have double tapped because I didn't even see the fee screen. Then I was very surprised  to see that my send to him had a huge fee on it (ie larger than 1 satoshi). Honestly I was pretty annoyed by this. 

So there are multiple things that went wrong here:

1. My friend was expecting a QR code to come up when he tapped "Receive via Invoice". He immediately backed out because he didn't see one. Now this is partially because he isn't super familiar with how lightning invoices work, but I think this could be improved to remove this potential confusion.
2. I didn't notice that I was on a "Send to BTC Address" screen because I was expecting something else.
3. I was able to double tap the button so that I sent the transaction without seeing any of the confirmation page.

3 is probably the worst part of this. You should not be able to double tap those buttons like that. It would be much better if there was no "Next" button. That page should present *all* the information with a "send" button at the bottom.  And there should be a confirm pop up with a button in a *different* place so there's no way to double tap. It should also be more visually clear what kind of transaction this is. I would recommend a prominent yellow-colored lightning bolt icon on the page vs maybe a silver colored bitcoin symbol (or something that visually indicates "on-chain") so that its easier to click with someone who is only half paying attention. 

1 This I think can be improved too. First of all "Receive via BTC Address" is not recognizable enough to newbies as being on-chain. To anyone who's new to bitcoin, a lightning node id could just as well be considered a "BTC Address". I mean, it is an address that you can send bitcoin to. Perhaps it should say "Receive On-Chain" or "Receive via On-Chain Address". Similarly, "Receive via Invoice" is not clear to a newbie either. To someone new to this, what would an "invoice" vs an "address" mean anything to them? "Receive via Invoice" should really read "Receive via Lightning". The invoice isn't what matters there, what's important is that you want to use lightning vs on-chain.

However, ideally people shouldn't even need to decide whether to receive on-chain or via lightning. What if you just clicked receive, typed an amount, and a QR code gave all the info to the other client to decide the best way to get bitcoins over there. If both support lightning, send via lightning. If not, send via bitcoin. Ideally, the user shouldn't have to navigate that nuance manually.

Another thing that can be done here is for a space for a QR code to be already apparent on this screen before you type in the info. For example, it could show a blurred out QR code below the input boxes, which will auto populate as you type in the amount/description. 

I do also want to mention that this update has a lot of great stuff! The easy ability to convert fiat to sats is very useful. The extra sending and receiving options are great too. Being able to simply send to someone you've paid or received from before would be a great feature (didn't get it working but will write another issue about it). So keep up the great work!

**Comment by fresheneesz** [comment]
To my suggestions on point 1, I think something like this mock up that bitcoinuser created would make it much clearer whether you're asking for money on lightning or on-chain: 

![](https://user-images.githubusercontent.com/1178856/76430384-0c890180-638f-11ea-8b43-2bfa3708df4d.jpg)

Except that the amount and description should actually appear where the "Add Custom Amount" is.

**Comment by kingonly** [comment]
I tried to repro #3 and couldn't...

**Comment by fresheneesz** [comment]
How can I use Breez on the testnet? I would like to play around this more without spending a bunch of money.

**Comment by leonardo-sj** [comment]
I would also like to know to start the app (via command line) on the testnet in an iOS/Android simulator.

**Comment by kingonly** [comment]
We don't provide a testnet option. You can build from source.

**Comment by fresheneesz** [comment]
@kingonly Can you please try to be a little more helpful? Where are instructions on how to configure Breez to talk to testnet if I build from the source? 

And why did you close this ticket? None of the problems I brought up have been addressed.

**Comment by kingonly** [comment]
I closed this issue because this isn't something we're going to fix anytime soon. While I hear your feedback, this scenario is caused by two mistakes:
1. Someone accidentally created a BTC address instead of a LN invoice.
2. You accidentally confirmed the tx. I verified it couldn't happen in double click.
If I hear from others this happened again, I'll reopen. Would you rather I keep it open and do nothing about it?

There are build instructions in the GitHub repositories. Our team is available in our telegram group if you need assistance.

**Comment by fresheneesz** [comment]
I listed a number of things that could be done about this. Particularly, the most actionable suggestions are my suggestions for making the UI clearer. I would be happy to discuss those further if you think you may not have understood what I was saying.

I see no instructions relating to configuring Breez for testnet, but I guess I'll ask the telegram group. Thanks.

**Comment by kingonly** [comment]
We appreciate your feedback and I've received your message loud and clear. Nevertheless, this isn't something we're going to address because of the reasons I've listed above. We're allowed to do so, right?
