### ISSUE TITLE
Send to Node ID not working and/or confusing user experience

### ISSUE THREAD

**Issue by fresheneesz** [breez/breezmobile#344]
I tried a couple times to send money to my friend's Node ID. However, every time it failed. I assume this was because his lightning app wasn't open at that exact moment, however all I get is a message saying "Failed Payment". It doesn't say why it failed, and so it breaks the first rule of error messages: they should always be actionable. I don't know what to do to make this work with the message "Failed Payment". Did it fail because his node wasn't online? If so it could recommend I tell the recipient to turn on their lightning node. Did it fail because none of the found routes worked? If so, what would I do? Etc. The error should be actionable to a user.

Second of all, the flow of tapping a previous payment, tapping Node ID, tapping copy, tapping send, then tapping paste Node ID is a bit cumbersome. It would be nice if you had a "Send" button on a transaction receipt that brought you straight to the pay to Node ID view. It would also be nice if there was an option in the "Send" menu for "Send to contact" that would list out the people you have interacted with and let you choose someone to send to. That would be much shorter.

I assume that the reason payment didn't work here is because his app wasn't open. When lightning rod is implemented, this flow should be incredibly easy, as you could simply pay someone and have it just work, and they can actually receive it whenever they open their app next.

**Comment by kingonly** [comment]
Send to Node ID isn't available for mobile nodes exactly for this reason. That's also the reason Node ID isn't exposed, but only available in the Developers screen.

Use Connect to Pay for Breez to Breez payments.

Not something we're going to change now, we need to see how Lightning evolves and first implement Lightning Rod.

**Comment by fresheneesz** [comment]
> only available in the Developers screen.

Actually, the Node ID is available on a transaction receipt. There's buttons for copying and sharing it.

> Not something we're going to change now,

I still think the error message should be improved now if possible. Is there more information available that can be told to the user?

**Comment by kingonly** [comment]
Not really. Errors are provided by the underlying implementation (lnd).

**Comment by fresheneesz** [comment]
Can we please discuss options before you close the ticket?

For example, does your Breez wallet know when its talking to another mobile Breez node?

**Comment by kingonly** [comment]
No, it doesn't know.
I don't close all the tickets, but I close the ones I believe we won't going to fix anytime soon (from a product standpoint, not implementation).
