### ISSUE TITLE
Be able to pay an invoice using Android notification

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#349]
Hi,

1- I browse on phone to https://strike.me/strike and a lightning invoice is generated.
2- I click to open with Breez.

What I expect:

Show an Android notification to Allow or Deny the payment. Something like this:

![android-l-notifications](https://user-images.githubusercontent.com/1178856/86514211-1c699d00-bde7-11ea-9b57-5dea9840a389.jpg)

**Comment by kingonly** [comment]
Leo, this doesn't make sense... The 'Open with' interface is designed to launch an app. This is how interop between apps work on mobile devices. The only other alternative is to create a special activity for Lightning payments by this hasn't been done yet.

**Comment by bitcoinuser** [comment]
Hi, I thought could be possible to launch the app minimized and just show the notifications.

**Comment by kingonly** [comment]
No such thing...
