### ISSUE TITLE
signmessage from breez failed to validate by lnd

### ISSUE THREAD

**Issue by offerm** [breez/breezmobile#355]
Use the developer/wallet menu to sing a message

on breez wallet:
```
signmessage hello

{
    "signature": "rn9z4se8f8ci9bcm3wsmxcz7n7e7cb773yegxaogh7gw867ys11iy3ti8dwzc6nzgirz3zg8r4rbd4abmiprw5k7j4gdse7i4cxxeojk"
}
```

verify on breez wallet
```
verifymessage hello rn9z4se8f8ci9bcm3wsmxcz7n7e7cb773yegxaogh7gw867ys11iy3ti8dwzc6nzgirz3zg8r4rbd4abmiprw5k7j4gdse7i4cxxeojk

{
    "valid": true,
    "pubkey": "02ff778c4a5b724ea7d45c78c2657f484a4172da140c35167163a8a06b925753ca"
}
```

Try the same with LND 
>lnd version 0.10.1-beta commit=v0.10.1-beta

```
lncli verifymessage hello rn9z4se8f8ci9bcm3wsmxcz7n7e7cb773yegxaogh7gw867ys11iy3ti8dwzc6nzgirz3zg8r4rbd4abmiprw5k7j4gdse7i4cxxeojk
{
    "valid": false,
    "pubkey": "02ff778c4a5b724ea7d45c78c2657f484a4172da140c35167163a8a06b925753ca"
}
```

**Comment by yaslama** [comment]
In the legacy family[1] of signing/verifying functions, as opposed to the new one [2], lnd checks [3] that the node is visible in the graph stored in its internal database.
Breez app nodes are generally connected to the Ligntning Network via a private channel only, so are they are not included in the graph stored by any node except themselves.
Right now, lnd still use the legacy family of functions in lncli, this is the reason "valid" is false.

[1]https://api.lightning.community/?shell#signmessage
[2]https://api.lightning.community/?shell#signmessage-2
[3]https://github.com/lightningnetwork/lnd/blob/master/rpcserver.go#L1403

**Comment by offerm** [comment]
Very well!

Thank you.
