### ISSUE TITLE
“All files have been downloaded” notifications

### ISSUE THREAD

**Issue by shawnyeager** [breez/breezmobile#361]
I'm seeing notifications on iOS with this text a few times each day. When I tap them, I'm dropped into the app with no further context or detail.

**Comment by kingonly** [comment]
Thanks for your report!
This notification appears when graph information is updated. It should happen when you open the app after a few days of inactivity. Could you please send us your logs to contact@breez.technology (Advanced> Developers> top right menu> Share Logs) and we see why it doesn't work as expected?
