### ISSUE TITLE
Suggestion: Add latinamerican fiat currencies to POS

### ISSUE THREAD

**Issue by grunch** [breez/breezmobile#373]
The POS mode is pretty awesome, there is a lot of people asking me how to receive LN the "easy" way, this is one of the easiest way for a merchant.

I received this kind of questions from mechants from latinamerica, the problem is there is no latinamerican fiat currencies.

I thinks we can start with three currencies, VES (Venezuela), ARS (Argentina) and MXN (Mexico).

It's important to let you know that Argentina and Venezuela have currency controls so we should't use APIs that shows the official rate cause is not the real one, I propose to use the api from this site which have the free market fiat currencies rate.

https://yadio.io/api.html

VES: https://api.yadio.io/rate/VES
ARS: https://api.yadio.io/rate/ARS
MXN: https://api.yadio.io/rate/MXN

The `usd` field in each endpoint is the pair rate VESUSD, ARSUSD, MXNUSD

**Comment by kingonly** [comment]
Added

**Comment by wksantiago** [comment]
Can we add the Curacao Guilder?

https://api.yadio.io/rate/ANG
