### ISSUE TITLE
Question: proper way to open custom channel from Breez

### ISSUE THREAD

**Issue by misovan** [breez/breezmobile#375]
For some more expert usage scenarios I would like to open a second channel apart from the one opened by Breez. Could someone please verify the process and resulting questions related to doing so?

- Using Developers access to on-device lnd rpcapi I generate new onchain address
- I send funds to this address from another wallet using onchain tx
- Walletbalance of lnd api becomes non-zero
- I connect to peer and subsequently open new channel using rpc committing funds from wallet

My questions / assumptions are:
- If I leave any balance in the wallet, can they be recovered using Breez backup feature?
- If not is there a way to restore them if Breez does not expose lnd seed?
- If I have another channel opened, do its transactions / local balance shown in Breez main UI?

Thank you for possible answers

**Comment by kingonly** [comment]
We recommend not going through the local wallet in creating additional channels. Although everything should work, it's not a flow that is well tested. Please see: https://github.com/breez/breezmobile/wiki/Creating-Channels

Breez balance/list support multiple channels.

**Comment by misovan** [comment]
OK got it, so the recommended way is to open inbound channel from remote node and then send some funds from this node to get outbound capacity on Breez side. This then completely removes the need to use on device wallet. Thanks for quick answer.

**Comment by kingonly** [comment]
Sure thing. And yes, exactly.
