### ISSUE TITLE
LNURL withdraw hangs

### ISSUE THREAD

**Issue by misovan** [breez/breezmobile#376]
When trying LNURL withdraw from LNBits to Breez, the app hangs after pressing Redeem. Popup on main screen shows Receive Funds, 0%, Synchronizing to the network.

Steps to reproduce:
- Create and fund a wallet on lnbits.com
- Enable LNURL withdraw extension
- Create withdrawal link
- Scan link QR with Breez
- Press on Redeem button

Tested both on lnbits.com and on private lnbits deployment.

**Comment by kingonly** [comment]
The issue doesn't seem to be related to lnurl. The app needs to be synced to the blockchain in order to receive funds, and in your case this process hangs. Does the same happen using Receive> Receive via Invoice? Do you use VPN/Firewall or some other software that might intercept network traffic?

**Comment by misovan** [comment]
Thanks for quick guidance. Looks like installed company profile on my phone intercepts / blocks some network traffic, dunno exactly which one. However after deactivating company profile and related certificates, ln withdraw works like Breez :)

Thanks!
