### ISSUE TITLE
Feature Request: Data Loss Protection

### ISSUE THREAD

**Issue by fresheneesz** [breez/breezmobile#384]
If anything happens to a user's google drive backup, [data loss protection](https://lightningwiki.net/index.php/Data_loss_protection) would be mighty helpful.

**Comment by kingonly** [comment]
DLP is already implemented in lnd. But you need SCB file to trigger it, and again, you need to store it and update it every time a channel is added.
In regards to backup, we'll probably implement a photon like architecture, so realistically we're not going to walk away from a cloud storage.

**Comment by fresheneesz** [comment]
> you need SCB file to trigger it, and again, you need to store it and update it every time a channel is added

Hmm, so the scenarios this protects against is where a per-transaction backup doesn't successfully complete, but it still requires additional static data beyond your seed. What in the SCB file is needed to do this?

Phoenix wallet has an implementation that allows restoring your lightning channel with just the seed. I have the same situation for both wallets right now - got a new phone, wiped the old one and traded it in. With phoenix I just had to put in my seed and the wallet was restored. With Breez it seems there's a lot more limitations. It would be nice if the channel partner kept all the information necessary to restore like Phoenix clearly does. Of course, this doesn't mean a redundant backup (like google drive backup) isn't necessary (since you don't want to *only* rely on your channel partner for backup), but it would help a lot in edge cases. It would be nice tho if there was a way to run your own backup/watchtower server that you could opt to use in place of connecting your google account and drive.

**Comment by kingonly** [comment]
That's one of the reasons Phoenix "locks" the user to its node. Breez doesn't and we don't plan to.
It's too early to discuss backup watchtowers simply because such solution isn't implemented yet, but we're definitely open to support it.

**Comment by fresheneesz** [comment]
> Phoenix "locks" the user to its node

I'm curious what that means. Any link you could point me to?
