### ISSUE TITLE
POS Keypad UX is harder to use 

### ISSUE THREAD

**Issue by bubersson** [breez/breezmobile#387]
The Keypad has couple of issues to use it efficiently on a phone.  

Functional:
- It's not possible to change (fix) the last entered number (otherwise entering works quite well)
- Add ability to enter (in settings) other fiat currencies than the one available

UX issues
- The keyboard is too big on normal phone making it harder to reach. 
- The letters are too small compared to the size of the buttons. 
- the currently entered number is quite small compared to the rest of the UI - it would be better more prominent

**Comment by kingonly** [comment]
Thanks for the feedback.
We're adding more fiat currencies soon.
FYI: we did a lot of UX research before providing this interface, take a look at Square POS for example.

**Comment by bubersson** [comment]
Thank you for quick reply! Overall I love the UI, this is mostly smaller nits that may be worth bringing up with your UX. 

Square POS is a good example: https://images.ctfassets.net/2d5q1td6cyxq/4TfaOHVJWO50Yn3nyYR3S4/dff8252bd63c726dfa696e347599f0ec/gallery-terminal-01.jpg they have bigger font and the buttons are not squares (on the picture, in reality those afaik don't have borders)

This probably depends on the size of the phone (e.g. my 6" makes the small letters on big buttons more pronounced)

**Comment by kingonly** [comment]
1. If you use Square, you see a very similar design to our POS. It even has a larger keypad, and they do have borders. The 'C' functionality is also the same.
2. The screenshots were taken using the smallest find (not the default font).

**Comment by kingonly** [comment]
I closed by accident... Just wanted to add users can control the font size with the device configuration. All and all feedback is very appreciated and we'll keep it in mind for future enhancements.
