### ISSUE TITLE
Suggestion: Ability to attach a photo to the POS sale

### ISSUE THREAD

**Issue by bubersson** [breez/breezmobile#388]
Note: This is a brainstorming suggestion, I don't have a clear usecase in mind. 

It could be quite useful to be able to attach a picture (e.g. directly taken by a camera) to the POS sale ("order"?). Currently it's possible to attach a note, but it could be quite useful to quickly snap a picture of the item/situation, etc. 
For example seller would snap a bar-code of the item being sold, which would nicely associate the sale and allow for further accounting. 
Or the restaurant could snap a picture of the produced dish that could be used as a proof and prevent the delivery person from eating half of my dinner again.

**Comment by tgienger** [comment]
A barcode scanner would be perfect for POS

**Comment by kingonly** [comment]
> A barcode scanner would be perfect for POS

If this is something needed to use Breez in production, please email us at contact@breez.technology to discuss the specifics of this requirement.

**Comment by kingonly** [comment]
Not planning to add this.
