### ISSUE TITLE
Bug: when creating a new invoice with backup synchronizing, the popup disappear

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#392]
Bug: when creating a new invoice with backup synchronizing, the popup disappear

See the video uploaded.
[video_2020-10-28_11-00-08.mp4.zip](https://github.com/breez/breezmobile/files/5452339/video_2020-10-28_11-00-08.mp4.zip)

**Comment by bitcoinuser** [comment]
Usually happens when I receive a transaction and some seconds after I create I create a new invoice.

**Comment by kingonly** [comment]
Can you still reproduce?

**Comment by bitcoinuser** [comment]
> Can you still reproduce?

No, but If happens again I reopen the issue. Thaanks.
