### ISSUE TITLE
Add CZK as one of the supported currencies

### ISSUE THREAD

**Issue by bubersson** [breez/breezmobile#401]
Since Breez now added support for bunch of new currencies, this is a request to add CZK as one of the supported currencies.

To add more background with couple examples:
- Czech republic is one of the more advanced BTC countries
- The home of Trezor (https://trezor.io/)
- The home of Slushpool (https://slushpool.com/)
- The biggest Czech retailer (think Amazon or BestBuy) openly supports BTC (e.g. https://www.alza.cz/EN/btcpay-server-jak-prijimat-bitcoin-navod)
- etc :)

**Comment by kingonly** [comment]
We'll look into it ASAP.
Thanks for reaching out!

**Comment by kingonly** [comment]
Added. There is a bug: the symbol should be on the right, correct?

**Comment by bubersson** [comment]
Yes, the symbol is on the right as in "Beer costs 25 CZK". 

Sidenote: If the app would be adding translations, then that also applies on currency and numerical standards, e.g. in this case it would be "Pivo je za 25,- Kč"
