### ISSUE TITLE
Feature for extraction of the google drive backup

### ISSUE THREAD

**Issue by fresheneesz** [breez/breezmobile#414]
I need help resolving #383. It would help me greatly if I was able to use the app to extract my google drive backup, so that I am 100% sure I have a copy that I can use to attempt restoration procedures and so that I know that if anything goes wrong with Breez (either stock or a version I modify myself) that my google drive backup won't be lost. I lost my money in Breez about 4 months ago a this point, and I'd appreciate some more help recovering it. I was not careless with my encryption key, so IMO there is clearly something wrong with the Breez recovery process. Maybe its a weird edge case that only affected me, maybe its something larger that has affected many unsuspecting users. I'd like to find out, but first I'd like to secure my backup in my own custody.

**Comment by kingonly** [comment]
We'll try to prioritize it.

**Comment by kingonly** [comment]
Added to our latest update: long press on the entry in the restore dialog to download the backup files. As said, backup was successfully tested many many times internally and externally. We have no reason to believe there's an issue with the backup/restore operation and we won't provide additional assistance in brute forcing the files.

**Comment by fresheneesz** [comment]
Thanks so much! I'll check this out and report back what I find.
