### ISSUE TITLE
Cannot "Receive via BTC Address"

### ISSUE THREAD

**Issue by hup121010** [breez/breezmobile#415]
**Timeline:**
- 2021-01-05: Sent some bitcoin to Breez Wallet via the "Receive via BTC Address" from Blue Wallet
- 2021-01-11: The transaction disappeared from Blue Wallet after taking too long to confirm (fee was too low)

However, I continue to see the following message in Breez:
> "Breez is processing your previous deposit. You will be able to add more funds once this operation is completed."

The message won't seem to go away, and it's not allowing me to cancel or start the process over.

How can I use the "Receive via BTC Address" feature now?

**Comment by kingonly** [comment]
Try the 'Reset Unconfirmed Swaps' action in Advanced> Developers top right menu.

**Comment by hup121010** [comment]
'Reset Unconfirmed Swaps' does not seem to make any difference.

**Comment by kingonly** [comment]
Sorry, 'Reset Unconfirmed Swaps' currently works on send btc txns, not receive btc. We're going to release an update on Sunday that includes the ability to reset receive txns as well.
Please wait till the next update and try again.

**Comment by kingonly** [comment]
Please try again after the latest update. Use 'Reset Unconfirmed Swaps', then restart the app.

**Comment by kingonly** [comment]
Can we close this issue?

**Comment by hup121010** [comment]
It seems to be working now, after doing 'Reset Unconfirmed Swaps'.

Please note that it didn't work right away (I needed to force-close and restart the app before I could receive again).

**Comment by kingonly** [comment]
Yep, a restart is required. So closing...
