### ISSUE TITLE
Payment never routed through direct channel

### ISSUE THREAD

**Issue by misovan** [breez/breezmobile#417]
Hi, I have a direct channel between my Breez wallet and my own LND node that I opened through Breez's developer console. My wallet's node has a local balance in that channel and channel is active according to the `listchannels` command. However when I try to pay invoice or to my channel pubkey, payment is always routed through Breez node, not taking into account direct channel option. I re-checked with wallet node's `queryroutes` command and it ignores direct channel as well.

Does anybody know about any possible reason for such behavior? Thx

**Comment by kingonly** [comment]
Interesting... 
If it's a public channel, I wonder if the channel is included in the graph data (you can use Describe Graph in the Developers screen top right menu to download the graph data).

You can also try to reset lnd mission control using the resetmc command.

You can also try sendtoroute but I never tried it from the Breez app.

**Comment by misovan** [comment]
I tried to send payment through the console while force setting outgoing channel to the direct channel id and lnd responded "insufficient balance", (local balance is 1mio sats). Channel is apparently in some weird state, so I did close it and moved balance to another onchain wallet.

My question than is, what is then the proper way to open own channels to/from Breez wallet - ideal would be to open it from the other node, however Breez wallet node does not expose ip address to connect to. Thanks for any advice.

**Comment by kingonly** [comment]
ip won't help you because you're behind a NAT most likely (Breez uses the same ip assigned to your device).

You just need to first connect to the peer from the device, then open a channel from the peer. Please see: https://github.com/breez/breezmobile/wiki/Creating-Channels

I'm closing the issue for now, feel free to open another if needed.
