### ISSUE TITLE
Fiat value for past transactions

### ISSUE THREAD

**Issue by Chris869218** [breez/breezmobile#420]
Is there a particular reason for not displaying the approximate fiat value for previous transactions? If an invoice was entered by typing in a USD (or other fiat currency) value, could that value just automatically be part of the description field, or saved elsewhere with the option for future display? 

If someone sends an invoice for 'lunch', currently my workaround is saying "hey, can you cancel that and change the description to $25 for lunch" which is a bit awkward. 

It is nice to be able to go back and remember what I was paying for without having to look up the historical BTC price on that day.

**Comment by nanotube** [comment]
FWIW, i like this idea.

**Comment by kingonly** [comment]
Added to POS Transactions screen
