### ISSUE TITLE
Error after sending BTC from BRD to Breez

### ISSUE THREAD

**Issue by dlvry** [breez/breezmobile#423]
Sent BTC from BRD wallet on iOS to Breez on iOS.

5/6 confirmations on BRD, while on Breez I have a msg that says:

Failed to add funds: rpc error: code = Unknown
desc = Error in payment response:
insufficient_balance

![IMG_7868](https://user-images.githubusercontent.com/16870157/107297840-2e2cb600-6a42-11eb-85a5-feeee4597293.PNG)

**Comment by yaslama** [comment]
@dlvry We had a temporary channel problem. Can you retry now please?

**Comment by dlvry** [comment]
Reloaded app this am and Sats are sitting where they should be. :) Thank you!

**Comment by kingonly** [comment]
Perfect! Closing....
