### ISSUE TITLE
Payment from Breez to Muun failed

### ISSUE THREAD

**Issue by lschmierer** [breez/breezmobile#424]
I tried sending a payment from Breez wallet on iOS to Muun on iOS.
On Breez the payment is shown as pending. On Muun the payment is shown as failed.

**Comment by kingonly** [comment]
Muun doesn't support MPP and for some reason the HTLC are not cancelled correctly on their end. We will include ba workaround in our next version not to send MPP to Muun, but for now you will have to wait bfor payment expiration.

**Comment by kingonly** [comment]
I'm a bit reluctant to integrate a fix not to send payments when there's no mpp support. Our users won't understand the failures they will get.
The "right" fix is in not at the payment process, but at when non-mpp invoice is shown. We need to hhow a different max amount when trying to pay non-mpp invoices (the local balance of the largest channel). However, this is a much more complicated fix and I'm not sure it's necessary if almost everyone are supporting mpp. Also, our basic architecture with multiple channels basically requires mpp to work... W/o it almost every payment to Muun will fail.

In the case of Muun, till they support MPP, we just need payments to gracefully fail.
The problem I see is that not all HTLCs are cancelled correctly and the payment is still pending on the Breez end. 

We're checking with Muun if that something that they can fix on their end.

**Comment by kingonly** [comment]
We've added a fix in our last update not to use mpp when sending to Muun. Most likely that for now, till Muun supports mpp, a lot of payments will fail with no route, but that's the best we can do on our end.
