### ISSUE TITLE
Marketplace not available without balance

### ISSUE THREAD

**Issue by Fittiboy** [breez/breezmobile#427]
Currently, the Marketplace seems to not be available without a wallet balance. Aside from the fact that it would be nice to be able to browse the Marketplace, it also blocks you from accessing your LN Markets account.
This can obviously be worked around if you have an API key or by transferring at least one sat to your Breez wallet, but some people will not have that option, and will not have access to LN Markets.

**Comment by kingonly** [comment]
We'll probably change it in the next major version. You can always access lnm from another device and log in using QR code.
