### ISSUE TITLE
Translate the labels in the UI into Spanish

### ISSUE THREAD

**Issue by bubersson** [breez/breezmobile#430]
I was teaching a street vendor in South America about Bitcoin, installed Breez for him, but he was confused, mainly because the UI was only in english on his phone. Unless I'm missing something I don't see a way to switch the UI to Spanish?

Note that I don't actually speak Spanish, but if we are talking translations, then Spanish would have imo the biggest impact as many latin countries are in a strong need of "small amount" Lightning transactions.

**Comment by kingonly** [comment]
WIP.
