### ISSUE TITLE
Display BTCUSD price in main screen

### ISSUE THREAD

**Issue by nanotube** [breez/breezmobile#431]
Currently, breez shows the USD value of the sats currently in the wallet. It would be nice if it also displayed btc/usd price (similar to how BLW does it). That would avoid needing to look up price separately. 
I am thinking perhaps on that line where the wallet usd value is displayed, could display full price in parentheses? Since the data is obviously already available to the breez wallet, hopefully it doesn't take much to just add a display for it. 
alternatively, if you want to avoid cluttering the gui, one of the currency toggles when you click on the fiat value, could include full btc price.

**Comment by kingonly** [comment]
Do you mean the current conversation rate? Are you aware we have that in the conversation dialog? Most wallets don't have this information in their main screen, but we'll keep it in mind for future redesigns.

**Comment by nanotube** [comment]
Hi, thank you for the quick follow up!
Yes, i mean the current bitcoin price (as in, ~48k as of this moment)
And I am not sure where to find this "conversation dialog" you mention? Could you tell me where to click so I can find this info inside breez?
thank you again!

**Comment by kingonly** [comment]
The conversation dialog is available in any place you need to enter sats/btc in an input field (the icon on the right with the arrows). It allows you to convert from fiat to sats. For example: Receive> Receive via Invoice in the Amount field.

**Comment by nanotube** [comment]
aha, i see it! thank you! :)
not as convenient as seeing it on the main screen, but if it takes me a couple clicks to get to the price, it works for me. :)

**Comment by kingonly** [comment]
👍 Closing for now.
