### ISSUE TITLE
"Failed to receive funds: EOF" when scanning LNURLw QR code

### ISSUE THREAD

**Issue by Chris869218** [breez/breezmobile#433]
I created a LNURLw voucher with lnbits.com. When I scan the QR code, Breez throws up a 'Receive Funds' dialog with "Failed to receive funds: EOF" as the displayed text. Is this an issue on Breez's end, lnbits.com's end, or c) none of the above?

**Comment by Chris869218** [comment]
Update - I tried the same LNURLw QR code today and it worked. Any chance a more descriptive error could be used to inform the user why it failed when it does fail?

**Comment by kingonly** [comment]
The error is provided by lnurl provider, it's not a Breez related issue...

**Comment by Chris869218** [comment]
Noted. Thanks
