### ISSUE TITLE
How to open relay on successful payment

### ISSUE THREAD

**Issue by iBobik** [breez/breezmobile#438]
I would like to have a fridge with drinks what can be unlocked by a payment on POS.

For this I need to somehow detect successful payment on a POS. Ideally if an Android tablet send some signal by USB where is somehow electromagnetic lock wired.

**Comment by kingonly** [comment]
You are welcome to open a PR. You can also join our telegram group if you require an assistance from our devs, but this isn't something we're planning to develop...

**Comment by iBobik** [comment]
Fair enough, thank you for reply
