### ISSUE TITLE
Unable to leave podcast 'discover' search window

### ISSUE THREAD

**Issue by Chris869218** [breez/breezmobile#439]
After searching for a podcast (on iOS), the x in the top right does not appear to do anything. There is no way to get back to the main Breez menu without killing the app and reopening. Sliding the menu from the left side of the screen also doesn't work from here.

**Comment by kingonly** [comment]
There's a bug: there should be a back arrow on the top left side, but it's white in light mode...
We'll fix it ASAP. You can use the dark mode in the meantime...

**Comment by Chris869218** [comment]
Great, thanks. Just wanted to note it in case it wasn't already known.

**Comment by kingonly** [comment]
Ofc, much appreciated 🙏

**Comment by kingonly** [comment]
Fixed
