### ISSUE TITLE
Podcast Player: defense needed for invalid types in JSON

### ISSUE THREAD

**Issue by daveajones** [breez/breezmobile#443]
Currently, the Breez podcast player crashes back to the episodes list when a JSON chapters file gives the "startTime" value as a string instead of a number.  This might be a fairly common occurence with various non-typed language based JSON generators (like PHP) that infer type incorrectly sometimes when encoding from an array.

It would probably be good to have some defensive code in the player to handle that possibility.

Example:
![image](https://user-images.githubusercontent.com/1498236/112243467-982ca380-8c1b-11eb-8755-72fcfdc0f587.png)

**Comment by amugofjava** [comment]
Linked issue: [https://github.com/amugofjava/podcast_search/issues/8](https://github.com/amugofjava/podcast_search/issues/8)
