### ISSUE TITLE
Transaction history does not show up

### ISSUE THREAD

**Issue by bitbug42** [breez/breezmobile#444]
Hello,
I'm having a bug with my Breez wallet, the transaction history fails to load [(see picture)](https://user-images.githubusercontent.com/50223813/112295549-4d02a700-8c94-11eb-90f5-58b2b08caf0d.jpg)
(I did a dozen or so transactions with that wallet before)

Sometimes when I restart the app, the history shows for a brief second before disappearing.

The bug started to occur after I tried to tip a node with a keysend payment. The keysend failed with error message `Failed to send payment: rpc error: code = Unknown desc = cannot marshall failure *lnwire.InvalidOnionPayload`.

**Comment by kingonly** [comment]
Can you please send us your logs to contact@breez.technology?
Preferences> Developers screen> top right menu> Share Logs

**Comment by bitbug42** [comment]
Sure, logs sent.

**Comment by kingonly** [comment]
We think we have a solution, we'll share a test package today/tomorrow.

**Comment by kingonly** [comment]
Test build:
https://drive.google.com/file/d/1GjZcm95PFquZ03KmrvoYvN07JneP99_c/view?usp=drivesdk

Can you please install and let us know if it helps?
If not, please send logs.

**Comment by Kixunil** [comment]
The transactions are shown now, but I still see one issue that may or may not be related to this. I played a podcast and hit "Boost" a few times during the podcast, yet it sent less sats than one "Boost". So I guess "Boost" doesn't work for some reason or the latest payments were not processed and it's not shown in the UI at all.

**Comment by kingonly** [comment]
Probably unrelated.
Please open a different issue and send the logs.
This seem to be related to the configuration of the specific podcast.

**Comment by Kixunil** [comment]
OK, I've sent the logs already but will ask the podcaster about it.

**Comment by kingonly** [comment]
No need, just give us the name of the podcast.
Sometimes,  if it's a new node and it takes some time for the graph to be updated.
To expedite the process, go to Preferences> Developers screen> top right menu and click Update Graph. Restart Breez and wait a minute or two before trying again.

**Comment by Kixunil** [comment]
Should be older node. "Reči o živote, vesmíre a vôbec", he's already making sure to open and rebalance a channel.

**Comment by bitbug42** [comment]
> Test build:
> https://drive.google.com/file/d/1GjZcm95PFquZ03KmrvoYvN07JneP99_c/view?usp=drivesdk
> 
> Can you please install and let us know if it helps?
> If not, please send logs.

Thanks! Although I'm on iOS, so I can't test this APK, sorry.
