### ISSUE TITLE
Podcast data block record 7629169, no unique data

### ISSUE THREAD

**Issue by AbelLykens** [breez/breezmobile#451]
Please add

` podcastindex_id: 12345`

to the sent data in the value payments. Would really help me ;)

Podcast title is not unique per se. Podcastindex_id should be :)

**Comment by kingonly** [comment]
Makes sense. Will do.

**Comment by kingonly** [comment]
We're adding podcastindex_id today, isn't it enough?

**Comment by satoshisstream** [comment]
**Very sorry for this.** 

I only yesterday read about the Breez format. They use key `feedID`. I am trying to NOT introduce more different keys (which I did by proposing `podcastindex_id`, so sorry for that!

If we are standardizing (I am suggesting using your Breez format as a start), let's use existing keys over new ones.

**Comment by kingonly** [comment]
Added feedID to our last update

**Comment by satoshisstream** [comment]
Much appreciated!!!
