### ISSUE TITLE
Bug that make main window "crazy"

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#452]
Hi,

I tried to make a payment using keysend (paste node id). After I clicked send. I see this:

![photo_2021-03-25_22-32-09](https://user-images.githubusercontent.com/1178856/112564618-5c7c1000-8dba-11eb-8399-079b432bb6bd.jpg)

Obs. Restart doesn't make this work. The window appear correctly and after some seconds stay crazy again as you can see on video:

https://user-images.githubusercontent.com/1178856/112564779-a238d880-8dba-11eb-9872-092ad0b876fa.mp4

Logs here:

[lnd (5).log](https://github.com/breez/breezmobile/files/6208781/lnd.5.log)

**Comment by kingonly** [comment]
Similar to https://github.com/breez/breezmobile/issues/444

**Comment by Kixunil** [comment]
Same here (Android) and I know someone who experienced it on iOS.

I may have the steps to reproduce:

1. Have Breez installed with a few transactions
2. Open a podcast (I tried one from Stephan Livera), listen to it, pay some sats
3. Come back later, open another podcast (tried "Reči o živote, vesmíre a vôbec" this time)
4. Listen a bit, boost a bit, I also changed values of stream and boost in between operations
5. Look into wallet - no transaction for the latest podcast shown
6. Kill the app
7. Open the app - the transaction shows up - smaller value than what I actually intended to send, then everything disappears

**Comment by kingonly** [comment]
We think we have a solution, we'll share a test package today/tomorrow.

**Comment by kingonly** [comment]
Test build:

**Comment by bitcoinuser** [comment]
Fixed here.
