### ISSUE TITLE
Podcast Value splits not updated on pull to refresh

### ISSUE THREAD

**Issue by AbelLykens** [breez/breezmobile#453]
What I did:
1) Install Breez 3 days ago
2) Subscribed to podcast 3 days ago
3) Changed value split 1 day ago
4) Pulled to refresh podcast, listened to new podcast ep
5) Noticed value is still sent to old split

Workaround:
1) Unsubscribe from podcast
2) Resubscribe
3) Splits are now sent correctly

What I hoped would happen:
*) Splits would be updated on podcast pull-to-refresh

Interesting:
*) New users did get the correct split

**Comment by kingonly** [comment]
Fixed in our last update
