### ISSUE TITLE
<br> in description of RSS is not being shown on app.

### ISSUE THREAD

**Issue by genen** [breez/breezmobile#455]
Using podcasting 2.0 compliant RSS generated by buzzsprout.com hosting for podcast.sirgene.com the Breez app just puts everything in the description into one line with no line or paragraph breaks. Should be like the second example.
![signal-2021-03-30-193236](https://user-images.githubusercontent.com/332206/113073633-1397d300-918f-11eb-96da-b93c059bf3a3.png)
![Screenshot 2021-03-30 193209](https://user-images.githubusercontent.com/332206/113073610-08dd3e00-918f-11eb-93d0-4677dcba5b81.png)

    <item><itunes:title>0026 Sir Gene Speaks</itunes:title><title>0026 Sir Gene Speaks</title>
    <description><![CDATA[**<p>I recommend listening at 1.25X<br/><br/>Story Images and Links are only visible to Podcasting 2.0 Apps such as the following:<br/>I recommend <a href='https://apps.apple.com/us/app/podverse/id1390888454'>Podverse </a>on iOS<br/>I recommend <a href='https://play.google.com/store/apps/details?id=com.bambuna.podcastaddict'>PodcastAddict </a>on Android<br/>Get beta of <a href='https://breez.technology/'>Breez </a>with bitcoin donation option <a href='https://breez.technology/'>https://breez.technology/</a>  <a href='https://breez.technology/'><br/></a><br/>See all the <a href='https://podcastindex.org/apps'>latest APPS</a> for Podcasting 2.0<br/><br/>Episode Produced with financial support provided by: BrewCityMike $50</p> <p><a rel="payment" href="https://paypal.me/SirGeneSpeaks">Support the show</a> (https://paypal.me/SirGeneSpeaks)</p><br><a target='_blank' href='https://www.buzzsprout.com/?referrer_id=1623706'>Move to the same Podcast Host I use!</a> <br>Get some credit on Buzzsprout! $20 Amazon Gift Card<br><br>]]>**</description>

**Comment by kingonly** [comment]
We'll add a space

**Comment by genen** [comment]
This is not the summary field. This is the description field.  The image is what is in the summary field - without <br>
![Capture](https://user-images.githubusercontent.com/332206/113219317-c5460b00-9246-11eb-9491-fa92407877f5.JPG)

**Comment by kingonly** [comment]
I meant a preview of the description.

**Comment by kingonly** [comment]
Fixed in latest (br are converted to spaces).
