### ISSUE TITLE
Podcasts don't auto-refresh

### ISSUE THREAD

**Issue by genen** [breez/breezmobile#456]
In iOS version at least, when I am subscribed to a podcast, only the episodes which were online the previous time I listened are showing. I need to manually pull down on that podcast to do a refresh of its RSS feed to see any new episodes.  

Is this by design or a bug? Generally, when a podcast app lets you subscribe to podcasts, it will at minimum keep the feed refreshed and optionally auto-download new episodes. I think the same type of functionality would be expected by users here as well.

**Comment by kingonly** [comment]
It's by design, but the library author is working on a better solution.

**Comment by kingonly** [comment]
This partially fixed in the latest update. What's missing is an indication that's there's a refresh in progress.
