### ISSUE TITLE
Charge by Breez for failed transactions

### ISSUE THREAD

**Issue by genen** [breez/breezmobile#457]
It seems that when there are errors sending sats, the app still charges for the Breez portion as though the transactions went through. 
I had users report to me when they had errors while listening to my podcast, and I just see the same thing with Free Domain podcast where the minute fee that was turned on apparently had errors and yet there was a charge from Breez.  

Is that by design and is it mentioned in the TOS document or is this a bug and fees should not be charged by Breez if the transaction times out?

![signal-2021-03-31-181254](https://user-images.githubusercontent.com/332206/113222754-46080580-924d-11eb-97be-0cdeba2095ba.png)

**Comment by bitcoinuser** [comment]
Related to: https://github.com/breez/breezmobile/issues/450

**Comment by kingonly** [comment]
Breez like PodcastIndex or others in the value block is part of the split. These are not routing fees. Payments are sent in parallel and one payment isn't dependant on the other. We are also helping and investing A LOT of time in supporting "faulty" nodes.
