### ISSUE TITLE
[Podcast] Enqueue multiple episodes

### ISSUE THREAD

**Issue by MaxHillebrand** [breez/breezmobile#462]
Currently after one episode is finished, no new episode is starting. 

It would be nice to have a list of enqueued episodes, where one plays after the other is complete. 

Sorting this list manually would be nice too. 

As well as an easy way to add an unplayed episode to the list.

**Comment by MaxHillebrand** [comment]
if this gets implemented, the sleep timer #492 should have an additional option of `sleep at end of episode`.

**Comment by kingonly** [comment]
That's the plan 🙂
