### ISSUE TITLE
[Podcast] Remember previously played episode

### ISSUE THREAD

**Issue by MaxHillebrand** [breez/breezmobile#463]
Currently, when I force close Breez while listening to a podcast, and then I restart it later, it does not remember the previously played episode. I have to go back into the subscription feed and click play on the episode, where it then remembers the time it was left off.

It would be great if there's a constant Play button in the Podcast home screen, where at any time even after wallet restart, I can press play and continue the podcast.

**Comment by MaxHillebrand** [comment]
To be clear, this is already implemented for when the podcast is paused, and breez is kept running. Then this player pops up.

![screenshot_20210411_115336](https://user-images.githubusercontent.com/30683012/114299616-989eb880-9abc-11eb-9cfb-b2b5925fd03d.png)

My request is to show this player even when Breez was force closed and is starting fresh for the first time.

**Comment by kingonly** [comment]
https://github.com/amugofjava/anytime_podcast_player/commit/831d6aca5f0173575356f087d2b542172f615ef2

**Comment by kingonly** [comment]
Fixed in latest

**Comment by MaxHillebrand** [comment]
tACK 1622189719-1.apk, nice improvement, thanks!
