### ISSUE TITLE
[Podcast] Custom sats amount

### ISSUE THREAD

**Issue by MaxHillebrand** [breez/breezmobile#466]
Currently the user can click `-` and `+` to increase decrease the amount of sats in pre-defined intervals.

The idea of `value for value` that is the core of Podcasting 2.0 is that the listener chooses himself how much and in what type [time, talent, treasure] to contribute. I think that pre-defining the donation values is in contradiction to the core mission.

For example, often the lowest sat/minute value is 10 sats, and when listening to the same show for days, this does sum up to a considerable amount, which maybe is too much cost for the listener. On the other hand, some might want to toss 10000 sats per minute, and those are also hindered to give the value they desire. Currently the only option to reduce the total cost, is to sometimes turn off the sats streaming to 0, or to only boost a pre-defined amount. But then the there's the problem that the user might forget to turn it back up again. The only way to increase donation, is by manually boosting often, which again has mental transaction costs.

I think it would be better if the user has three input options:
- `+` to increase to the next pre-defined amount.
- `-` to decrease to the next pre-defined amount.
- custom input of sats / minute, maybe by clicking on the number in between the buttons, and the number pad pops up.

**Comment by kingonly** [comment]
The use case here isn't really custom amount, but an amount less than 10 sats. Thing is that  with the current fees, and especially when you have multiple splits, going below 10 doesn't really make economic sense (we try to make the sats/min gross in our algo). Ofc the client side aggregation can handle it, but the UX won't be as good.

**Comment by MaxHillebrand** [comment]
yes, transaction fees is a concern here, I hope that the client side aggregation can indeed handle it. 

But notice that the request goes both ways, I currently can't toss 10k sats/minute neither. 

Maybe it does make sense to have a certain amount as the minimum / maximum based on real constraints of LN.

Maybe I also want to toss a fun amount, like 1337 sats/minute.

My main concern is that the fundamental value for value principle relies on the actual value of the individual listener, and no pre-set value can adequately describe this.

**Comment by kingonly** [comment]
sats/min is 1K max atm.
Not sure I understand the difference between 1k to 1337.

I tend to disagree with the last statement, I think we can cover most of the use cases with predefined values, but we'll see.

**Comment by MaxHillebrand** [comment]
> If you get any value from this project, or if you just believe in it and want to help us out with hosting fees and paying the bills, a donation of **any amount** would be great.
https://podcastindex.org

I hear Adam Curry say repeatedly that the core ethos of `value for value` is that each individual decides how much value he actually gets from the show, and then recuperates this value in some form [time, talent, treasure]. 

Regarding fun amounts, for example on the podcasting 2.0 show donors are often sending in donations with custom amounts, like 1337 sats [leed], or 19.84 USD [orwell] etc.

**Comment by kingonly** [comment]
There's no argument ethos wise. But sometimes you do some compromises to provide a cleaner UX that better helps the cause. We try to find the right balance, and tbh, I don't mind missing some use cases if it helps the 80%.

If we'll get more feedback supporting this, we will add it. Just keep in mind, nothing comes free. Adding a custom amount means you need a way to remove/edit, etc.

**Comment by MaxHillebrand** [comment]
Checkout episode 31 of the [podcasting 2.0](https://podcastindex.org/podcast/920666) show, at the 11:30 minute mark, Adam and @daveajones actually mention that the custom sat amount is missing in Breez. Adam mentions explicitly that he would like to send `333` sats / minute ["fun" amount]

**Comment by adamc199** [comment]
Experience has shown that allowing a custom amount results in more being sent at higher amounts. Is a compromise possible where the minimum amount is 10 (or whatever needed to still make economic send with network fees)?

The podcastindex node receives 1% split from all v4vtransactions and from what we *can* see, boosting from Sphinx is significantly higher, as they allow custom amounts.

Conversely, Sphinx users rarely adjust their per/min sats above 10 sats/min, likely because they do not surface this setting in the UI, only in settings

**Comment by kingonly** [comment]
Ok, I'm sold... We'll add it.

**Comment by adamc199** [comment]
Thank You For Your Courage!!

**Comment by kingonly** [comment]
Click on the amount now allows you to add a custom amount.

**Comment by MaxHillebrand** [comment]
Awesome, thank you for shipping!

y'all are rockstars! :black_heart:

**Comment by MaxHillebrand** [comment]
tACK 1622189719-1.apk, works exactly how I imagined it, awesome!
