### ISSUE TITLE
Connecting to testnet

### ISSUE THREAD

**Issue by mcroad** [breez/breezmobile#467]
In orde to continue the #464 effort, I need to be able to access every screen in the app. Some screens are only available if the wallet has a balance. I need to be able to run the app on testnet.

I have already attempted to configure the app for testnet by following the instructions on the readme. This did not work. I tried pinging the node adress listed, `3.16.119.191`, but it doesn't even respond. I asked on the telegram group but was told to open an issue here.

I need instructions to run the app on testnet.

**Comment by roeierez** [comment]
@mcroad probably this node doesn't exist any more.
I suggest to pick another testnet well connected node which you can find here: https://1ml.com/testnet/
A few examples I saw:

038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9@203.132.94.196:9735
030f0bf260acdbd3edcad84d7588ec7c5df4711e87e6a23016f989b8d3a4147230@163.172.94.64:9735

Also please attach your logs so I can help with the sync issue.
Let me know how it goes.

**Comment by mcroad** [comment]
Back from short hiatus.

The readme instructs to change `breez.conf` and `lnd.conf`:
```diff
# breez.conf
-network=mainnet
+network=testnet
-peer=btcd-mainnet.lightning.computer
+peer=btcd-testnet.lightning.computer

# lnd.conf
-neutrino.connect=btcd-mainnet.lightning.computer
+neutrino.connect=btcd-testnet.lightning.computer
```

Am I suposed to run my own breez server or is `.lightning.computer` a real server? If it's not real, how do I go about running my own on testnet?

**Comment by roeierez** [comment]
> Am I suposed to run my own breez server or is `.lightning.computer` a real server? If it's not real, how do I go about running my own on testnet?

That was the intention but I see this testnet node is no longer functioning...
Today bitcoin core supports compact filters so you can run your own bitcoin node in testnet (either btcd or bitcoin core).
LND documents how to run each of them in the installation Readme: https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md#available-backend-operating-modes
If you choose to run bitcoin core (which faster and recommended) you should add these configuration options to its config file so it will support compact filters:

```
blockfilterindex=1
peerblockfilters=1
```

Once you configure a working node it will start syncing.

**Comment by mcroad** [comment]
Got stuck on a different error after pulling the latest commits from `master`. This error keeps coming up:

```
E/BREEZUI (14633): Error in method rate: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: missing address"
E/BREEZUI (14633): go.Universe$proxyerror: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: missing address"
E/BREEZUI (14633):      at bindings.Bindings.rate(Native Method)
E/BREEZUI (14633):      at java.lang.reflect.Method.invoke(Native Method)
E/BREEZUI (14633):      at com.breez.client.plugins.breez.breezlib.Breez$BreezTask.run(Breez.java:327)
E/BREEZUI (14633):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/BREEZUI (14633):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/BREEZUI (14633):      at java.lang.Thread.run(Thread.java:923)
I/flutter (14633): Error in calling method rate
I/GoLog   (14633): 2021-06-07 01:22:57.108 [INF] CLIENT: getBreezClientConnection - before Ping;
I/GoLog   (14633): 2021-06-07 01:22:57.108 [INF] CLIENT: getBreezClientConnection - after Ping; err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: missing address"
```

Again this is from the master branch. App runs but as soon as it tries to do any transaction, it fails. Any idea why this would be?

**Comment by roeierez** [comment]
This error is not related to the failed payment. It is because you are not connected to breez server that serves the "rate" endpoint (for currencies) and It is not needed for payment. 
Can you please tell me what error you get in the UI?
Also can you pease share the logs?

**Comment by mcroad** [comment]
To be more specific, this happens specifially when trying to generate an invoice.
UI says:
>Failed to create an invoice (rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: missing address"). Please try again later.

where do I get "the logs"? I pasted the recuring error in my comment above.

**Comment by roeierez** [comment]
Thanks you for the logs @mcroad . I indeed see now the problem.
Unfortunately since we added support for zero-conf channels testnet is won't be able to work without running the breez-server (https://github.com/breez/server) and lspd(https://github.com/breez/lspd).
We can go that path but I haven't try it myself and I suspect it would be too much for what you want to achieve. I wasn't aware of this so please take my apology for getting this only now.
Lately we developed a docker based cluster that runs and connects all the breez backend components on simnet and let you connect from mobile or other devices. The docs are here (https://github.com/breez/breezmobile/wiki/Running-Breez-in-simnet).
There are other options to run Breez and I can help you choose the right one. You can contact me on Telegram directly for any question (@roeierez).

**Comment by mcroad** [comment]
This is not on testnet. I cloned the latest `master`, built it, and pointed it to the `bb1.breez.technology` server. I would have expected it to work. To be fair, this is recent. When I started working on #464, this was not an issue.

**Comment by roeierez** [comment]
@mcroad I Understand now. Can you DM me on telegram? I think we can sort things a lot faster there and setup your mainnet environment.

**Comment by kingonly** [comment]
@mcroad Can we close?
