### ISSUE TITLE
Breez requires you to keep too many sats in your balance

### ISSUE THREAD

**Issue by hup121010** [breez/breezmobile#471]
I tried to make a payment the other day, thinking I had more than enough funds available, but I was blocked by a message saying, "Breez requires you to keep 59000 sats in your balance."

That's like $30 USD sitting in my wallet completely unusable! :(

1. Why is this amount so high?
2. What happens if I ever stop using Breez Wallet? Are these funds just going to be lost?

**Comment by kingonly** [comment]
This is an old bug for relatively large channels that was fixed a while ago.
This applies here as well: https://github.com/breez/breezmobile/wiki/What's-the-deal-with-the-600-sats%3F
