### ISSUE TITLE
Overall balance is off

### ISSUE THREAD

**Issue by lschmierer** [breez/breezmobile#474]
I can not reproduce the stated balance given the individual transaction amounts.

The following screenshot shows all transactions of the wallet.

Manually adding all of the transactions together (`in amounts - out amounts - out fees`) adds up to 0.00042911 instead of 0.00042909 as reported by Brezel Wallet. (off by 3 Satoshi)

![IMG_1513](https://user-images.githubusercontent.com/2204708/117536053-44bebb00-aff9-11eb-8337-b24389bca4f8.PNG)

**Comment by kingonly** [comment]
Maybe millisats rounding in the display UI (UI doesn't show millisats). Balance should be the same as channelbalance command in the Developers screen.

**Comment by kingonly** [comment]
@lschmierer can we close?

**Comment by lschmierer** [comment]
Sure, your explanation makes sense.
Just a little unexpected at first glance.

After additional transactions, my overall balance got closer to the value I obtained by adding the transactions manually (only off by 2 sats now).

I do not see how this could be improved without showing exact millisats to the user.
Howerver, I think showing millisats would have a much worse UX than having an overall balance being off by a few sats.

**Comment by kingonly** [comment]
I agree 👍
