### ISSUE TITLE
Can't pull down dependency packages with flutter pub get

### ISSUE THREAD

**Issue by lukevenediger** [breez/breezmobile#475]
Hi, I'm trying to set up the Breeze Mobile app and am getting stuck trying to pull the dependencies down with flutter pub get

### Flutter Doctor

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel beta, 2.2.0-10.3.pre, on Linux, locale en_ZA.UTF-8)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 3.6)
> [✓] Connected device (1 available)
> 
> • No issues found!

### Issue

Running flutter pub get results in the following:

```bash
$ flutter pub get
Because every version of flutter_test from sdk depends on test_api 0.3.0 and mockito >=4.1.2 <=5.0.0-nullsafety.7 depends on test_api ^0.2.19-nullsafety, flutter_test from sdk is incompatible with mockito >=4.1.2 <=5.0.0-nullsafety.7.
So, because breez depends on both mockito 4.1.3 and flutter_test any from sdk, version solving failed.
Running "flutter pub get" in breezmobile...                             
pub get failed (1; So, because breez depends on both mockito 4.1.3 and flutter_test any from sdk, version solving failed.)
```

And with better formatting:

> flutter pub get
> Because every version of flutter_test from sdk depends on test_api 0.3.0 and mockito >=4.1.2 <=5.0.0-nullsafety.7 depends on test_api ^0.2.19-nullsafety, flutter_test from sdk is incompatible with mockito >=4.1.2 <=5.0.0-nullsafety.7.
> So, because breez depends on both mockito 4.1.3 and flutter_test any from sdk, version solving failed.
> Running "flutter pub get" in breezmobile...                             
> pub get failed (1; So, because breez depends on both mockito 4.1.3 and flutter_test any from sdk, version solving failed.)

Am I doing something wrong? Or on the wrong branch? Thanks!

**Comment by roeierez** [comment]
He @lukevenediger Your are OK, it is just that we moved to flutter stable channel and didn't update our readme...
I just updated the readme. Please run:

```
flutter channel stable
flutter upgrade
```

And then try again, let me know if it fixed your issue.

**Comment by lukevenediger** [comment]
This works
