### ISSUE TITLE
Implement AOPP Support

### ISSUE THREAD

**Issue by lclc** [breez/breezmobile#477]
AOPP (Address Ownership Proof Protocol) is a new, simple protocol that specifies the transmission of signed messages via a URI scheme: https://gitlab.com/aopp/address-ownership-proof-protocol

Providing proof of ownership over an address is required to withdrawal Bitcoin in some countries (Switzerland, the Netherlands, Singapore). It's a hassle to do that manually for the user and the exchange. AOPP heavily improves that. See [aopp.group](https://aopp.group/) for more information about it.

Besides improving the UX for the user, there are two more benefits:

1. There is no need to copy & paste a Bitcoin address for the wallet to the exchange to withdraw. This prevents malware from replacing it in the clipboard (e.g. https://www.fortinet.com/blog/threat-research/vipersoftx-new-javascript-threat)
1. The wallet is aware that the user is withdrawing from an exchange (even which exchange) and with that can suggest other options, which might be better for his privacy, provide better fees or better technology (e.g. segwit support, etc.).

AOPP does not affect and is not even visible to users of exchanges who don't have AOPP (don't require ownership proof).

Since Breez already supports URI handling for bitcoin: and the signing of messages, implementing AOPP is probably straightforward.

BlueWallet (which also has both) implement AOPP support in less than a day (BlueWallet/BlueWallet#2915).

Here you can find a demo video of AOPP with Electrum: https://www.youtube.com/watch?v=heP-ufUke-g

and one with BlueWallet and pocketbitcoin.com: https://user-images.githubusercontent.com/39227503/113781661-4dd61700-9731-11eb-849e-86e2ecf13a74.mp4

**Comment by kingonly** [comment]
Breez isn't an on-chain wallet. Adding funds is done via submarine swap, so this might be more challenging to implement than in a typical on-chain wallet.

**Comment by kingonly** [comment]
Won't implement for now
