### ISSUE TITLE
Build error while trying to start client: Exception: Unsupported Android Plugin version: 4.2.0.

### ISSUE THREAD

**Issue by lukevenediger** [breez/breezmobile#478]
Hi, I'm unable to launch the app on an emulator. I get the following error when trying to launch from Visual Studio code:

```
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
lib/main.dart:1
3
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Exception: Unsupported Android Plugin version: 4.2.0.
Exited (sigterm)
```

Any idea on what it could be?

**Comment by roeierez** [comment]
Hi @lukevenediger I think it means there could be incompatibility with the gradle version.
Can you make sure your settings for the project are using gradle 6.8 ?
You can verify that by having the following line In gradle-wrapper.properties:
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.8-bin.zip`

Also in android/build.gradle make sure you have the following line in the dependencies:
`classpath 'com.android.tools.build:gradle:4.2.0-beta03'`

**Comment by lukevenediger** [comment]
I'll check that out - thank you!

**Comment by lukevenediger** [comment]
Seems to be the same issue @roeierez - I'm getting the same error message.

Here's my gradle-wrapper.properties file:

```properties
#Thu Jan 21 12:21:38 IST 2021
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.8-bin.zip
```

And here's my build.gradle:

```gradle
buildscript {
    repositories {
        google()
        maven {
            url "https://maven.google.com"
        }
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.0-beta03'
        classpath 'com.google.gms:google-services:4.2.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        flatDir {
        dirs 'libs'
      }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by lukevenediger** [comment]
Strangely, if I launch from the terminal using ```flutter run --flavor=client --target=lib/main.dart``` then the app starts up just fine. So I've added a run configuration for this and will see how it goes. Strange!

**Comment by kingonly** [comment]
@lukevenediger close?

**Comment by lukevenediger** [comment]
Yep, happy to close - thanks @kingonly

**Comment by logicabooleana** [comment]
But what was the solution?

**Comment by logicabooleana** [comment]
@lukevenediger  But what was the solution? estoy teniendo el mismo error

**Comment by logicabooleana** [comment]
@lukevenediger  But what was the solution? I am having the same error
