### ISSUE TITLE
Add .aar file in github releases

### ISSUE THREAD

**Issue by emanuelb** [breez/breezmobile#479]
Add the .aar file used in the build of android app in github releases of this repo:
https://github.com/breez/breezmobile/releases

or maybe also in breez repo (latest is 0.5.8-openbeta from Apr 21, 2019) while latest commit in this repo is from: May 13, 2021
https://github.com/breez/breez/releases

Thus will enable easier building of the app (no need to compile breez.aar as there a precompiled file to download) and also helpful for reproducible-builds verification, as there is a file to compare against, publishing the commit which used to build the file used in the version (or using matched tag) is also needed.

**Comment by kingonly** [comment]
Added.
@emanuelb I wonder if in light of your latest findings we can get an updated status in the wallet scrutiny site.
