### ISSUE TITLE
Error running Breez in Simnet

### ISSUE THREAD

**Issue by jsebastianms1** [breez/breezmobile#484]
Hello! im trying to run Breez in simnet (https://github.com/breez/breezmobile/wiki/Running-Breez-in-simnet), i followed the steps, using 0.0.0.0 as DEV_HOST_IP 

When i try to run the start-dev-env-sh i always have the same error: 

Creating dev-alice                         ... done
-breez_server: Bind for 0.0.0.0:50053 failed: port is already allocated

ERROR: for dev-breez_server  Cannot start service dev-breez_server: driver failed programming external connectivity on endpoint dev-breez_server: Bind for 0.0.0.0:50053 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

Checking at the https://github.com/breez/breez/blob/master/docker/dev-simnet.yml dev-breez_server and dev-alice allocate this port, so changing it in one or another is a plausible solution or is there something else that im not seeing?

@kingonly 
@roeierez 

Thanks a lot if you can reply

**Comment by yaslama** [comment]
@jsebastianms1 Can you check if there is already a service listening on the port 50053? Depending on the OS you use, you can run `ss -lpn` or `netstat -a` to have a list of all the services listening on each port. But in any case, you can change the port in the docker configuration file

**Comment by jsebastianms1** [comment]
Thanks a lot, solved my doubt

**Comment by kingonly** [comment]
Is this resolved? Can we close?

**Comment by jsebastianms1** [comment]
I have another question, server is running OK, going through the next steps is really easy, but when i try to follow: 
- From your mobile app, generate a payment request via Receive> Receive via Invoice. 
I have the following error in my app log, i can see that the blockheight is correct, but when i try to do something like generating a payment request, it says that im not authorized

I/GoLog   ( 2684): 2021-05-26 14:41:15.869 [INF] DAEM: Sync to chain interval Synced=false BlockHeight=418
I/GoLog   ( 2684): 2021-05-26 14:41:15.915 [INF] CLIENT: getBreezClientConnection - before Ping;
I/GoLog   ( 2684): 2021-05-26 14:41:15.919 [INF] CLIENT: getBreezClientConnection - after Ping; err: rpc error: code = PermissionDenied desc = Not authorized
E/BREEZUI ( 2684): Error in method rate: rpc error: code = PermissionDenied desc = Not authorized
E/BREEZUI ( 2684): go.Universe$proxyerror: rpc error: code = PermissionDenied desc = Not authorized

Im using Android Emulator in a mac, and i use breezserver=10.0.2.2:50053 and peer=10.0.2.2:18555 in my breez.conf (10.0.2.2 because it's an alias to my host loopback interface.

Hope you can guide me through this, thanks a lot!

**Comment by jsebastianms1** [comment]
The only thing i could find looking at https://github.com/breez/breez/blob/master/docker/start-dev-env.sh is that here we say that 
export BTCD_HOST="127.0.0.1:18556"

and in https://github.com/breez/breez/blob/ca1971dee5a03c4c01f603451c0efd452485f4c7/docker/dev-simnet.yml
we use  ports:      - ${DEV_HOST_IP}:18555:18555 on  dev-btcd service

**Comment by roeierez** [comment]
> I have another question, server is running OK, going through the next steps is really easy, but when i try to follow:
> 
> * From your mobile app, generate a payment request via Receive> Receive via Invoice.
>   I have the following error in my app log, i can see that the blockheight is correct, but when i try to do something like generating a payment request, it says that im not authorized
> 
> I/GoLog ( 2684): 2021-05-26 14:41:15.869 [INF] DAEM: Sync to chain interval Synced=false BlockHeight=418
> I/GoLog ( 2684): 2021-05-26 14:41:15.915 [INF] CLIENT: getBreezClientConnection - before Ping;
> I/GoLog ( 2684): 2021-05-26 14:41:15.919 [INF] CLIENT: getBreezClientConnection - after Ping; err: rpc error: code = PermissionDenied desc = Not authorized
> E/BREEZUI ( 2684): Error in method rate: rpc error: code = PermissionDenied desc = Not authorized
> E/BREEZUI ( 2684): go.Universe$proxyerror: rpc error: code = PermissionDenied desc = Not authorized
> 
> Im using Android Emulator in a mac, and i use breezserver=10.0.2.2:50053 and peer=10.0.2.2:18555 in my breez.conf (10.0.2.2 because it's an alias to my host loopback interface).
> 
> Hope you can guide me through this, thanks a lot!

Hi, it looks like you made a real progress and next thing to solve is the grpc connection to breez server.
Can you attach the breez conf file that you are using?

**Comment by kingonly** [comment]
What's the status here?

**Comment by kingonly** [comment]
@jsebastianms1 what's the status of this issue? Can we close?

**Comment by jsebastianms1** [comment]
@kingonly you can close it, thanks a lot
