### ISSUE TITLE
Can not send from Breez to other Breez user

### ISSUE THREAD

**Issue by Kixunil** [breez/breezmobile#488]
I was unable to send from Breez to another (new) Breez user.

Steps attempted:

0. User installed the wallet
1. Send sats from Breez to Breez - failed
2. Send sats to Breez of the new user - succeeded, the channel was created
3. Send 1 sat from new user to a non-breez node - succeeded
4. Send 1 sat from old user to a non-breez node - succeeded
5. Send 1 sat from old user to the new user - failed

**Comment by kingonly** [comment]
What's the difference between step #1 and #2?

**Comment by Kixunil** [comment]
sorry for unclear description, in step 2 it was sent from a non-breez node.

**Comment by kingonly** [comment]
So it always failed to send from the same old Breez to the new Breez. I'm wondering whether a different Breez would've worked. We don't have anything that prevents it from happening and we probably need to reproduce in this specific environment.

**Comment by Kixunil** [comment]
I will ask a friend who's using Breez to try. You can also paste a 1-sat invoice and I will try to pay it.

**Comment by Kixunil** [comment]
Now it started working. I sent part of the sats somewhere else and then tried transactions to a friend and to the new user and both succeeded. Not sure if there's anything actionable. I have agreed to send debug info to Breez before, when it failed, so I guess that's the only lead now.

**Comment by kingonly** [comment]
That wouldn't be enough to track it down.
The failure report only send the dest node which allows us to see if there are liquidity issues. In this case, it's definitely not a liquidity issue and probably need to be debugged in real time.

**Comment by kingonly** [comment]
After looking into a few similar reports, this issue seems to stem from lnd mc blacklisting the private channel between Breez hub and mobile node. We're looking to see what can be done to mitigate it.

**Comment by kingonly** [comment]
https://github.com/lightningnetwork/lnd/issues/5544

**Comment by Kixunil** [comment]
Awesome that you found it!

**Comment by NorrinRadd** [comment]
Should this still be open?

**Comment by kingonly** [comment]
Yes, there's a fix committed in the master that wasn't published yet

**Comment by kingonly** [comment]
Fix was published in the latest version, please reopen if needed
