### ISSUE TITLE
Encryption key is excessively long

### ISSUE THREAD

**Issue by Kixunil** [breez/breezmobile#489]
The encryption key (AKA seed) uses 24 words which is 256 bits of security. This is excessive as Bitcoin keys themselves only have 128 bits of entropy (256 bit elliptic curve key doesn't mean 256 bits of entropy) and leads to worse UX - having to write twice as much words.

The reason 24 word seeds are even a thing is that the recovery procedure on some HW wallets (Trezor One) needs to be protected by mixing up words - so it's 12! combinations vs 24!. This does not apply to mobile wallets and even newer HW wallets (Trezor T) offer 12-word seeds when they achieve protection differently.

**Comment by yaslama** [comment]
@Kixunil You are right. Reducing the number of words can improve the UX without impacting the security.

**Comment by kingonly** [comment]
Published
