### ISSUE TITLE
[Podcast] Sleep Timer

### ISSUE THREAD

**Issue by MaxHillebrand** [breez/breezmobile#492]
You'll be poor quickly when you fall a sleep listening to a long podcast while streaming sats/minute...

Sleep timer is especially useful when making payments!

**Comment by kingonly** [comment]
Added in the latest update

**Comment by MaxHillebrand** [comment]
tested ACK, thank you kindly!

[the new boostagram screen with custom amount is great too]

**Comment by MaxHillebrand** [comment]
should there maybe be a countdown of when the sleep kicks in? 
Not sure if this is useful, it would clutter UI...

**Comment by kingonly** [comment]
We went with a clean, Spotify-like design
