### ISSUE TITLE
Android API

### ISSUE THREAD

**Issue by ueen** [breez/breezmobile#507]
Hey, I'm collaborating on AntennaPod and was wondering if there is like an API or something, that could trigger podcast value payments through the breeze android app from another podcast app?

**Comment by kingonly** [comment]
Not really... Breez is a client side app and unfortunately there's no way to interop between two Android apps that would allow you to stream payments, but we're open to explore it if you have something in mind.
Best would be to contact me directly at roys@breez.technology and close this issue...

**Comment by ueen** [comment]
Hey, thanks for the quick reply! 
I was thinking, maybe sending intents and breez starts a foreground service (with a notification) that then handles the payment, I didn't try anything like this before but I'm sort of feeling like that could work, there's an app that does that somewhat similarly
https://github.com/tengusw/share_to_clipboard
It receives an intent from the share menu and then starts a foreground service/notification to handle the copy to clipboard.
