### ISSUE TITLE
Offline Podcast listening

### ISSUE THREAD

**Issue by MaxHillebrand** [breez/breezmobile#508]
One of the benefits of podcasting is that the whole episode can be downloaded in advance, and then listened to later, especially when offline.

Already now Breez allows to download the podcast file. 

However, when then later the phone is offline, Breez will not start properly, as the lightning node obviously only works with internet connection.

Would it be possible, to enable offline podcasting functionality, so that breez opens in the podcast view, and then allows to play downloaded podcasts?

Of course vlaue4value streaming is not possible offline, but maybe there could be a local counter remembering how many sats to send where, which are then sent off when the phone is back online later.

I think offline podcast listening is a required feature for any decent podcast app, and it's currently blocking me from moving to Breez as my main podcatcher app.

**Comment by kingonly** [comment]
We changed the 'Exit' in the dialog to  'Cancel'  to allow you to listen to podcasts offline.

**Comment by bitcoinuser** [comment]
Duplicate of this? https://github.com/breez/breezmobile/issues/459

**Comment by MaxHillebrand** [comment]
Sorry for the duplicate issue - and thanks that it's already implemented!! :fire: :rocket: :black_heart:
