### ISSUE TITLE
Breez fails to pick up lnurl-withdrawl from clipboard or when pasted into 

### ISSUE THREAD

**Issue by Liongrass** [breez/breezmobile#511]
REPRO:
1) I copy a lnurl
2) I open Breez 0.11 (4261.1) on iOS 14.6
3) See the notice "Breez pasted from ..."

EXPECTED:
Breez picks up the lnurl in the clipboard and opens the usual dialogue

ACTUAL:
No reaction from Breez

REPRO:
4) Go to 'Send' -> 'Paste Invoice or Node ID'
5) Paste the lnurl from the clipboard into the field
6) Click 'Approve'

EXPECTED
Breez picks up the lnurl in the field and opens the usual dialogue

ACTUAL:
Error message: "Invalid invoice or node ID"

Thank you for all your work!

**Comment by kingonly** [comment]
Fixed in latest, package is rolling out today.
