### ISSUE TITLE
Lightning funds aren't added when using Bitcoin address twice

### ISSUE THREAD

**Issue by johanf85** [breez/breezmobile#514]
I've been using the Breez wallet on my Android device, android version 7.0.

I first added funds to my Lightning wallet by sending an amount of bitcoin to an on chain address from a bitcoin exchange. This worked. However when a couple of days later I sent money to the same btc address, the funds weren't added to my wallet (it is has been more than two weeks now) and the transaction is stated as confirmed in the blockchain info.

I didn't bother generating a new address because I had to verify that address again at my exchange, just figured would be okay that the same address can be used twice, just like normal on chain transactions.

This is information from my Bitcoin exchange platform for the transactions:

![](https://user-images.githubusercontent.com/43075793/123789025-fe8d2600-d8dc-11eb-8213-94533d8bfabf.jpg)

![](https://user-images.githubusercontent.com/43075793/123788803-ba018a80-d8dc-11eb-978c-6bca290196aa.jpg)

Here is a screenshot of my wallet:

![](https://user-images.githubusercontent.com/43075793/123789606-a4409500-d8dd-11eb-8ded-8234c153d99e.png)

I am a bit afraid of reinstalling the wallet, as I am not sure if my funds will be lost. I did backup the wallet via Google Drive. 

It is possible to use a btc address to receive funds twice right? Is there a fix?

**Comment by kingonly** [comment]
Do NOT uninstall Breez.
You'll be refunded via Breez. See: https://github.com/breez/breezmobile/wiki/Adding-Funds-via-Submarine-Swaps

Use on-chain addresses only once.

**Comment by kingonly** [comment]
Please email us to contact@breez.technology to drill into the specifics of this case.
