### ISSUE TITLE
iOS build fails with "No such module bindings"

### ISSUE THREAD

**Issue by NorrinRadd** [breez/breezmobile#522]
GoMobile produces xcframeworks now, instead of fat frameworks.
https://github.com/golang/mobile/pull/65

Xcode is not finding  the necessary static library with the new xcframework format.

Procedure
===
Build with iOS simulator target

Observed Behavior
===

Showing All Issues
CompileSwift normal x86_64 ~/code/breezmobile/ios/Plugins/Breez/BreezLib/iCloudBackupProvider.swift (in target 'Runner' from project 'Runner')
    cd ~/code/breezmobile/ios

~/code/breezmobile/ios/Plugins/Breez/BreezLib/iCloudBackupProvider.swift:11:8: error: no such module 'Bindings'
import Bindings
       ^

Expected Behavior
===
Successful iOS  build

**Comment by kingonly** [comment]
Fixed
