### ISSUE TITLE
[Podcast] Allow for boost messages

### ISSUE THREAD

**Issue by AbelLykens** [breez/breezmobile#524]
The TLV record supports messages with boosts. 

My dream: a longpress on boost creates a popup where I can set a one time boost amount, and enter a message.

Hope you can consider it.

GO PODCASTING!

**Comment by kingonly** [comment]
Why set the amount on long press? Just a message seems simpler and more streamlined.

**Comment by AbelLykens** [comment]
True. Was thinking that for messaged boosts, I might do one-time larger payments. So that's easier than +++++++ing before doing the boost, then -------'ing again ;)

**Comment by kingonly** [comment]
You don't have to use the +/-. You can change the amount by clicking on it.

**Comment by AbelLykens** [comment]
Okay skip that requirement then. TIL. Cheers.

**Comment by MaxHillebrand** [comment]
Consider it a bump in the feature request :) 
Notice custom amount is discussed in #466.

**Comment by kingonly** [comment]
Added boostagram support in the latest update

**Comment by MaxHillebrand** [comment]
Y'all are rockstars! 
Thanks @kingonly

**Comment by kingonly** [comment]
Last update caused a regression in the "regular" boost. We'll fix soon.

**Comment by kingonly** [comment]
I updated the APK: https://github.com/breez/breezmobile/wiki/Can-I-download-Breez-APK%3F

Btw, we're adding an amount field to the Boostagram dialog to allow a bit much flexibility.

**Comment by MaxHillebrand** [comment]
tested latest update, it works well! 

Yes, changing amount while writing the text would be useful.
