### ISSUE TITLE
Suggestion: Add Curacao fiat currency to #373

### ISSUE THREAD

**Issue by wksantiago** [breez/breezmobile#525]
The POS mode is pretty awesome, there is a lot of people asking me how to receive LN the "easy" way, this is one of the easiest way for a merchant.

I received this kind of questions from mechants from Curacao, the problem is there is no Curacao fiat currency

Use the api from this site which have the free market fiat currencies rate.

https://yadio.io/api.html

Can we add the Curacao Guilder?

https://api.yadio.io/rate/ANG

The usd field in each endpoint is the pair rate ANGUSD

**Comment by kingonly** [comment]
We'll take a look

**Comment by wksantiago** [comment]
Thanks

**Comment by yaslama** [comment]
@wksantiago we just added ANG

**Comment by wksantiago** [comment]
Awesome just realized it, thanks you guys are my heroes :-)

I will close the issue.

Thanks,

William K. Santiago
***@***.******@***.***)

[Website](https://privkey.io/) | [LinkedIn](https://www.linkedin.com/in/wksantiago/) | [Twitter](https://twitter.com/WilliamSantiago)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
