### ISSUE TITLE
Selected File isn't a valid CSV file when importing POS Items List

### ISSUE THREAD

**Issue by wksantiago** [breez/breezmobile#526]
On Android Mobile.

When importing POS Items List from Google drive I get the following:

"Selected File isn't a valid CSV file when importing POS Items List" OK

**Comment by kingonly** [comment]
I just tried it and it works from Google Drive.
Try to export and then import the same file.

**Comment by wksantiago** [comment]
I tried the import on a different mobile (Pixel 4a) and it worked.

The other mobile is a Samsung (SM-A207M)

**Comment by kingonly** [comment]
This problem is unlikely to be related to Breez.
The file was changed during the process somehow.
Try to export and import using another method.

**Comment by wksantiago** [comment]
With the new mobile after the import any changes to the file, like adding new items or changing the price, are not reflected after the successful import.

**Comment by kingonly** [comment]
So they weren't added to the file correctly...
Let's continue this via email.
Send us the file to contact@breez.technology
