### ISSUE TITLE
Text overflow in LNURL Pay purchase information window

### ISSUE THREAD

**Issue by rkfg** [breez/breezmobile#531]
![Screenshot_20210719-103110](https://user-images.githubusercontent.com/184066/126120693-df0d3253-2d02-46b0-886c-50fc30864888.png)

**Comment by kingonly** [comment]
What's the service?

**Comment by rkfg** [comment]
https://crawly.org.es/ here, the codes are at the bottom

**Comment by rkfg** [comment]
There's no information for the "free quantity" payment but there is for the 2000 one. I tried it in the debug version I built myself yesterday:
![Screenshot_20210719-122542](https://user-images.githubusercontent.com/184066/126137468-4a2afbda-1fb0-4d13-b725-34718a5f5bc7.png)

**Comment by kingonly** [comment]
Thanks! We'll get that fixes ASAP.

**Comment by kingonly** [comment]
Can you please check the master branch and let us know how it looks on your end?

**Comment by rkfg** [comment]
Thanks, now it all fits nicely!
