### ISSUE TITLE
LNURL Pay doesn't work on zbd.gg

### ISSUE THREAD

**Issue by rkfg** [breez/breezmobile#536]
Example: https://zbd.gg/BITC0IN
On scanning Breez says "Link Error; Failed to process link: unknown response tag"

**Comment by kingonly** [comment]
We've tested Zebedee many times and this linked also just worked for me. Maybe a temporary issue on the server end?

**Comment by nochiel** [comment]
>> On scanning Breez says "Link Error; Failed to process link: unknown response tag"

> We've tested Zebedee many times and this link also just worked for me. Maybe a temporary issue on the server end?

This also works for me.

NB. Possibly unrelated if the qr-code is successfully scanned.
Re: https://github.com/breez/breezmobile/pull/518
To test zbd.gg I had to [upgrade qr_code_tools' zxing dependency](https://github.com/AifeiI/qr_code_tools/pull/9).

**Comment by kingonly** [comment]
Please make sure to test in production build before opening issues

**Comment by rkfg** [comment]
I tested it in production build. It seems that zbd.gg blocks some IPs from their side, I get `403 Forbidden` when accessing it without VPN (which is what my phone does). However, it works fine on my PC that uses VPN, hence the issue. After I enabled VPN on the phone too it worked. Sorry for confusion!

**Comment by rkfg** [comment]
In case anyone gets this issue in the future, looks like zbd.gg blocks _at least_ Russian and Ukrainian IPs for whatever reason. Weird and sad.

**Comment by kingonly** [comment]
Can you tweet it? Interesting to see their response.

**Comment by rkfg** [comment]
Yeah, I'll try.

**Comment by rkfg** [comment]
Surprisingly, they only allow Bitcoin payments [in certain countries](https://zebedee.io/countries/):
![2021-07-21_23-43-06](https://user-images.githubusercontent.com/184066/126557495-bb3001fa-588c-4714-92f5-c53237a04766.png)

First time I see something like that. For fiat it would be fully understandable but not for Bitcoin.

**Comment by kingonly** [comment]
Well, it's a custodial service working closely with bitstamp so I'm not surprised.
