### ISSUE TITLE
[Feature request] Prefill LNURL Pay amount

### ISSUE THREAD

**Issue by rkfg** [breez/breezmobile#539]
I think it would be useful to automatically set the amount in LNURL payments if the min amount equals max amount. You're not supposed to enter anything else there anyway!
![Screenshot_20210722-112937](https://user-images.githubusercontent.com/184066/126610588-6feb862f-8775-4878-9f68-5fe7135f8e53.png)
For example, on https://chat.blixtwallet.com/ you can post a message for 10 sats exactly and you have to enter 10 in the amount field. Entering 9 and less or 11 and more doesn't work obviously so there's no reason to bother the user.

**Comment by kingonly** [comment]
Good suggestion!
