### ISSUE TITLE
Default to FaceID on iOS

### ISSUE THREAD

**Issue by shawnyeager** [breez/breezmobile#544]
I've found that almost always (but with unpredictably few exceptions) Breez presents me with the PIN entry screen by default, rather than attempt FaceID.

**Comment by kingonly** [comment]
I assume that biometrics is set but doesn't work consistently. Which iOS model? Can you please share a video?

**Comment by shawnyeager** [comment]
It's set, yes.

To complicate matters, I just rebooted my iPhone 11 after installing iOS 14.7.1, and now FaceID is working consistently with Breez. Whether it's the iOS upgrade, I can't say. 

Also, I did install build 4347.1 yesterday to test (via Roei) due to my phone running hot while streaming.

**Comment by kingonly** [comment]
If it's working on the latest iOS update, I recommend closing for now (users must run the latest updates).
Feel free to reopen if needed.
