### ISSUE TITLE
[bug] Playback doesn't resume when new audio source starts then stop

### ISSUE THREAD

**Issue by neb-b** [breez/breezmobile#547]
Happening to me on iOS

To reproduce:

1. Start podcast
2. Start a video somewhere (I started watching one on Twitter)
3. Stop video
4. Podcast doesn't start playing

The current time in the app continues to move forward after I stop the other media source, but there is no audio. When I press "pause", then "start" the podcast jumps back x seconds to start when it should have.

**Comment by erdemyerebasmaz** [comment]
> 4. Podcast doesn't start playing

This behavior is normal, continuous playback has been disabled on almost on fronts in the industry. Same behavior can be examined on iOS's Podcast app, YouTube etc. or your browser.

> The current time in the app continues to move forward after I stop the other media source, but there is no audio.

This bug is no longer examined, closing.
