### ISSUE TITLE
[Idea] Private App Icon

### ISSUE THREAD

**Issue by exitfiat** [breez/breezmobile#548]
Just got the inspiration for a good feature in theory.
Add the option to change the app icon and name to something non money related. Like Calculator or Notes. The Pornhub app already has this option for example.
This could help woman with evil husbands, people in countries where bitcoin is illegal, children with bad parents etc...

**Comment by kingonly** [comment]
There are external apps that allow you to do that, but this isn't something we plan to provide (also supposably not aligned with app stores guidelines).
