### ISSUE TITLE
Question: How can I view details about a payment failure? 

### ISSUE THREAD

**Issue by fresheneesz** [breez/breezmobile#550]
It would be nice for there to be a way to toggle visibility of failed payments and a way to view more detailed information about why those payments failed. I recently had a number of attempts where payments from Breez to a Phoenix wallet failed. A few of them failed after a timeout (with a brief toast message telling me), and another went into "pending" state and then failed for some other reason. Once these messages are gone, I don't see any way to go back to that information. It would help me understand if its something that is my fault, a temporary problem with the network, or a potential bug I should report.

**Comment by kingonly** [comment]
These are most likely temporary Lightning Network issues and the information is in our logs. Breez to Phoenix payments aren't very reliable because they don't rebalance our channels and because the two apps are non-custodial and need to be active to send or receive.

You can also try: https://github.com/breez/breezmobile/wiki/Troubleshooting-Payment-Failures

**Comment by fresheneesz** [comment]
Thanks. When you say "our logs", is that something I can access? Given that you closed this, I assume you don't think it would be a worthwhile feature to give users an easier ability to look back at payment failures?

**Comment by kingonly** [comment]
Logs can be accessed via:
Preferences> Developers screen> top right menu> Share Logs

Yes, troubleshooting payment failures isn't a typical end user action in our mind, so providing a UI for it is a bit much... Our logs and our payment failure reports cover our needs.

Btw, even with the logs, troubleshooting these failures are far from easy...

**Comment by fresheneesz** [comment]
I see, thanks
