### ISSUE TITLE
LNURL pay generator or guide

### ISSUE THREAD

**Issue by iBobik** [breez/breezmobile#551]
> As a merchant I want to have paper backup of my POS, because phone with Breez app could not be available always, so I can receive payments to Breez at least with a printed QR code prepared for such cases.

In on-chain ages merchants were able to print QR code with a receiving address, in LN age we can use static LNURL pay/donate QR code. This QR code could have or have not specified amount. It should receive payments directly to their Breez wallet, without need for running LNbits or BtcPay server or having some other wallet in some custodial service.

In an app there could be generator for such URL or QR code, but it will be **totally ok to solve this need just by a guide in a wiki**, so app does need to be bloated by this. Guide should be understandable for people without LN knowledge. They should start with installed Breez and end with QR code ready to be printed.

**Comment by kingonly** [comment]
Generating LNURL-Pay requires running an always online web server. It also doesn't fit mobile nodes which are mostly offline. Not sure what's the issue here.

**Comment by iBobik** [comment]
So to solve this need (of real merchants I work with) Breez would need to
run some service (webserver and forwarding online wallet). Is there a will?


Honza Pobořil


11. 8. 2021 3:10:39, kingonly ***@***.***> napsal:

**Comment by kingonly** [comment]
Nope. This is completely out of scope for us. Breez will remain a non-custodial service.
We're looking at bolt12, which would provide similar capabilities inherent to LN.

**Comment by iBobik** [comment]
Could you please focus on the last paragraph of issue decription? It could be solved by an docs.

**Comment by kingonly** [comment]
What do you mean "can be solved by the doc"? How exactly?
