### ISSUE TITLE
Add ability to use testnet network

### ISSUE THREAD

**Issue by Bosch-0** [breez/breezmobile#557]
Heya,

I'm from the [Bitcoin Design community](https://bitcoin.design/) and we are major fans of your applications UX - it really is pushing the industry forward and making LN much more accessible! 

One thing that would really help us designers experiment with your app, learn more about its inner workings and thus help us improve the overall UX of Bitcoin/LN alongside Breez would be the ability to run Breez in testnet mode (ideally buried in an advanced settings area as to not have noobs accidentally switch networks).

**Comment by kingonly** [comment]
We've had a testnet version when we've started, but our environment we weren't able to keep maintaining or developing it. We do offer a simnet environment https://github.com/breez/breezmobile/wiki/Running-Breez-in-simnet.
