### ISSUE TITLE
When Breez stay closed for a long time,  creating an invoice, the popup close automatically before show qrcode

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#561]
Hi,

When Breez stay closed for a long time,  creating an invoice, the popup close automatically before show qrcode. So the user needs to proceed with creating an invoice more than one time.

OS: Android.

**Comment by kingonly** [comment]
I think the app just closes.

**Comment by tlindi** [comment]
It is now showing "Syncing" instead of closing while creating invoice. At least on PoS with. Isn't it?

**Comment by erdemyerebasmaz** [comment]
> It is now showing "Syncing" instead of closing while creating invoice. At least on PoS with. Isn't it?
Yes and this is true for "Receive via Invoice" as well.

Tested with a node that was not synced for a long time, can't reproduce. Closing.
