### ISSUE TITLE
[Podcast] Share Soundbite Clip

### ISSUE THREAD

**Issue by MaxHillebrand** [breez/breezmobile#569]
It would be great if the listener can create a soundbite with a certain starting / endpoint, and then share this directly to social media.

Not sure how this functionality should be best implemented, maybe cut out from the downloaded mp3/mp4?

There is also the `Soundbite` namespace tag, and some applications like Hypercatcher and Fountain already support this.

**Comment by kingonly** [comment]
Added to latest
