### ISSUE TITLE
Verify Backup Password, add Checkmarks

### ISSUE THREAD

**Issue by MaxHillebrand** [breez/breezmobile#573]
Currently, in the verification of the backup encryption password, the user needs to type in 3 randomly selected words.

After typing a word, there is no indication if it is correct or wrong.

Instead, please add a checkmark or error icon after a word is typed, to indicate right away if that word is good or not.

**Comment by kingonly** [comment]
Giving an error after one word allows users to exclude that word.  Giving an error after 3 words is a bit safer in that regard.

**Comment by MaxHillebrand** [comment]
> allows users to exclude that word

I don't understand.

**Comment by kingonly** [comment]
If you give users indication per word, they can guess better what was their mistake. If you give error on 3 words, less chances they would use their memory.

When we've implemented (back in the day), we've look at multiple wallet designs/implementations, and this design made sense.

**Comment by MaxHillebrand** [comment]
Ah, I see.
Ok, reasonable enough.

Thanks!
