### ISSUE TITLE
Add 'breez:' deep link support

### ISSUE THREAD

**Issue by juscamarena** [breez/breezmobile#576]
It'd be nice to have deep link support, especially for iOS. Anyone with more than one lightning wallet on iOS has a hard time having the URI open the correct wallet...

Bluewallet and Muun seem to support deeplinking and it'd help the UX for wallets if Phoenix also supported this.

Examples:

https://bluewallet.io/testpage/#:~:text=Deeplinks%20prefixed,%60bluewallet%3A%60
bluewallet:bitcoin:BC1QH6TF004TY7Z7UN2V5NTU4MKF630545GVHS45U7?amount=666&label=Yo

bluewallet:lightning:lnbc10u1pwjqwkkpp5vlc3tttdzhpk9fwzkkue0sf2pumtza7qyw9vucxyyeh0yaqq66yqdq5f38z6mmwd3ujqar9wd6qcqzpgxq97zvuqrzjqvgptfurj3528snx6e3dtwepafxw5fpzdymw9pj20jj09sunnqmwqz9hx5qqtmgqqqqqqqlgqqqqqqgqjq5duu3fs9xq9vn89qk3ezwpygecu4p3n69wm3tnl28rpgn2gmk5hjaznemw0gy32wrslpn3g24khcgnpua9q04fttm2y8pnhmhhc2gncplz0zde

**Comment by kingonly** [comment]
Did you test it and it didn't work cause it we added it a long time ago...

**Comment by kingonly** [comment]
@roeierez  please confirm breez protocol is supported

**Comment by juscamarena** [comment]
Ah, perhaps it works. Apologies, I was testing out which wallets supported it and how each one owned the uri and may have not had breez installed when testing. 😅

**Comment by juscamarena** [comment]
Yes, it is indeed supported, closing!
