### ISSUE TITLE
Cache Storage on Android Grows >10GB in ~1 Month

### ISSUE THREAD

**Issue by mbiskach** [breez/breezmobile#584]
Breez Version: 0.12-beta (recently updated from previous version)
Running on stock Pixel 3a XL, Android 11
I use Breez to download podcasts, stream sats/listen, then delete episode upon completion. Looking at the app details page, downloading/deleting episodes increases/decreases User Data size as expected, while Cache increases by a small fraction. Not sure what other mechanism could slowly increase cache size over time...

**Comment by kingonly** [comment]
Thanks for the issue 🙏
We need to review our cache usage. 
Did you delete the cache or kept it? Would be interesting to see the files there.

**Comment by mbiskach** [comment]
I have not yet cleared the cache, however I do not know how to inspect contents of the cache...

Let me know what information would be useful.

**Comment by kingonly** [comment]
Would it possible to contact me on telegram? 
Might be easier to interact...
@roysheinfeld

**Comment by kingonly** [comment]
@roeierez please update

**Comment by kingonly** [comment]
Published
