### ISSUE TITLE
When open a Lnur-pay with Breez locked, show the Android keyboard

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#593]
Hi,

When open a Lnur-pay like (https://zbd.gg/leo) with Breez locked, show the Android keyboard, but shouldn't.

![photo_2021-10-12_18-56-23](https://user-images.githubusercontent.com/1178856/137034772-94f80d13-9565-42ab-b93d-c92217a2b313.jpg)

**Comment by erdemyerebasmaz** [comment]
Native keyboard was showing because the amount field was being focused behind the PIN page when the invoice was opened through a deeplink.

This does not seem to be the case anymore. Closing.
