### ISSUE TITLE
[BD] Use uppercase lettering for invoices and addresses

### ISSUE THREAD

**Issue by Bosch-0** [breez/breezmobile#595]
Breez currently uses lower cased bitcoin addresses and Lightning invoices. As [outlined here](https://bitcoinops.org/en/bech32-sending-support/#creating-more-efficient-qr-codes-with-bech32-addresses) using uppercase lettering results in more efficient QR code generation making them easier to scan. 

> In summary, when using bech32 addresses in QR codes, consider uppercasing them and any other adjacent characters that can be uppercased in order to produce smaller and less complex QR codes. (However, for all other purposes, bech32 addresses should use all lowercase characters.)

**Comment by kingonly** [comment]
@nochiel Please take a look. Only the QR should be effected.

**Comment by kingonly** [comment]
Published
