### ISSUE TITLE
Webdav backup not working for me

### ISSUE THREAD

**Issue by clayt0nk** [breez/breezmobile#596]
First I tried to backup to a Nextcloud instance on my local network. That failed because apparently Breez will not accept an IP address in place of a URL.

Then I tried to backup to a remote Webdav share. That worked once at setup time, yesterday. Today it just says "Failed to save backup files to Remote Server", with no further explanation, no change to Webdav credentials. I tried many network connection variations: mobile, broadband, multiple VPN endpoints, Tor, nothing works. Meanwhile another Webdav client on the same device can connect to the Webdav share that Breez is using at will, no problem. I can see the files that were dropped there by Breez yesterday, nothing was added today.

Local storage options would be nice.

**Comment by kingonly** [comment]
Let's handle this via our support channel since it maybe something specific to your environment.
Please send us an email to contact@breez.technology and we'll follow up with you directly.
