### ISSUE TITLE
Server Offline?

### ISSUE THREAD

**Issue by TheBlueMatt** [breez/breezmobile#601]
I currently get a 502 Error popup when I try to create a large invoice, and smaller invoices simply disappears the invoice request popup without any invoice.

**Comment by bitcoinuser** [comment]
Same here

**Comment by RealDudePerson** [comment]
Can confirm, same issue here. 

"Failed to create an invoice (rpc error: code = Unavailable desc = Bad Gateway: HTTP status code 502; transport: received the unexpected content-type "text/plain; charset=utf-8").
Please try again later."

**Comment by TheBlueMatt** [comment]
Seems to be working now.
