### ISSUE TITLE
Sent funds to the wallet but they don’t arrive

### ISSUE THREAD

**Issue by adriano-pinaffo** [breez/breezmobile#615]
I sent funds to the wallet via a BTC address and it fails with the errors in the images below. More than 20 confirmations have passed now.

First it said “Payment is in transition”
Then it said “Context deadline exceeded”

Why is this happening?
I have an iPhone X with iOS 14.6

![image](https://user-images.githubusercontent.com/28174227/139511080-f6be233e-6a18-47dc-bb47-b7c6a2eb83c4.png)

![image](https://user-images.githubusercontent.com/28174227/139511093-cfa341b3-2e6d-42f0-8f57-dca1d99bd293.png)

**Comment by mendozal** [comment]
Having the same issue

**Comment by kingonly** [comment]
Don't uninstall Breez. Wait for a refund.
Hopefully we'll be able to fix this sooner:
https://github.com/breez/breezmobile/wiki/Adding-Funds-via-Submarine-Swaps

**Comment by adriano-pinaffo** [comment]
> Don't uninstall Breez. Wait for a refund. Hopefully we'll be able to fix this sooner: https://github.com/breez/breezmobile/wiki/Adding-Funds-via-Submarine-Swaps

I joined the Telegram channel and talked to Roy there, I informed that by the time he told me not to uninstall I had already uninstalled the app, and worse... my 24 mnemonic words are not restoring my wallet. Now I can't get access to my funds. It may be the case that one of the 24 words is wrong in my case and Roy pointed me to this [issue](https://github.com/breez/breezmobile/issues/383), There,  the author managed to get the backup file from Google Drive and tried his 24 words programatically... 

@kingonly if you don't mind I would like to open a new issue (referencing that other issue) because the Google Drive backup file is not working for iPhones (at least my iPhone).

**Comment by kingonly** [comment]
Let's continue this via support.
You can contact us at contact@breez.technology.

**Comment by adriano-pinaffo** [comment]
I just noticed that I can reference that issue here.

In #383, @fresheneesz, managed to download the Google Drive backup file and run a nodejs program on the backup to recover his 24 words (in his case he confirmed he had the right words, in my case I need to test the 24 words I have noted down becausee it may be the case that one of them is wrong. The problem is, I can't download the backup file from Google Drive as he did as mine keeps "trying" (the spinner keeps rotating) and it never downloads. My device is an iPhone X, iOS 14.6.

I attached a short video of the process. Can you help me with that?

https://user-images.githubusercontent.com/28174227/139553836-063d7d95-b205-4141-b4d5-8e22a88eeb7e.mov

**Comment by kingonly** [comment]
@roeierez can you please take a look?

**Comment by adriano-pinaffo** [comment]
> @roeierez can you please take a look?

I managed to borrow an android phone and there I could download the backup.
Then I put in my PC, adapted @fresheneesz script (thank you so much for the initial work), and created my script that permutes all the 24 words for the 2000+ words in the wordlist. In a matter of seconds I found out I had mistyped one single letter but the word was still valid.

That's why I back up @fresheneesz idea that it seems to be an extremely poor design choice to use mnemonics instead of passwords.

Anyway, if anyone needs this in the future...
```
// based on the work of @fresheneesz described here: https://github.com/breez/breezmobile/issues/383

var bip39 = require('bip39')
var hex = require('convert-hex')
var crypto = require('crypto')
var fs = require('fs')

var nonceSize = 12
var tagSize = 16

// add your 24 words (the ones you think are right)
var mnemonic = [

  "word1",
  "word2",
  "word3",
  "word4",
  "word5",
  "word6",
  "word7",
  "word8",
  "word9",
  "word10",
  "word11",
  "word12",
  "word13",
  "word14",
  "word15",
  "word16",
  "word17",
  "word18",
  "word19",
  "word20",
  "word21",
  "word22",
  "word23",
  "word24",

]

// Download the wordlist by cloning the github repository.
// I had to remove the first and last lines to parse it.
var wordlist = JSON.parse('[' + fs.readFileSync("./lib/routes/security_pin/backup_phrase/wordlist.dart", 'utf-8').replace('const WORDLIST = [', '').replace('];', '') + ']')

var encryptedSourceBytes = fs.readFileSync("/home/alien/Downloads/breez/backup1/breez.db")
var decrypted = false;

var decryptRes = decrypt(encryptedSourceBytes, mnemonic.join(' '));
if (decryptRes)
  decrypted = true

// the 2 for below will permute all of the 24 words you provided
// if only one of the words is wrong, the correct sequence will be found
for (i=0; i<mnemonic.length; i++) {
  if (decrypted)
    break;
  var mnemonicCopy = [...mnemonic];
  for (j=0; j<wordlist.length; j++) {
    mnemonicCopy[i] = wordlist[j]
    var decryptRes = decrypt(encryptedSourceBytes, mnemonicCopy.join(' '));
    if (decryptRes && /account/.test(decryptRes)) {
      decrypted = true
      break;
    }
  }
}
if (decrypted)
  console.log('Found')
else
  console.log('Not found')

function decrypt(sourceBytes, mnemonic) {
  console.log('Trying...\n' + mnemonic)
  var entropy;
  try {
    entropy = bip39.mnemonicToEntropy(mnemonic)
  } catch(e) {
    return false;
  }
  var keyArray = hex.hexToBytes(entropy)
  var key = Buffer.from(keyArray)
  
  var nonce = sourceBytes.slice(0, nonceSize)
  var cipherContent = sourceBytes.slice(nonceSize, sourceBytes.length - tagSize)
  var tag = sourceBytes.slice(sourceBytes.length - tagSize)
  
  var decipher = crypto.createDecipheriv('aes-256-gcm', key, nonce)
  decipher.setAuthTag(tag)
  
  try {
    var dec = decipher.update(cipherContent, 'hex', 'utf8')
    dec += decipher.final('utf8')
  } catch(e){

  }

  return dec
}
```

**Comment by adriano-pinaffo** [comment]
> @roeierez can you please take a look?

I managed to borrow an android phone and there I could download the backup.
Then I put in my PC, adapted @fresheneesz script (thank you so much for the initial work), and created my script that permutes all the 24 words for the 2000+ words in the wordlist. In a matter of seconds I found out I had mistyped one single letter but the word was still valid.

That's why I back up @fresheneesz idea that it seems to be an extremely poor design choice to use mnemonics instead of passwords.

Anyway, if anyone needs this in the future...

```
// based on the work of @fresheneesz described here: https://github.com/breez/breezmobile/issues/383

var bip39 = require('bip39')
var hex = require('convert-hex')
var crypto = require('crypto')
var fs = require('fs')

var nonceSize = 12
var tagSize = 16

// add your 24 words (the ones you think are right)
var mnemonic = [

  "word1",
  "word2",
  "word3",
  "word4",
  "word5",
  "word6",
  "word7",
  "word8",
  "word9",
  "word10",
  "word11",
  "word12",
  "word13",
  "word14",
  "word15",
  "word16",
  "word17",
  "word18",
  "word19",
  "word20",
  "word21",
  "word22",
  "word23",
  "word24",

]

// Download the wordlist by cloning the github repository.
// I had to remove the first and last lines to parse it.
var wordlist = JSON.parse('[' + fs.readFileSync("./lib/routes/security_pin/backup_phrase/wordlist.dart", 'utf-8').replace('const WORDLIST = [', '').replace('];', '') + ']')

var encryptedSourceBytes = fs.readFileSync("/home/user/Downloads/breez/backup1/breez.db")
var decrypted = false;

var decryptRes = decrypt(encryptedSourceBytes, mnemonic.join(' '));
if (decryptRes)
  decrypted = true

// the 2 for below will permute all of the 24 words you provided
// if only one of the words is wrong, the correct sequence will be found
for (i=0; i<mnemonic.length; i++) {
  if (decrypted)
    break;
  var mnemonicCopy = [...mnemonic];
  for (j=0; j<wordlist.length; j++) {
    mnemonicCopy[i] = wordlist[j]
    var decryptRes = decrypt(encryptedSourceBytes, mnemonicCopy.join(' '));
    if (decryptRes && /account/.test(decryptRes)) {
      decrypted = true
      break;
    }
  }
}
if (decrypted)
  console.log('Found')
else
  console.log('Not found')

function decrypt(sourceBytes, mnemonic) {
  console.log('Trying...\n' + mnemonic)
  var entropy;
  try {
    entropy = bip39.mnemonicToEntropy(mnemonic)
  } catch(e) {
    return false;
  }
  var keyArray = hex.hexToBytes(entropy)
  var key = Buffer.from(keyArray)
  
  var nonce = sourceBytes.slice(0, nonceSize)
  var cipherContent = sourceBytes.slice(nonceSize, sourceBytes.length - tagSize)
  var tag = sourceBytes.slice(sourceBytes.length - tagSize)
  
  var decipher = crypto.createDecipheriv('aes-256-gcm', key, nonce)
  decipher.setAuthTag(tag)
  
  try {
    var dec = decipher.update(cipherContent, 'hex', 'utf8')
    dec += decipher.final('utf8')
  } catch(e){

  }

  return dec
}
```

**Comment by adriano-pinaffo** [comment]
About the funds, the wallet now says the transaction had expired and that I will be able to redeem the funds in one more block (whatever that means). Let's see
