### ISSUE TITLE
Handle `lightning:name@domain.com` URIs correctly.

### ISSUE THREAD

**Issue by nochiel** [breez/breezmobile#616]
## Bug

- `lightning:name@domain.com`  is not handled when scanned from QR code or pasted from clipboard.

## Rationale

> [Y]ou want to differentiate lightning addresses from "regular" addresses in some cases. 

## References

- breez/breezmobile/pull/560
- https://twitter.com/dergigi/status/1454444857255211022?t=4IcLkvZ0yAUngXKSpdycvg
- https://github.com/andrerfneves/lightning-address/blob/master/README.md
- https://github.com/lightningnetwork/lightning-rfc/blob/46c454cb567326f03107d249b3ac56df965bfd7f/11-payment-encoding.md#encoding-overview
- https://lightningaddress.com/

**Comment by MaxHillebrand** [comment]
Not URI related, but if I manually type in `user@domain.com ` [notice the space at the end] then it says `Invalid invoice or ID`. 

Trailing whitespace should be ignored!

**Comment by nochiel** [comment]
> Not URI related, but if I manually type in `user@domain.com ` [notice the space at the end] then it says `Invalid invoice or ID`.
> 
> Trailing whitespace should be ignored!

Thank you, @MaxHillebrand. I'll fix that too.
