### ISSUE TITLE
TLV record field types incorrect

### ISSUE THREAD

**Issue by daveajones** [breez/breezmobile#624]
Some of the types on the JSON properties are incorrect (feedID and value_msat_total should be integers, not strings for example).  It might be worth taking a look through the TLV 7629169 spec just to make sure everything matches up:

https://github.com/satoshisstream/satoshis.stream/blob/main/TLV_registry.md#field-7629169

I'll look at doing a pull request also to help out.

**Comment by kingonly** [comment]
Published
