### ISSUE TITLE
json decode (status: 502 Bad Gateway): invalid character '<' looking for beginning of value 

### ISSUE THREAD

**Issue by prayank23** [breez/breezmobile#626]
Why do I see this error when I click on Send -> Send to BTC Address in app?

![image](https://user-images.githubusercontent.com/13405205/141203799-9c006da1-1e94-4551-9733-08b9f42ab639.png)

App and device details:

Breez version 0.12-beta
Android 10
OnePlus 6

**Comment by kingonly** [comment]
The Boltz service is down for maintenance:
https://t.me/breez_lightning/21263

Should be up soon.
