### ISSUE TITLE
Breez should ignore HTTP status code in LNURL flows

### ISSUE THREAD

**Issue by rkfg** [breez/breezmobile#628]
When trying to pay to my Lightning address I get this:
![Screenshot_20211114-183543](https://user-images.githubusercontent.com/184066/141687823-fcea334e-c3e9-44ff-b515-40b1adf33185.png)
[The spec](https://github.com/fiatjaf/lnurl-rfc/blob/luds/01.md#http-status-codes-and-content-type) says: `Neither status codes or any HTTP Header has any meaning. Servers may use whatever they want. Clients should ignore them (and be careful when using libraries that treat responses differently based on headers and status codes) and just parse the response body as JSON, then interpret it accordingly.`

**Comment by kingonly** [comment]
Why doesn't the spec follow normal http conventions?

**Comment by rkfg** [comment]
That's up to the spec authors. Still, 201 is an "ok" code so it shouldn't break the flow I think.

**Comment by kingonly** [comment]
It's 'Created'. Not sure why it should be used in this context. The spec isn't set in stone.

**Comment by rkfg** [comment]
Yes, it's not 200 OK but it's in the 2xx range. It's an implementation detail and I sure can change it on my side. But currently Breez doesn't conform to the spec so I decided to report that. Feel free to escalate to the spec authors if you have objections (I'm neutral about this).

**Comment by kingonly** [comment]
We will push a fix to support 2xx codes for now.
@nochiel please discard, @roeierez is already on it.

**Comment by kingonly** [comment]
All 2xx are accepted now
