### ISSUE TITLE
Year 1969 on expiration date on transaction on pending state

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#629]
Year 1969 on expiration date on transaction on pending state

![photo_2021-11-16_11-28-22](https://user-images.githubusercontent.com/1178856/142004021-816fa937-fe2c-4126-936d-cd60d261e76b.jpg)

**Comment by kingonly** [comment]
Although there's probably a bug here, this isn't something we reproduce. Can we close it for now?
