### ISSUE TITLE
When paying a lighting invoice via link, there is no fiat value shown to protect from overcharges.

### ISSUE THREAD

**Issue by Transisto** [breez/breezmobile#631]
![telegram-cloud-photo-size-1-4951773404965480767-y](https://user-images.githubusercontent.com/388716/142505289-d607a6b9-5c74-4fe8-aa0f-f755d72462d6.jpg)

**Comment by kingonly** [comment]
1. You can long press the amount to get the fiat value
2. Make sats your unit of account

**Comment by Transisto** [comment]
Great thanks, not obvious though.
