### ISSUE TITLE
Add support for Paying to internet identifiers (e-mail like)

### ISSUE THREAD

**Issue by iBobik** [breez/breezmobile#634]
https://github.com/fiatjaf/lnurl-rfc/blob/luds/16.md

**Comment by kingonly** [comment]
If that's the same as Lightning address, we already support it in the Paste dialog.

**Comment by MaxHillebrand** [comment]
Ftr, you can also just type in the lightning address (email like) in the invoice field and it will work as well.

**Comment by iBobik** [comment]
Aha, I haven't found Breez mentioned in the RFCs README.

Honza Pobořil
