### ISSUE TITLE
problems with podcast boost

### ISSUE THREAD

**Issue by LightningHelper** [breez/breezmobile#637]
Not sure what is the problem, but when I try to boost an episode I first see the full boost size (in pending) and then it switch to a very small amount of satoshis, see here:

![image](https://user-images.githubusercontent.com/35897350/143509222-47a6e262-ed99-4aab-b0a0-9c18e3f455ed.png)

Any idea what is going on?

**Comment by kingonly** [comment]
It's not a bug, Breez is failing to route the payment. This should be handled in support (contact@breez.technology).

**Comment by LightningHelper** [comment]
So what I need to do? send them an email ?

**Comment by kingonly** [comment]
Yes, but make sure the node is ok to accept keysend.
When I try to keysend to 03ab8660c26c3425381d3019fd8ff93518db59c7782cb365b8d6e7006af800608f it fails almost immediately, not sure why. lnd gives no route, but the failure is immediate, so perhaps there's something else hiding there.

**Comment by LightningHelper** [comment]
which node?
