### ISSUE TITLE
Allow to see transactions and balance in a POS mode

### ISSUE THREAD

**Issue by iBobik** [breez/breezmobile#643]
Most of businesses I work with has workflow like: After a shift (once or multiple times a day) they "close cashier" - could cash and card transactions and alight it with data in a cash register. For this cash register apps usually has "close casher" feature which will print summaries of all payments by a method since last close (e.g. Cash: 12345 CZK, Cards 23456 CZK and Bitcoin 345 CZK).

Problem is that when Breez is locked in POS mode, employees cannot see balance nor transactions they did since last counting.

Could you add option to allow access to a transactions list and balance in the POS mode?
To have it useable it is good to show amounts in a fiat and to show transactions with summaries by days.

**Comment by kingonly** [comment]
There is a Transactions view in POS mode

**Comment by iBobik** [comment]
There is also another use case: When transaction fails or takes time, service often close transaction dialog before making sure what happened. Often customer tells them a few secons after they closed it transaction was successful. But service cannot verify it, cannot just see last transactions and be calm they will not have to pay it from their salary.

**Comment by kingonly** [comment]
![Screenshot_20211201-181401](https://user-images.githubusercontent.com/31890660/144271072-eb3c5aad-5477-4b63-9a67-fdbc24f21884.jpg)

**Comment by iBobik** [comment]
Aha, thank you, I tried only balance screen.

So there are the rest of the points - see fiat amounts in a list and summaries by days. I see it only in a export, but this is not handy for their use-cases.
