### ISSUE TITLE
Better support devices without camera

### ISSUE THREAD

**Issue by iBobik** [breez/breezmobile#650]
Some cashier tablets does not have camera (usually whitelabel Android tablets), but Breez still offer taking QR codes by camera.

Also it will be nice to support more ways how to send money without scannig QR codes. Like outgoing LNURL-withdrawl (of course only when wallet is running).

**Comment by kingonly** [comment]
You can still send or receive w/o a camera. LNURL is supported by copy/paste for example or using Send> Paste Invoice or ID. Same for BTC address.

**Comment by iBobik** [comment]
Yes, but this cashier tablets usually have no IM accounts installed. Screen
is the only useable way how to communicate easily with devices nearby.

How about offering Connect to Pay URL also as a QR code? There is room for
it on the screen.


Honza Pobořil


13. 12. 2021 9:51:51, kingonly ***@***.***> napsal:
