### ISSUE TITLE
Local Nextcloud backups

### ISSUE THREAD

**Issue by BonHodl** [breez/breezmobile#684]
Unable to use local instance of Nextcloud (http(s)://192.x.x.x) for Breez backups. I get an "Invalid URL" message. I have tried a few different url schemes to no avail. 
I have a copy of Joplin syncing notes back to my nextcloud machine just fine. Joplin has documentation for the exact url to use for syncing.

**Comment by yaslama** [comment]
@BonHodl Can you please re-try with the latest version of Breez? You have to use the webdav url of Nextcloud like http://<ip address>/remote.php/dav/files/<username>. You can see the webdav url when you click on the settings button in the lower left corner of the nextcloud page when browsing files. If you use https, the server need to have a valid certificate signed by a valid CA.

**Comment by kingonly** [comment]
We don't provide that option. Only http will work in this case.

**Comment by BonHodl** [comment]
> We don't provide that option. Only http will work in this case.

Ok thanks. Any chance this would be something added in the future?

**Comment by kingonly** [comment]
Why is it needed? What's the meaning of using https when ignoring certificates? Why not use http in this case? We're aware that some apps support it (seems to be for legacy), but some apps don't and really not sure why we need to... We're trying to be extra careful when it comes to the security stack.

**Comment by BonHodl** [comment]
I guess for network security in transport as I understand it. I know if my network was compromised I am in trouble for many things but at least snooping traffic between my devices and the local server would be safe. The server itself would need authorization to access as well so it's just protecting the data transfer. 
Ay least that's how I understand it.

**Comment by yaslama** [comment]
> I know if my network was compromised I am in trouble for many things but at least snooping traffic between my devices and the local server would be safe.
If your network is compromised, you are vulnerable to a MITM (man in the middle attack) because an invalid certificate is accepted, so the attacker can snoop the traffic between Breez and the local server. In fact an invalid certificate gives you the wrong impression that the traffic is secure.

**Comment by kingonly** [comment]
I'm closing this for now.
