### ISSUE TITLE
 Add support for lnurl-pay image data

### ISSUE THREAD

**Issue by torkelrogstad** [breez/breezmobile#685]

**Comment by torkelrogstad** [comment]
This is by the way also an issue in Phoenix, I posted the same issue there: https://github.com/ACINQ/phoenix/issues/234

**Comment by kingonly** [comment]
We don't support LNURL-Pay thumbnails

**Comment by kingonly** [comment]
I changed the title/description. There's no issue with the specific thumbnail, we just need to add support for it, but not sure when it will happen. PRs welcomed.

**Comment by kingonly** [comment]
Added in latest update
