### ISSUE TITLE
wallet blown away by upgrade

### ISSUE THREAD

**Issue by clayt0nk** [breez/breezmobile#699]
A simple problem: I accepted the upgrade to the latest version 0.12-beta on Android, and my wallet balance is now zero. This #596 is also me. I never heard back from anyone about #596

**Comment by kingonly** [comment]
We don't handle support cases in github...
Email us to contact@breez.technology and we'll follow up with you. I'm surprised you are saying no one followed up with you previously, but to make sure, I'll keep this issue open.
