### ISSUE TITLE
Currency reorder causes checkmark glitch 

### ISSUE THREAD

**Issue by tlindi** [breez/breezmobile#715]
Android 10 - version as of today

Reproduce:
Open Currencies
Seleect currency 
Drag it up or down 

Actual behavior
-Checked currency line duplicates and does not lock to line
-Go to another view, and checkmark is shown where is should not

Desired behavior
-Currencies reorder should work nice without dublicates
-Checkmarks should not be visible on another views

Pls see images.
![InkedScreenshot_20220123-145017_LI-0](https://user-images.githubusercontent.com/7249767/150679569-9f5b061b-f431-4ed4-a319-5bd7542447b3.jpg)

![InkedScreenshot_20220123-144945_LI-0](https://user-images.githubusercontent.com/7249767/150679565-43b29a03-ef39-4b27-bb89-c6ed0434df78.jpg)

![InkedScreenshot_20220123-145017_LI](https://user-images.githubusercontent.com/7249767/150679568-96ebc28a-40cd-492f-aff2-1c6e77bfbaa3.jpg)

**Comment by kingonly** [comment]
@ademar111190 please take a look at this

**Comment by ademar111190** [comment]
I did manage to reproduce here, thank you very much for the report 🙏 
Working on a solution
