### ISSUE TITLE
PoS Receipt printing causes extra post linefeeds

### ISSUE THREAD

**Issue by tlindi** [breez/breezmobile#733]
Issue has occured recently (during Jan 2022). 

Basic Receipt Printer Driver has no updates since last Year. So I assume issue is on Breez.

Please see image
![IMG_20220124_175201](https://user-images.githubusercontent.com/7249767/151009454-fa854bf7-7290-411d-95f2-c975de791bb5.jpg)

**Comment by tlindi** [comment]
This is happening with Android 10 also with another BT Printer.

**Comment by tlindi** [comment]
This is happening with Android 11 also with another BT Printer (GoojPRT PT-210, which is not officially supported by Basic Receipt Printer Driver - https://play.google.com/store/apps/details?id=me.shadura.escposprint&hl=en&gl=US nor paid version https://play.google.com/store/apps/details?id=me.shadura.escposprint.plus&hl=en&gl=US)

**Comment by kingonly** [comment]
I tested with the same driver with mht-p10 and I don't reproduce. @erdemyerebasmaz can you please take a look to verify we're not adding extra space at the end of the PDF?

**Comment by kingonly** [comment]
@tlindi we're really not sure this is a Breez related issue, but we've prepared a test package for you to try:
https://drive.google.com/file/d/1YcQlC93WUdBCwu_Ffn6VF56Yp0aCVXUF/view?usp=drivesdk
Please let us know if it helps.

**Comment by tlindi** [comment]
> @tlindi we're really not sure this is a Breez related issue, but we've prepared a test package for you to try: https://drive.google.com/file/d/1YcQlC93WUdBCwu_Ffn6VF56Yp0aCVXUF/view?usp=drivesdk Please let us know if it helps.

I'm not able to create invoice with this version :-( Not Even with My Own node (as If Breez Deafault is having issues at The moment)

**Comment by kingonly** [comment]
We're aware, let's wait till our IT issues are resolved.

**Comment by tlindi** [comment]
![IMG_20220129_213405](https://user-images.githubusercontent.com/7249767/151675058-1e9c3b31-a361-4571-abee-412c2bda191a.jpg)
Not as Bad as originally. What size  PDFvyou create A4 or Letter? Why are bit hard to print into 58mm Receipt Printer ;)

**Comment by kingonly** [comment]
A4, but the driver should be able to handle it...
We'll commit this change to master (fyi @erdemyerebasmaz).

**Comment by tlindi** [comment]
Works for me. Real solution would be 80mm printer which would eg supported eg Basic Receipt Printer Driver.

What are your printers and are they documented somewhere?
Do you testprint Via LAN, BT and/or USB? If BT which driver App you have?

**Comment by kingonly** [comment]
I use this http://www.hit-global.cn/products_view_714.html
With the same driver you use (https://play.google.com/store/apps/details?id=me.shadura.escposprint&hl=en&gl=US).

**Comment by tlindi** [comment]
BTW: Where I can check installed Breez version & build? 

It's booting to uninstall & reinstall+restore quite often.

**Comment by kingonly** [comment]
Don't you install from Google Play?

**Comment by tlindi** [comment]
Installed for this test the special version from link above. Usually I install from Play or Apple Stores.

**Comment by kingonly** [comment]
Yep, this is an exception. We will try to push the fix to Google Play today.

**Comment by tlindi** [comment]
Thanx. I also purchased Plus version of driver (https://play.google.com/store/apps/details?id=me.shadura.escposprint.plus&pli=1)

Its release notes say especially notes it does NOT support GoojPRT PT-210 (MTP-II), but print is perfect. Only 2 lines extra feed.

So it seem to issue in Xprinter emulation the driver free version is using. Paid version uses GoojPRTn support. See image below:

![session-attachment-2022-02-02-143901](https://user-images.githubusercontent.com/7249767/152155557-c2c762e7-10b4-47fe-ac6b-97be4fb8336f.jpg)

Works for me.

**Comment by kingonly** [comment]
Nice!

**Comment by kingonly** [comment]
The fix was published, might take some time to be approved.
