### ISSUE TITLE
Replace keysend with AMP

### ISSUE THREAD

**Issue by Kixunil** [breez/breezmobile#743]
According to [LND doc](https://github.com/lightningnetwork/lnd/blob/1482e5e20ab974e431ca994e91ce8dbc7f3bbb91/sample-lnd.conf#L386), keysend shouldn't be used anymore and AMP should be preferred.

Using keysend only puts people into awkward situation when they have to enable a deprecated option.

**Comment by kingonly** [comment]
What exactly you want us to replace? Are you referring to podcasting? Because that's not our specification.

Not sure AMP is going to last either, probably is going to replaced by bolt12.

**Comment by kingonly** [comment]
Btw, when keysend came up in the roundtable with LL, roasbeef stated it's not going to be deprecated soon (even once AMP is enabled). So this also requires some clarification.

**Comment by Kixunil** [comment]
> Are you referring to podcasting?

Yes, sorry for being unclear.

> Because that's not our specification.

Where can I raise this issue then?

> it's probably going to be replaced by bolt12

Good point!

>  roasbeef stated it's not going to be deprecated soon

OK, I wanted to avoid supporting keysend just to remove it later but looks like I can't.

**Comment by kingonly** [comment]
Value block specification is here:
https://github.com/Podcastindex-org/podcast-namespace/blob/main/value/value.md#value-element

Dave and Adam (podcasting 2.0 leaders) are well aware of the alternatives and waiting to see where the chips falls.

Btw, I also DMed you on telegram on this.
