### ISSUE TITLE
BTCPay LNURL-Pay IS not working

### ISSUE THREAD

**Issue by tlindi** [breez/breezmobile#748]
![IMG_20220130_195230](https://user-images.githubusercontent.com/7249767/151711215-b796699d-e573-433f-82ab-cd65e0bd830d.jpg)

Scan and result is

![Screenshot_20220130-194951](https://user-images.githubusercontent.com/7249767/151711230-a796c476-7458-4b37-b802-2badd60cf24a.png)

**Comment by kingonly** [comment]
Are you sure this is a Breez issue? Does it work in another wallet?

**Comment by MaxHillebrand** [comment]
I believe this is a btcpay issue... https://github.com/btcpayserver/btcpayserver-plugins/issues/6

**Comment by tlindi** [comment]
Yep same. Same error on my BTCPay logs. And ofcource it doesn't work with other wattets either. Thanx @MaxHillebrand

**Comment by kingonly** [comment]
Closing here for now.

**Comment by tlindi** [comment]
BTCPay 1.3.x supports only LNULR-bech32, not clear text text URL:s. 
See
![image](https://user-images.githubusercontent.com/7249767/151773882-16b0bbca-479a-47ff-bdf0-91171fb5d282.png)

bech32 QR:s work for me.
:)
