### ISSUE TITLE
Unexpected funds exclamation icon should disappear if is a low value

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#755]
Hi,

Unexpected funds exclamation icon should disappear if is a low value that is not possible to send to other address because of fee.

![photo_2022-02-03_10-05-34](https://user-images.githubusercontent.com/1178856/152348771-f2f5cdba-95ad-4013-9e8e-abc70b2fcee6.jpg)

**Comment by kingonly** [comment]
Won't fix. It's not ideal, but we don't want to add heuristics to the code.
