### ISSUE TITLE
No success after fixing network on no_connection_dialog_title

### ISSUE THREAD

**Issue by tlindi** [breez/breezmobile#759]
Android

Reproduce: 
Turn off all data networks
Start Breez
You see no network notification
Turn on mobile data and / or Wi-Fi
Select retry on notification window
Notification keeps popping up

Workaround:
Wait for some (minute or so) time After data/wifi is turned on
Select Retry
Notification disappears and Breez works normally

I think there was network connectivity exclamation mark related PR or issue Open. Maybe this could be solved under same fix.

**Comment by kingonly** [comment]
For me, it takes a few seconds till the try again works, but not a minute. Tested on several devices...

**Comment by tlindi** [comment]
Maybe I'm not patient enougth. Screenvideo: https://lindfi-my.sharepoint.com/:v:/g/personal/tomi_lind_fi/EQUVU2VMDb9Fo9go32yh2I0Bhnbe9w1JGMwsRkV5UBqP_A?e=BssfwG

I think this could be fixed just by adding one line to proposed fixes above Cancel and TRY AGAIN. Like this? #775

**Comment by kingonly** [comment]
Closing for now
