### ISSUE TITLE
[Feature Request] Improve backup by including PoS Settings and data onto backup

### ISSUE THREAD

**Issue by tlindi** [breez/breezmobile#780]
Please include Avatar, PoS Settings, Currencies and Items onto backup.

Also Receipt Printing is not possible after restore for PoS transactions prior restore.

**Comment by kingonly** [comment]
@erdemyerebasmaz please take a look. Podcasts in library is another item. Keep in mind that efficiency is key and we already backup breez.db so one approach would be to store everything there. @roeierez should advise.
