### ISSUE TITLE
Improve Transactions UI for merchant's accounting

### ISSUE THREAD

**Issue by iBobik** [breez/breezmobile#784]
From merchants using POS mode (locked by manager password) I have a feedback about usability of the transactions list.

Merchants (at least in my country) every day after business close they do "financial statements" - they count all cash money, today cards transactions, vouchers and also Bitcoin received and compare it with a sales report in POS (the main one). This is necessary everyday pain for every waitress in small pubs or shift manager in bigger restaurants.

Breez does not help, but complicates things. For adoption we need to not annoy people who accept Bitcoin. :-)

Current issues:
- transactions list does not show fiat amount (major)
- can not see summary of today transactions (major)
- can not see wallet balance when locked by manager password (minor, good for investigations in case of deficiency)
- they can not easily see today just transactions (minor, can use filters)

Proposed solution:
- Add row with fiat amount or add switch between fiat or sats in menu (most important)
- Group transactions by days
- Show summary for each day 
- Add filter to see only incoming transactions (less important because merchants usually does not send money on a shift)

**Comment by tlindi** [comment]
+1

And possibility to make same optionally weekly and monthly basis. Cause all the merchants do not report on daily basis.

**Comment by kingonly** [comment]
I understand the requirements, but see if you can use the csv for now. It contains fiat values and dates.

**Comment by kingonly** [comment]
No need to send to an accountant... Anyone can do it and you can even use a simple Excel macro.

**Comment by kingonly** [comment]
We're aware there are gaps. However, meanwhile that exactly where you guys can contribute to provide a complete solution.

**Comment by iBobik** [comment]
CSV is a way, but restaurants here do it on site without a computer. Sending CSV somewhere is exactly that pain in the ass what will stop adoption when there will be more Bitcoin payments every day. Currently it is rare to have more than a few Bitcoin customers a day and most of days none, so counting manually works.

**Comment by kingonly** [comment]
I was referring to it as an interim solution. One can develop a simple mobile app that generates the necessary information from the csv.

**Comment by tlindi** [comment]
> CSV is a way, but restaurants here do it on site without a computer. Sending CSV somewhere is exactly that pain in the ass what could turn waitresses against Bitcoin when there will be more payments every day. Currently it is rare to have more than a few Bitcoin customers a day and most of days none, so counting manually works.

^ word. I couldn't agree more.

**Comment by kingonly** [comment]
Sales report was added in the latest release

**Comment by iBobik** [comment]
@kingonly Nice, it helps when there are more transactions a day, but this is not common. Much bigger pain is that all amounts are in sats only.

**Comment by kingonly** [comment]
The report shows the aggregated fiat amount (if all the sales were in the same fiat value).

**Comment by iBobik** [comment]
Aha, fiat field is shown only when there are some transactions. :-)


Honza Pobořil


30. 3. 2022 14:09:35, Roy Sheinfeld ***@***.***> napsal:
