### ISSUE TITLE
Suggestion: Add option to users choose themes for other colors on UI

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#797]
Hi,

Maybe not a priority, but would be great to have an option to choose themes for other colors on UI. 
For example: I like dark color but I don't like the dark color of Breez. I would like something like this:

![photo_2022-03-09_10-42-16](https://user-images.githubusercontent.com/1178856/157453401-acf4f153-12f8-4e89-b975-e7bf85f93c54.jpg)

**Comment by kingonly** [comment]
Not in our plans
