### ISSUE TITLE
UI: Implement easy App version & build check

### ISSUE THREAD

**Issue by tlindi** [breez/breezmobile#807]
Developers -> getinfo shows LND version not App, right?

**Comment by kingonly** [comment]
Google Play/App Store shows this information. Why this is needed?

**Comment by tlindi** [comment]
![Screenshot_20220330-150320](https://user-images.githubusercontent.com/7249767/160830330-f820a3a5-15ea-4b1c-b105-6feeea9ca710.png)
Yes, Play shows 0.12-beta and date, but no build.

 Wouldn't it Be nice to check version without Google services for ones installing from APK?

**Comment by kingonly** [comment]
We don't see a need to implement it right now.

**Comment by MarnixCroes** [comment]
+1 version is useful info
