### ISSUE TITLE
Increase timeout for LNURL withdraw

### ISSUE THREAD

**Issue by theDavidCoen** [breez/breezmobile#848]
When I scan a LNURL withdraw link I made with lnbits (on legend.lnbits.com), I get this warning.
I'm able to scan it with other wallets, for example Wallet of Satoshi or Zeus.
![CsY0ibv2](https://user-images.githubusercontent.com/38695835/161376854-abaa61c3-f09f-426c-bf45-d2c875b32c87.jpg)

I suggest to increase the timeout, but the fix should be general, not specific for that demo service.

You can use this LNURL withdraw link for testing:
lightning:LNURL1DP68GURN8GHJ7MR9VAJKUEPWD3HXY6T5WVHXXMMD9AMKJARGV3EXZAE0V9CXJTMKXYHKCMN4WFKZ7M6YWQEN2EJHXEEXYKR60F38JETSGSM9JENY9UE55526DUE8W5R6V4SHY3ME2DZYVKNF2FR42Y8VK7R

Or create a new one on https://legend.lnbits.com (you need to fund a wallet and activate LNURL-withdraw plugin).

**Comment by kingonly** [comment]
@erdemyerebasmaz please look into it. I tested the link in WoS and it takes a while to load, cso our timeout might be too short for slow servers.

**Comment by erdemyerebasmaz** [comment]
Average response time for the query at hand proved to be ~20 seconds with various dns & proxy settings, low bandwidth tests. The timeout has been increased to 30 seconds.
![Screenshot_20220403_210543_com breez client debug](https://user-images.githubusercontent.com/4012752/161441915-32decabe-6eae-4422-b9ff-cd642419a249.jpg)

**Comment by kingonly** [comment]
Fixed in latest
