### ISSUE TITLE
Pay button missing when using "Connect to pay"

### ISSUE THREAD

**Issue by hokkanen** [breez/breezmobile#88]
After connecting through "Connect to pay" with a friend and setting "Sat Amount" and "Note", there is no pay-button to proceed with the payment, although a connection is established (both have green dots). My friend had this button, and everything worked fine, but I don't have that button. The affected device is Doogee S60.

**Comment by kingonly** [comment]
Sorry... Although we're trying to test many devices, it's impossible to test them all...

Can you please send a screenshot? This would help us understand what went wrong with the render. 
Do you see a button in the 'Remove Funds' screen?
Can you try a smaller display size to see if it helps?

Thanks for your report!

**Comment by hokkanen** [comment]
![Screenshot_20190414-185816](https://user-images.githubusercontent.com/15683479/56090743-9a433f00-5ee9-11e9-9030-f71f51f4510e.png)

Yes, I can see "Remove" button when selecting "Remove Funds".

**Comment by kingonly** [comment]
Thanks! I'm also guessing you can't scroll down, right?

**Comment by hokkanen** [comment]
Yes, that is right. Nothing happens when I try to scroll down.

**Comment by kingonly** [comment]
Got it. we'll take a look ASAP. If you're able to reduce the display size temporarily and let us know, that would also help us to understand what went wrong.

**Comment by hokkanen** [comment]
Tried different font, but still no signs of a button.

**Comment by kingonly** [comment]
OK. We'll let you know once we track down the problem...

**Comment by kingonly** [comment]
We've released an updated package containing a fix to this issue.
Once it becomes available on your device, please update the package and let us know if the problem is fixed ("Fix 'Connect to Pay' screen render on some devices." in the package release notes.)

**Comment by hokkanen** [comment]
It works now, good job!

**Comment by kingonly** [comment]
Perfect 👌 Enjoy...
