### ISSUE TITLE
Dropdown clears the amount after picking the same option

### ISSUE THREAD

**Issue by utkarshshendge** [breez/breezmobile#901]
On the POS keypad screen, the currency type drop-down clears the entered number after choosing the same currency from the drop-down.
Ideally, it should clear the entered number only if the chosen currency is different.
Please see 

https://user-images.githubusercontent.com/57677520/166116056-9a40a4ed-02b6-4328-a8b0-d64cc99bdc0e.mp4

**Comment by utkarshshendge** [comment]
@kingonly I am interested in fixing this. Could you please assign me this issue?

**Comment by kingonly** [comment]
@utkarshshendge go for it! Thanks for the report 🙏
