### ISSUE TITLE
Add support for NFC following the LNURL-withdrawPOS flow reference

### ISSUE THREAD

**Issue by theDavidCoen** [breez/breezmobile#910]
Breez has a great POS UI you can activate with a tap on the side menu. It also has support for LNURL-withdraw.
I believe that if you add NFC support you can improve the UX.

As a reference you could use my repo [LNURL-withdrawPOS](https://github.com/theDavidCoen/LNURL-withdrawPOS).
Other companies/associations are working on that.
See for example [BTCpay's LNURL NFC Support plugin](https://github.com/btcpayserver/btcpayserver-plugins) by  [Andrew Camilleri](https://github.com/Kukks) 

![breez pos](https://user-images.githubusercontent.com/38695835/169787968-1bb9206e-8669-4583-8c64-96c8fb684dc8.jpg)

You can add an "Activate NFC + LNURL withdraw" button/link on the invoice screen, or even better, you could automatically activate the NFC sensor when the user is on POS UI and already selected that option in Settings.

**Comment by kingonly** [comment]
Will publish soon
