### ISSUE TITLE
Swift Compiler Error when trying to launch breezmobile locally on macOs with M1 chip

### ISSUE THREAD

**Issue by moritz-schindelmann** [breez/breezmobile#914]
### Environment
macOs Monterey: Version 12.0.1
Chip: Apple M1 Pro
Flutter 2.10.0 • channel stable
Dart 2.16.0 • DevTools 2.9.2
XCode Version 13.4
go version go1.18.2 darwin/arm64

breezmobile 872ad5f6 (current master head)
breez e3aa150 (current master head)

### Steps to reproduce
1. Breez setup:
```
git clone https://github.com/breez/breez.git
cd breez
go get -d golang.org/x/mobile/cmd/gomobile
go get -d golang.org/x/mobile/cmd/gobind
export PATH=$PATH:$GOPATH/bin
gomobile init
```

2.  Generate bindings.framework in breez repo:
Run `./build-ios.sh`.
-> `build/ios/bindings.xcframework/` is generated.

3. Copy `breez/build/ios/bindings.xcframework/` to `breezmobile/ios/bindings.framework/`

4. Store google service info in `breezmobile/ios/Runner/GoogleService-Info.plist`

5. Run `pod install` in `breezmobile/ios`
-> Output: `Pod installation complete! There are 36 dependencies from the Podfile and 59 total pods installed.`

6. Run `flutter pub get` in `breezmobile`
-> Output:
```
Warning: You are using these overridden dependencies:
! flutter_downloader 1.7.1 from git https://github.com/breez/flutter_downloader.git at c3e528
! podcast_search 0.4.2 from git https://github.com/breez/podcast_search.git at e5edae
Running "flutter pub get" in breezmobile...                         3.3s
The plugin `share_extend` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a
future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
```

7. Run `flutter run --flavor=client`
-> Output:
```
Launching lib/main.dart on iPhone 12 in debug mode...
Exception: The Xcode project does not define custom schemes. You cannot use the --flavor option.
```

8. Run `flutter run` 

### Expected behavior

App is launched on xcode simulator device.

### Actual behavior

Error: 
```
Swift Compiler Error (Xcode): No such module 'Bindings'
/Users/xy/Code/breezmobile/ios/Plugins/Breez/BreezLib/iCloudBackupProvider.swift:10:7


Uncategorized (Xcode): Command EmitSwiftModule failed with a nonzero exit code


Could not build the application for the simulator.
Error launching application on iPhone 12.
```

**Comment by roeierez** [comment]
Thanks for the details @moritz-schindelmann I noticed you copied the xcframework folder while currently we require copying the specific architecture framework which in your case should be:
ios/bindings.xcframework/ios-arm64/Bindings.framework

Can you try that please?

**Comment by moritz-schindelmann** [comment]
Thanks for the quick response.
Correctly copying the bindings got me one step further:
```
Target Integrity (Xcode): Building for iOS Simulator, but the linked framework 'Bindings.framework' was built for iOS.
/Users/xy/Code/breezmobile/ios/Runner.xcodeproj
```

**Comment by roeierez** [comment]
If you are building for the simulator it is different architecture and you should copy:
ios/bindings.xcframework/ios-arm64_x86_64-simulator/Bindings.framework/

In order to create this framework you should change the build.sh. Just change the gomobile command to build with different target: 
-target=iossimulator

**Comment by moritz-schindelmann** [comment]
Awesome, that worked. Thank you!

**Comment by AlexFront2021** [comment]
> If you are building for the simulator it is different architecture and you should copy: ios/bindings.xcframework/ios-arm64_x86_64-simulator/Bindings.framework/
> 
> In order to create this framework you should change the build.sh. Just change the gomobile command to build with different target: -target=iossimulator

Please could you clarify what is command I have to use? gomobile build -target=iossimulator doesnt work.
