### ISSUE TITLE
Eurosign printed incorrectly on receipt

### ISSUE THREAD

**Issue by tlindi** [breez/breezmobile#916]
Using Nokia 5.1 Plus and (non-paid version) Basic Receipt Printer Driver (paid version name is Receipt Printer Driver) prints euro sign incorrectly on "Item, Price, Amount, Total -line.

"Total sat (nn €)" line prints sign correctly. Please see image.
![IMG_20220601_212208](https://user-images.githubusercontent.com/7249767/171476007-a30567d3-8c9c-421d-bb8a-c9d97cad63bf.jpg)

**Comment by kingonly** [comment]
I just tested with the free driver and I get a wrong sign in the total amount also. This is definitely a bug in the driver as the regular printer works as expected. Not sure what we can do here besides using 'EUR' instead of '€' but that wouldn't look as good.
Can you maybe contact the driver creators?

**Comment by tlindi** [comment]
I'm not sure if EUR would work - U know better ;-)

If multible sales Items can only be only added with one currency then ASCII fiat Name (EUR, USD, etc) would work.

Unfor driver developer is not too find of to reply my contact. Or he asks fees for changes to his product.

**Comment by kingonly** [comment]
@ademar111190 let's change the currency representation in the receipt to 3 letters instead of a symbol. Sales view should be the same as today with one exception: Let's use丰 for sats (currently we use Ş) which is becoming more popular.

**Comment by kingonly** [comment]
Everywhere (all the places in the POS functionality)

**Comment by kingonly** [comment]
Fixed in latest
