### ISSUE TITLE
Invoice payment displays is BTC/sats

### ISSUE THREAD

**Issue by tcharding** [breez/breezmobile#925]
When paying an invoice the mobile app displays the amount to pay in sats, this is inconvenient because typically I am paying a fiat amount and since the receiver created the invoice it is not possible to verify the amount. Said another way, Alice wants to pay Bob $50, Bob creates an invoice for $55 and shows it (or sends it) to Alice, Alice sees the amount in sats and since it is kind of close pays it - Bob wins.

**Comment by kingonly** [comment]
You can log press the amount in the dialog to see the fiat value.

**Comment by tcharding** [comment]
Oh sweet! Thanks

**Comment by MarnixCroes** [comment]
Had the same issue.
Would have no idea that this was possible, especially long pressing. Just a quick tap (like at homescreen) makes more sense imo.
