### ISSUE TITLE
Breez wallet goes offline

### ISSUE THREAD

**Issue by tcharding** [breez/breezmobile#926]
Basically every time I open Breez [*] the app says it is 'offline'. I have to go into the phone's app settings and force quit the app, restarting the app then connects to the network correctly and displays balance.

Phone: Pixel 4a, Calyx OS 3.6.0 , Android 12
Network: bb1.breez.technology

[*] - does not happen if I close the app and re-open it immediately or within a few minutes. I only typically use the app once every week or so and each of these times it is what I mean by 'basically every time'.

**Comment by kingonly** [comment]
Seem to be an issue specific to your environment.
Perhaps calyx closes the network and not the app and Breez cannot recover. 
Let's follow up via email: contact@breez.technology

**Comment by tcharding** [comment]
Cool, cheers.
