### ISSUE TITLE
Closing channel pending for over a month (limbo)

### ISSUE THREAD

**Issue by enoughofme** [breez/breezmobile#928]
Hello, last month I sent funds from the breez app to an on chain address. My app began showing a "pending channel close" and a month later is still showing the same message and the funds have not been received on the other side. 

In the pending channels on the developer tab it shows the amount as a "limbo balance" and "anchor": "LIMBO" 

This is not in my wheel house, and I don't even know if I'm reaching out to the right place. But I'm having no luck in the contact us on the breez website.

**Comment by kingonly** [comment]
Github isn't really the right medium for support. Please email us to contact@breez.technology.
