### ISSUE TITLE
"invalid pair hash" error in "Send to BTC Address"

### ISSUE THREAD

**Issue by andrasfuchs** [breez/breezmobile#942]
I tried to send a few satoshis to a BTC address, but I got this weird "invalid pair hash" error.

![image](https://user-images.githubusercontent.com/910321/179219472-4f7426df-2641-4d01-a858-656b49b76f6f.png)

It would be great if there was some explanation what the exact problem is, and what can I do about it. I have no idea now.

Also it would be better if the Boltz fee and transaction fee would be displayed in fiat too (like in the you receive row).

**Comment by kingonly** [comment]
We actually don't know more details, this is an error retuned by Boltz

**Comment by andrasfuchs** [comment]
@kingonly Thank you for the quick reply!

Does this mean that Breez doesn't have the function at the moment to send Lightning satoshis to BTC addresses?
So is it a general problem as you can tell (with Boltz), or does it only happen to me for unknown reasons?

**Comment by kingonly** [comment]
It seems to be working fine, could you please restart Breez and try again? If the problem persists, please contact us via email contact@breez.technology and we'll follow up with you directly. This is really a support issue, so closing it for now.
