### ISSUE TITLE
Scan to receive

### ISSUE THREAD

**Issue by Falsen** [breez/breezmobile#95]
Would be great if you could scan QR codes for receiving payments. According to lnurl spec:
https://github.com/btcontract/lnurl-rfc.

Saves the trouble of transferring invoice strings to a computer etc.

**Comment by kingonly** [comment]
We support scanning to pay a bolt11 invoice (via the 'pay invoice' action).
The lnurl is for more advanced scenarios, can you please clarify your use case?

**Comment by Falsen** [comment]
So right now depositing into service is fairly simple, you get a QR code on screen, you open your phone and scan it. Which is super convinient, but for withdrawing/receving it's a bit more complicated. You somehow need to transfer the invoice from the phone to the computer, which is kinda awkward. The lnurl spec solves this by adding the possible to scan to receive. The user scans the QR code which has an encoded api url in it. The mobile client connects to the endpoint and sends its generated invoice internally. This way the user never have to handle any invoices!
I have it implemented on my flipping site https://lightningflip.xyz.

**Comment by kingonly** [comment]
Got you 👍 We'll add this to our todos... Thanks!

**Comment by kingonly** [comment]
This was added a few weeks ago
