### ISSUE TITLE
No strings available for Podcast screens

### ISSUE THREAD

**Issue by theDavidCoen** [breez/breezmobile#955]
I translated the app in Italian and I'm testing the strings but noticed that Podcast has no strings to be translated, so all the screens, search fields and other elements are in English.

Can you check and send me the new strings to translate?
![1659613852256](https://user-images.githubusercontent.com/38695835/182840317-bbade70b-a0f1-454b-8018-0826babee245.jpg)
![1659613852241](https://user-images.githubusercontent.com/38695835/182840326-9294ff15-f3cd-48ee-87b9-38bcf2765317.jpg)
![1659613852227](https://user-images.githubusercontent.com/38695835/182840334-4f7cbdb9-eb82-4f29-83b4-c29efa9aeffc.jpg)

**Comment by kingonly** [comment]
@ademar111190 fyi

**Comment by ademar111190** [comment]
That is correct @theDavidCoen the podcast player is a 3rd party library called Anytime so to add translations to it you need to translate more arb files…

Breez has its fork of anytime here: https://github.com/breez/anytime_podcast_player/blob/breez-merge/lib/l10n/intl_en.arb fell free to translate it and open a PR there and add me as a reviewer.

**Comment by theDavidCoen** [comment]
@ademar111190 got it. I'm gonna check and open a PR, but probably after you submit the new update to the stores.

**Comment by ademar111190** [comment]
don't worry @theDavidCoen :)

**Comment by ademar111190** [comment]
Merged 🥳 

As soon as we have a new release it will show Italian texts on Podcast :)

**Comment by kingonly** [comment]
@theDavidCoen can we close this?

**Comment by theDavidCoen** [comment]
@kingonly completed
