### ISSUE TITLE
Feature Request [Developement ]: No issue and PR template in github repository 

### ISSUE THREAD

**Issue by SiddheshKukade** [breez/breezmobile#970]
#### Solution: 
- We can add a `issue template` in the `.github/ISSUE_TEMPLATE/` folder and `.github/PULL_REQUEST_TEMPLATE/`
-  [This Article ](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository )explains benefits of Issues and Pull Request templates -

**Comment by SiddheshKukade** [comment]
@maintainers I would like to take this 👍🏻

**Comment by kingonly** [comment]
I don't think it's useful in our case, this is more of a channel for our users, it less being used for dev communication.

**Comment by SiddheshKukade** [comment]
@kingonly Which chanel is being used for dev communication ?
