### ISSUE TITLE
How do you close your breeze "account" / all channels and redeem your funds?

### ISSUE THREAD

**Issue by fresheneesz** [breez/breezmobile#972]
I was testing doing a full on-chain spend, expecting it to close out my channels, however it left the customary 600 sats in the channel. It seems like it should be possible to close everything out and redeem all your sats.

**Comment by kingonly** [comment]
Send to BTC address is a swap. Off-chain to on-chain tx.
To redeem "everything" you need to close all the channels. RTM: https://doc.breez.technology/How-to-close-Breez's-channels.html
There's no 600 sats of channel reserve for the past two years, your channel is very old.
