### ISSUE TITLE
lnurlw not using http on .onion sites

### ISSUE THREAD

**Issue by dipunm** [breez/breezmobile#977]
as per https://github.com/fiatjaf/lnurl-rfc/blob/luds/17.md

I did a quick test using nfc and saw that it tried to use https on my onion url.

**Comment by dipunm** [comment]
I was using orbot to make breez be able to make tor requests, so in retrospect, breez has no official support for tor, but it would be cool if it did.

**Comment by kingonly** [comment]
Did you do this?
https://t.me/lnurl/32585

**Comment by dipunm** [comment]
Yes

**Comment by dipunm** [comment]
To be clearer, lnurlw:// and other scheme's are converted to `https`, but when `.onion` is used, it could use `http`

**Comment by kingonly** [comment]
Gotcha. We might need your help with a test site, could you please provide an email? @ademar111190 please follow up.

**Comment by dipunm** [comment]
Is there a way to give an email privately? If you provide your email, I can email you... I don't want my email on this public forum.

**Comment by kingonly** [comment]
Sure, please send a note to: contact@breez.technology

**Comment by ademar111190** [comment]
I found the root of the problem, and the fix is here https://github.com/fiatjaf/go-lnurl/pull/13
once it is merged on the `go-lnurl` library, we need to update it on breez lib to have the fix on our app.

**Comment by dipunm** [comment]
Looks like it's merged 👀👀

**Comment by ademar111190** [comment]
Excellent, I'll update it on our library asap, thank you @dipunm

**Comment by kingonly** [comment]
@ademar111190 please verify it's included the latest published package, test and close the issue if so.

**Comment by kingonly** [comment]
Merged to mobile. Will be released in our next update.

**Comment by kingonly** [comment]
Should be fixed in latest
