### ISSUE TITLE
Bad Message UX : Funding Breez Wallet from an empty NFC-Card

### ISSUE THREAD

**Issue by arbadacarbaYK** [breez/breezmobile#978]
When using a LNURLw on the POS to receive funds while having too less sats on the card / card is empty the message is too nerdy and not helpful. Should say smth like "Not enough funds available"
<img width="415" alt="Bildschirmfoto 2022-09-19 um 23 55 28" src="https://user-images.githubusercontent.com/63317640/191126596-aad29c60-ba24-4ac4-af8f-a4264fbc6688.png">

**Comment by kingonly** [comment]
The "Link not working" message is coming from the lnurl service (in this case probably lnbits).
@ademar111190 let's fix the formatting though and just display the error coming from the service w/o the error domain/nslocalizeddescription etc.

**Comment by arbadacarbaYK** [comment]
exactly 🥳 Thanks!

**Comment by kingonly** [comment]
Another use case to improve: https://t.me/breez_lightning/25393
