### ISSUE TITLE
Add transaction report to present fees as a separate column

### ISSUE THREAD

**Issue by tlindi** [breez/breezmobile#981]
UI shows outgoing payment like this:
![image](https://user-images.githubusercontent.com/7249767/192010269-aa943a4e-672e-4ba8-8336-0560be9cefcd.png)
so it is -120sat and -1sat for fees.

Anyhow CSV report export shows total of -120 ie fees are completely invisible:
![image](https://user-images.githubusercontent.com/7249767/192010612-fbfa450c-0a32-44d2-bbab-a620cb6392ec.png)

**Comment by kingonly** [comment]
@ademar111190 please see if we can add payment fees to the csv export
