### ISSUE TITLE
A stuck/conflicted/cancelled on-chain swap deposit transaction will block all further deposits

### ISSUE THREAD

**Issue by MarcoFalke** [breez/breezmobile#988]
Breez claims to be "processing" the previous deposit while it is waiting in the mempool and continues to do so even if it leaves the mempool and eventually conflicts.

https://user-images.githubusercontent.com/6399679/195790964-49e71b28-201d-45b2-a797-0bd9ae5c0d4e.png

**Comment by kingonly** [comment]
Please go to Preferences> Developers screen> top right menu and click 'Reset Unconfirmed Swap'.
Then, restart Breez and see if it helps.

**Comment by MarcoFalke** [comment]
Thanks
