### ISSUE TITLE
Open a channel from another node to Breez

### ISSUE THREAD

**Issue by ElucGeek** [breez/breezmobile#990]
Hello,
I would like to open a channel from my node to a Breez wallet node, so the Breez wallet have more than 100k inbound capacity, how can I do that?

**Comment by kingonly** [comment]
RTM: https://doc.breez.technology/Opening-Channels.html

**Comment by ElucGeek** [comment]
Ok I saw it already but with the node ID only I cannot open, I need the IP and port, I guess I can find the IP I get from the mobile operator but what about the port number? And will it be open to the phone?
