### ISSUE TITLE
POS Default invoicing currency is not included in backup

### ISSUE THREAD

**Issue by tlindi** [breez/breezmobile#994]
Clean installation of Breez.

I remove other currencies from use from settings, except EUR.

Go to POS and see it has default currency, BTC.

I change it to "EUR". (I noticed Breez is not making backup automatically after this change).

I remove app, restore it from backup and I go to POS - invoicing currency is "sat".

IMO currency should be EUR. As it was before uninstall.

**Comment by kingonly** [comment]
This is by design. We don't want to include frequent display changes in the backup and trigger too many unnecessary backups.
